// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminAccountsColumns holds the columns for the "admin_accounts" table.
	AdminAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "username_normalized", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "password_changed_at", Type: field.TypeTime},
		{Name: "singleton_slot", Type: field.TypeInt, Default: 1},
	}
	// AdminAccountsTable holds the schema information for the "admin_accounts" table.
	AdminAccountsTable = &schema.Table{
		Name:       "admin_accounts",
		Columns:    AdminAccountsColumns,
		PrimaryKey: []*schema.Column{AdminAccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "adminaccount_username_normalized",
				Unique:  true,
				Columns: []*schema.Column{AdminAccountsColumns[2]},
			},
			{
				Name:    "adminaccount_singleton_slot",
				Unique:  true,
				Columns: []*schema.Column{AdminAccountsColumns[7]},
			},
		},
	}
	// AdminSessionsColumns holds the columns for the "admin_sessions" table.
	AdminSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "csrf_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "ip_address", Type: field.TypeString},
		{Name: "user_agent", Type: field.TypeString},
		{Name: "admin_id", Type: field.TypeString},
	}
	// AdminSessionsTable holds the schema information for the "admin_sessions" table.
	AdminSessionsTable = &schema.Table{
		Name:       "admin_sessions",
		Columns:    AdminSessionsColumns,
		PrimaryKey: []*schema.Column{AdminSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "admin_sessions_admin_accounts_sessions",
				Columns:    []*schema.Column{AdminSessionsColumns[8]},
				RefColumns: []*schema.Column{AdminAccountsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "adminsession_token_hash",
				Unique:  true,
				Columns: []*schema.Column{AdminSessionsColumns[1]},
			},
			{
				Name:    "adminsession_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AdminSessionsColumns[4]},
			},
		},
	}
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "actor_type", Type: field.TypeString},
		{Name: "actor_id", Type: field.TypeString},
		{Name: "target_type", Type: field.TypeString},
		{Name: "target_id", Type: field.TypeString},
		{Name: "metadata_json", Type: field.TypeJSON},
		{Name: "ip_address", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[8]},
			},
			{
				Name:    "auditlog_action",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[1]},
			},
		},
	}
	// SystemSettingsColumns holds the columns for the "system_settings" table.
	SystemSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "key", Type: field.TypeString},
		{Name: "value_json", Type: field.TypeJSON},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeString},
	}
	// SystemSettingsTable holds the schema information for the "system_settings" table.
	SystemSettingsTable = &schema.Table{
		Name:       "system_settings",
		Columns:    SystemSettingsColumns,
		PrimaryKey: []*schema.Column{SystemSettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "systemsetting_key",
				Unique:  true,
				Columns: []*schema.Column{SystemSettingsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminAccountsTable,
		AdminSessionsTable,
		AuditLogsTable,
		SystemSettingsTable,
	}
)

func init() {
	AdminSessionsTable.ForeignKeys[0].RefTable = AdminAccountsTable
}
