// Code generated by ent, DO NOT EDIT.

package notificationchannel

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the notificationchannel type in the database.
	Label = "notification_channel"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChannelType holds the string denoting the channel_type field in the database.
	FieldChannelType = "channel_type"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldSecretEnvelope holds the string denoting the secret_envelope field in the database.
	FieldSecretEnvelope = "secret_envelope"
	// FieldAllowPrivate holds the string denoting the allow_private field in the database.
	FieldAllowPrivate = "allow_private"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the notificationchannel in the database.
	Table = "notification_channels"
)

// Columns holds all SQL columns for notificationchannel fields.
var Columns = []string{
	FieldID,
	FieldChannelType,
	FieldName,
	FieldEnabled,
	FieldTarget,
	FieldSecretEnvelope,
	FieldAllowPrivate,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultTarget holds the default value on creation for the "target" field.
	DefaultTarget string
	// DefaultSecretEnvelope holds the default value on creation for the "secret_envelope" field.
	DefaultSecretEnvelope string
	// DefaultAllowPrivate holds the default value on creation for the "allow_private" field.
	DefaultAllowPrivate bool
)

// OrderOption defines the ordering options for the NotificationChannel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChannelType orders the results by the channel_type field.
func ByChannelType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelType, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// BySecretEnvelope orders the results by the secret_envelope field.
func BySecretEnvelope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretEnvelope, opts...).ToFunc()
}

// ByAllowPrivate orders the results by the allow_private field.
func ByAllowPrivate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowPrivate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
