// Code generated by ent, DO NOT EDIT.

package repository

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the repository type in the database.
	Label = "repository"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldSyncStatus holds the string denoting the sync_status field in the database.
	FieldSyncStatus = "sync_status"
	// FieldGithubRepoID holds the string denoting the github_repo_id field in the database.
	FieldGithubRepoID = "github_repo_id"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFullName holds the string denoting the full_name field in the database.
	FieldFullName = "full_name"
	// FieldInstallationID holds the string denoting the installation_id field in the database.
	FieldInstallationID = "installation_id"
	// FieldIsArchived holds the string denoting the is_archived field in the database.
	FieldIsArchived = "is_archived"
	// FieldIsPrivate holds the string denoting the is_private field in the database.
	FieldIsPrivate = "is_private"
	// FieldHTMLURL holds the string denoting the html_url field in the database.
	FieldHTMLURL = "html_url"
	// FieldDefaultBranch holds the string denoting the default_branch field in the database.
	FieldDefaultBranch = "default_branch"
	// FieldBaselineStartedAt holds the string denoting the baseline_started_at field in the database.
	FieldBaselineStartedAt = "baseline_started_at"
	// FieldBaselineFinishedAt holds the string denoting the baseline_finished_at field in the database.
	FieldBaselineFinishedAt = "baseline_finished_at"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// FieldLastSyncErrorCode holds the string denoting the last_sync_error_code field in the database.
	FieldLastSyncErrorCode = "last_sync_error_code"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the repository in the database.
	Table = "repositories"
)

// Columns holds all SQL columns for repository fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldSyncStatus,
	FieldGithubRepoID,
	FieldOwner,
	FieldName,
	FieldFullName,
	FieldInstallationID,
	FieldIsArchived,
	FieldIsPrivate,
	FieldHTMLURL,
	FieldDefaultBranch,
	FieldBaselineStartedAt,
	FieldBaselineFinishedAt,
	FieldLastSyncedAt,
	FieldLastSyncErrorCode,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSyncStatus holds the default value on creation for the "sync_status" field.
	DefaultSyncStatus string
	// DefaultIsArchived holds the default value on creation for the "is_archived" field.
	DefaultIsArchived bool
	// DefaultIsPrivate holds the default value on creation for the "is_private" field.
	DefaultIsPrivate bool
	// DefaultHTMLURL holds the default value on creation for the "html_url" field.
	DefaultHTMLURL string
	// DefaultDefaultBranch holds the default value on creation for the "default_branch" field.
	DefaultDefaultBranch string
	// DefaultLastSyncErrorCode holds the default value on creation for the "last_sync_error_code" field.
	DefaultLastSyncErrorCode string
)

// OrderOption defines the ordering options for the Repository queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// BySyncStatus orders the results by the sync_status field.
func BySyncStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncStatus, opts...).ToFunc()
}

// ByGithubRepoID orders the results by the github_repo_id field.
func ByGithubRepoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubRepoID, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByFullName orders the results by the full_name field.
func ByFullName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullName, opts...).ToFunc()
}

// ByInstallationID orders the results by the installation_id field.
func ByInstallationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallationID, opts...).ToFunc()
}

// ByIsArchived orders the results by the is_archived field.
func ByIsArchived(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsArchived, opts...).ToFunc()
}

// ByIsPrivate orders the results by the is_private field.
func ByIsPrivate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPrivate, opts...).ToFunc()
}

// ByHTMLURL orders the results by the html_url field.
func ByHTMLURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTMLURL, opts...).ToFunc()
}

// ByDefaultBranch orders the results by the default_branch field.
func ByDefaultBranch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultBranch, opts...).ToFunc()
}

// ByBaselineStartedAt orders the results by the baseline_started_at field.
func ByBaselineStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaselineStartedAt, opts...).ToFunc()
}

// ByBaselineFinishedAt orders the results by the baseline_finished_at field.
func ByBaselineFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaselineFinishedAt, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByLastSyncErrorCode orders the results by the last_sync_error_code field.
func ByLastSyncErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncErrorCode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
