// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/adminaccount"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/adminsession"
)

// AdminAccountCreate is the builder for creating a AdminAccount entity.
type AdminAccountCreate struct {
	config
	mutation *AdminAccountMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (_c *AdminAccountCreate) SetUsername(v string) *AdminAccountCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetUsernameNormalized sets the "username_normalized" field.
func (_c *AdminAccountCreate) SetUsernameNormalized(v string) *AdminAccountCreate {
	_c.mutation.SetUsernameNormalized(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *AdminAccountCreate) SetPasswordHash(v string) *AdminAccountCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminAccountCreate) SetCreatedAt(v time.Time) *AdminAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdminAccountCreate) SetUpdatedAt(v time.Time) *AdminAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetPasswordChangedAt sets the "password_changed_at" field.
func (_c *AdminAccountCreate) SetPasswordChangedAt(v time.Time) *AdminAccountCreate {
	_c.mutation.SetPasswordChangedAt(v)
	return _c
}

// SetSingletonSlot sets the "singleton_slot" field.
func (_c *AdminAccountCreate) SetSingletonSlot(v int) *AdminAccountCreate {
	_c.mutation.SetSingletonSlot(v)
	return _c
}

// SetNillableSingletonSlot sets the "singleton_slot" field if the given value is not nil.
func (_c *AdminAccountCreate) SetNillableSingletonSlot(v *int) *AdminAccountCreate {
	if v != nil {
		_c.SetSingletonSlot(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AdminAccountCreate) SetID(v string) *AdminAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddSessionIDs adds the "sessions" edge to the AdminSession entity by IDs.
func (_c *AdminAccountCreate) AddSessionIDs(ids ...string) *AdminAccountCreate {
	_c.mutation.AddSessionIDs(ids...)
	return _c
}

// AddSessions adds the "sessions" edges to the AdminSession entity.
func (_c *AdminAccountCreate) AddSessions(v ...*AdminSession) *AdminAccountCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionIDs(ids...)
}

// Mutation returns the AdminAccountMutation object of the builder.
func (_c *AdminAccountCreate) Mutation() *AdminAccountMutation {
	return _c.mutation
}

// Save creates the AdminAccount in the database.
func (_c *AdminAccountCreate) Save(ctx context.Context) (*AdminAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminAccountCreate) SaveX(ctx context.Context) *AdminAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminAccountCreate) defaults() {
	if _, ok := _c.mutation.SingletonSlot(); !ok {
		v := adminaccount.DefaultSingletonSlot
		_c.mutation.SetSingletonSlot(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminAccountCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "AdminAccount.username"`)}
	}
	if _, ok := _c.mutation.UsernameNormalized(); !ok {
		return &ValidationError{Name: "username_normalized", err: errors.New(`ent: missing required field "AdminAccount.username_normalized"`)}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "AdminAccount.password_hash"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdminAccount.updated_at"`)}
	}
	if _, ok := _c.mutation.PasswordChangedAt(); !ok {
		return &ValidationError{Name: "password_changed_at", err: errors.New(`ent: missing required field "AdminAccount.password_changed_at"`)}
	}
	if _, ok := _c.mutation.SingletonSlot(); !ok {
		return &ValidationError{Name: "singleton_slot", err: errors.New(`ent: missing required field "AdminAccount.singleton_slot"`)}
	}
	return nil
}

func (_c *AdminAccountCreate) sqlSave(ctx context.Context) (*AdminAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AdminAccount.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminAccountCreate) createSpec() (*AdminAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminaccount.Table, sqlgraph.NewFieldSpec(adminaccount.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(adminaccount.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.UsernameNormalized(); ok {
		_spec.SetField(adminaccount.FieldUsernameNormalized, field.TypeString, value)
		_node.UsernameNormalized = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(adminaccount.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adminaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PasswordChangedAt(); ok {
		_spec.SetField(adminaccount.FieldPasswordChangedAt, field.TypeTime, value)
		_node.PasswordChangedAt = value
	}
	if value, ok := _c.mutation.SingletonSlot(); ok {
		_spec.SetField(adminaccount.FieldSingletonSlot, field.TypeInt, value)
		_node.SingletonSlot = value
	}
	if nodes := _c.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adminaccount.SessionsTable,
			Columns: []string{adminaccount.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminsession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AdminAccountCreateBulk is the builder for creating many AdminAccount entities in bulk.
type AdminAccountCreateBulk struct {
	config
	err      error
	builders []*AdminAccountCreate
}

// Save creates the AdminAccount entities in the database.
func (_c *AdminAccountCreateBulk) Save(ctx context.Context) ([]*AdminAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminAccountCreateBulk) SaveX(ctx context.Context) []*AdminAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
