// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/event"
)

// Event is the model entity for the Event schema.
type Event struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// RepositoryID holds the value of the "repository_id" field.
	RepositoryID *string `json:"repository_id,omitempty"`
	// SubjectNumber holds the value of the "subject_number" field.
	SubjectNumber *int `json:"subject_number,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity string `json:"severity,omitempty"`
	// Actor holds the value of the "actor" field.
	Actor string `json:"actor,omitempty"`
	// WorkflowRunID holds the value of the "workflow_run_id" field.
	WorkflowRunID *int64 `json:"workflow_run_id,omitempty"`
	// WorkflowConclusion holds the value of the "workflow_conclusion" field.
	WorkflowConclusion string `json:"workflow_conclusion,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// SourceUpdatedAt holds the value of the "source_updated_at" field.
	SourceUpdatedAt *time.Time `json:"source_updated_at,omitempty"`
	// HTMLURL holds the value of the "html_url" field.
	HTMLURL string `json:"html_url,omitempty"`
	// PayloadSummary holds the value of the "payload_summary" field.
	PayloadSummary map[string]interface{} `json:"payload_summary,omitempty"`
	// SuppressNotification holds the value of the "suppress_notification" field.
	SuppressNotification bool `json:"suppress_notification,omitempty"`
	// DedupeFingerprint holds the value of the "dedupe_fingerprint" field.
	DedupeFingerprint string `json:"dedupe_fingerprint,omitempty"`
	// StateHash holds the value of the "state_hash" field.
	StateHash string `json:"state_hash,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Event) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case event.FieldPayloadSummary:
			values[i] = new([]byte)
		case event.FieldSuppressNotification:
			values[i] = new(sql.NullBool)
		case event.FieldSubjectNumber, event.FieldWorkflowRunID:
			values[i] = new(sql.NullInt64)
		case event.FieldID, event.FieldSource, event.FieldKind, event.FieldAction, event.FieldRepositoryID, event.FieldTitle, event.FieldSeverity, event.FieldActor, event.FieldWorkflowConclusion, event.FieldHTMLURL, event.FieldDedupeFingerprint, event.FieldStateHash:
			values[i] = new(sql.NullString)
		case event.FieldOccurredAt, event.FieldSourceUpdatedAt, event.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Event fields.
func (_m *Event) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case event.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case event.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case event.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case event.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case event.FieldRepositoryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repository_id", values[i])
			} else if value.Valid {
				_m.RepositoryID = new(string)
				*_m.RepositoryID = value.String
			}
		case event.FieldSubjectNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subject_number", values[i])
			} else if value.Valid {
				_m.SubjectNumber = new(int)
				*_m.SubjectNumber = int(value.Int64)
			}
		case event.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case event.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = value.String
			}
		case event.FieldActor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor", values[i])
			} else if value.Valid {
				_m.Actor = value.String
			}
		case event.FieldWorkflowRunID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_run_id", values[i])
			} else if value.Valid {
				_m.WorkflowRunID = new(int64)
				*_m.WorkflowRunID = value.Int64
			}
		case event.FieldWorkflowConclusion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_conclusion", values[i])
			} else if value.Valid {
				_m.WorkflowConclusion = value.String
			}
		case event.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		case event.FieldSourceUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field source_updated_at", values[i])
			} else if value.Valid {
				_m.SourceUpdatedAt = new(time.Time)
				*_m.SourceUpdatedAt = value.Time
			}
		case event.FieldHTMLURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field html_url", values[i])
			} else if value.Valid {
				_m.HTMLURL = value.String
			}
		case event.FieldPayloadSummary:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload_summary", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PayloadSummary); err != nil {
					return fmt.Errorf("unmarshal field payload_summary: %w", err)
				}
			}
		case event.FieldSuppressNotification:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field suppress_notification", values[i])
			} else if value.Valid {
				_m.SuppressNotification = value.Bool
			}
		case event.FieldDedupeFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dedupe_fingerprint", values[i])
			} else if value.Valid {
				_m.DedupeFingerprint = value.String
			}
		case event.FieldStateHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state_hash", values[i])
			} else if value.Valid {
				_m.StateHash = value.String
			}
		case event.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Event.
// This includes values selected through modifiers, order, etc.
func (_m *Event) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Event.
// Note that you need to call Event.Unwrap() before calling this method if this Event
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Event) Update() *EventUpdateOne {
	return NewEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Event entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Event) Unwrap() *Event {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Event is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Event) String() string {
	var builder strings.Builder
	builder.WriteString("Event(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	if v := _m.RepositoryID; v != nil {
		builder.WriteString("repository_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SubjectNumber; v != nil {
		builder.WriteString("subject_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(_m.Severity)
	builder.WriteString(", ")
	builder.WriteString("actor=")
	builder.WriteString(_m.Actor)
	builder.WriteString(", ")
	if v := _m.WorkflowRunID; v != nil {
		builder.WriteString("workflow_run_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("workflow_conclusion=")
	builder.WriteString(_m.WorkflowConclusion)
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SourceUpdatedAt; v != nil {
		builder.WriteString("source_updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("html_url=")
	builder.WriteString(_m.HTMLURL)
	builder.WriteString(", ")
	builder.WriteString("payload_summary=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayloadSummary))
	builder.WriteString(", ")
	builder.WriteString("suppress_notification=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuppressNotification))
	builder.WriteString(", ")
	builder.WriteString("dedupe_fingerprint=")
	builder.WriteString(_m.DedupeFingerprint)
	builder.WriteString(", ")
	builder.WriteString("state_hash=")
	builder.WriteString(_m.StateHash)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Events is a parsable slice of Event.
type Events []*Event
