// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/adminaccount"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/adminsession"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/auditlog"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/predicate"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/systemsetting"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAdminAccount  = "AdminAccount"
	TypeAdminSession  = "AdminSession"
	TypeAuditLog      = "AuditLog"
	TypeSystemSetting = "SystemSetting"
)

// AdminAccountMutation represents an operation that mutates the AdminAccount nodes in the graph.
type AdminAccountMutation struct {
	config
	op                  Op
	typ                 string
	id                  *string
	username            *string
	username_normalized *string
	password_hash       *string
	created_at          *time.Time
	updated_at          *time.Time
	password_changed_at *time.Time
	singleton_slot      *int
	addsingleton_slot   *int
	clearedFields       map[string]struct{}
	sessions            map[string]struct{}
	removedsessions     map[string]struct{}
	clearedsessions     bool
	done                bool
	oldValue            func(context.Context) (*AdminAccount, error)
	predicates          []predicate.AdminAccount
}

var _ ent.Mutation = (*AdminAccountMutation)(nil)

// adminaccountOption allows management of the mutation configuration using functional options.
type adminaccountOption func(*AdminAccountMutation)

// newAdminAccountMutation creates new mutation for the AdminAccount entity.
func newAdminAccountMutation(c config, op Op, opts ...adminaccountOption) *AdminAccountMutation {
	m := &AdminAccountMutation{
		config:        c,
		op:            op,
		typ:           TypeAdminAccount,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAdminAccountID sets the ID field of the mutation.
func withAdminAccountID(id string) adminaccountOption {
	return func(m *AdminAccountMutation) {
		var (
			err   error
			once  sync.Once
			value *AdminAccount
		)
		m.oldValue = func(ctx context.Context) (*AdminAccount, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AdminAccount.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAdminAccount sets the old AdminAccount of the mutation.
func withAdminAccount(node *AdminAccount) adminaccountOption {
	return func(m *AdminAccountMutation) {
		m.oldValue = func(context.Context) (*AdminAccount, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AdminAccountMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AdminAccountMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of AdminAccount entities.
func (m *AdminAccountMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AdminAccountMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AdminAccountMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AdminAccount.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUsername sets the "username" field.
func (m *AdminAccountMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *AdminAccountMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the AdminAccount entity.
// If the AdminAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminAccountMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *AdminAccountMutation) ResetUsername() {
	m.username = nil
}

// SetUsernameNormalized sets the "username_normalized" field.
func (m *AdminAccountMutation) SetUsernameNormalized(s string) {
	m.username_normalized = &s
}

// UsernameNormalized returns the value of the "username_normalized" field in the mutation.
func (m *AdminAccountMutation) UsernameNormalized() (r string, exists bool) {
	v := m.username_normalized
	if v == nil {
		return
	}
	return *v, true
}

// OldUsernameNormalized returns the old "username_normalized" field's value of the AdminAccount entity.
// If the AdminAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminAccountMutation) OldUsernameNormalized(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsernameNormalized is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsernameNormalized requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsernameNormalized: %w", err)
	}
	return oldValue.UsernameNormalized, nil
}

// ResetUsernameNormalized resets all changes to the "username_normalized" field.
func (m *AdminAccountMutation) ResetUsernameNormalized() {
	m.username_normalized = nil
}

// SetPasswordHash sets the "password_hash" field.
func (m *AdminAccountMutation) SetPasswordHash(s string) {
	m.password_hash = &s
}

// PasswordHash returns the value of the "password_hash" field in the mutation.
func (m *AdminAccountMutation) PasswordHash() (r string, exists bool) {
	v := m.password_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldPasswordHash returns the old "password_hash" field's value of the AdminAccount entity.
// If the AdminAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminAccountMutation) OldPasswordHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPasswordHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPasswordHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPasswordHash: %w", err)
	}
	return oldValue.PasswordHash, nil
}

// ResetPasswordHash resets all changes to the "password_hash" field.
func (m *AdminAccountMutation) ResetPasswordHash() {
	m.password_hash = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *AdminAccountMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AdminAccountMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the AdminAccount entity.
// If the AdminAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminAccountMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AdminAccountMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *AdminAccountMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *AdminAccountMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the AdminAccount entity.
// If the AdminAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminAccountMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *AdminAccountMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetPasswordChangedAt sets the "password_changed_at" field.
func (m *AdminAccountMutation) SetPasswordChangedAt(t time.Time) {
	m.password_changed_at = &t
}

// PasswordChangedAt returns the value of the "password_changed_at" field in the mutation.
func (m *AdminAccountMutation) PasswordChangedAt() (r time.Time, exists bool) {
	v := m.password_changed_at
	if v == nil {
		return
	}
	return *v, true
}

// OldPasswordChangedAt returns the old "password_changed_at" field's value of the AdminAccount entity.
// If the AdminAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminAccountMutation) OldPasswordChangedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPasswordChangedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPasswordChangedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPasswordChangedAt: %w", err)
	}
	return oldValue.PasswordChangedAt, nil
}

// ResetPasswordChangedAt resets all changes to the "password_changed_at" field.
func (m *AdminAccountMutation) ResetPasswordChangedAt() {
	m.password_changed_at = nil
}

// SetSingletonSlot sets the "singleton_slot" field.
func (m *AdminAccountMutation) SetSingletonSlot(i int) {
	m.singleton_slot = &i
	m.addsingleton_slot = nil
}

// SingletonSlot returns the value of the "singleton_slot" field in the mutation.
func (m *AdminAccountMutation) SingletonSlot() (r int, exists bool) {
	v := m.singleton_slot
	if v == nil {
		return
	}
	return *v, true
}

// OldSingletonSlot returns the old "singleton_slot" field's value of the AdminAccount entity.
// If the AdminAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminAccountMutation) OldSingletonSlot(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSingletonSlot is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSingletonSlot requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSingletonSlot: %w", err)
	}
	return oldValue.SingletonSlot, nil
}

// AddSingletonSlot adds i to the "singleton_slot" field.
func (m *AdminAccountMutation) AddSingletonSlot(i int) {
	if m.addsingleton_slot != nil {
		*m.addsingleton_slot += i
	} else {
		m.addsingleton_slot = &i
	}
}

// AddedSingletonSlot returns the value that was added to the "singleton_slot" field in this mutation.
func (m *AdminAccountMutation) AddedSingletonSlot() (r int, exists bool) {
	v := m.addsingleton_slot
	if v == nil {
		return
	}
	return *v, true
}

// ResetSingletonSlot resets all changes to the "singleton_slot" field.
func (m *AdminAccountMutation) ResetSingletonSlot() {
	m.singleton_slot = nil
	m.addsingleton_slot = nil
}

// AddSessionIDs adds the "sessions" edge to the AdminSession entity by ids.
func (m *AdminAccountMutation) AddSessionIDs(ids ...string) {
	if m.sessions == nil {
		m.sessions = make(map[string]struct{})
	}
	for i := range ids {
		m.sessions[ids[i]] = struct{}{}
	}
}

// ClearSessions clears the "sessions" edge to the AdminSession entity.
func (m *AdminAccountMutation) ClearSessions() {
	m.clearedsessions = true
}

// SessionsCleared reports if the "sessions" edge to the AdminSession entity was cleared.
func (m *AdminAccountMutation) SessionsCleared() bool {
	return m.clearedsessions
}

// RemoveSessionIDs removes the "sessions" edge to the AdminSession entity by IDs.
func (m *AdminAccountMutation) RemoveSessionIDs(ids ...string) {
	if m.removedsessions == nil {
		m.removedsessions = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.sessions, ids[i])
		m.removedsessions[ids[i]] = struct{}{}
	}
}

// RemovedSessions returns the removed IDs of the "sessions" edge to the AdminSession entity.
func (m *AdminAccountMutation) RemovedSessionsIDs() (ids []string) {
	for id := range m.removedsessions {
		ids = append(ids, id)
	}
	return
}

// SessionsIDs returns the "sessions" edge IDs in the mutation.
func (m *AdminAccountMutation) SessionsIDs() (ids []string) {
	for id := range m.sessions {
		ids = append(ids, id)
	}
	return
}

// ResetSessions resets all changes to the "sessions" edge.
func (m *AdminAccountMutation) ResetSessions() {
	m.sessions = nil
	m.clearedsessions = false
	m.removedsessions = nil
}

// Where appends a list predicates to the AdminAccountMutation builder.
func (m *AdminAccountMutation) Where(ps ...predicate.AdminAccount) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AdminAccountMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AdminAccountMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AdminAccount, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AdminAccountMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AdminAccountMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AdminAccount).
func (m *AdminAccountMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AdminAccountMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.username != nil {
		fields = append(fields, adminaccount.FieldUsername)
	}
	if m.username_normalized != nil {
		fields = append(fields, adminaccount.FieldUsernameNormalized)
	}
	if m.password_hash != nil {
		fields = append(fields, adminaccount.FieldPasswordHash)
	}
	if m.created_at != nil {
		fields = append(fields, adminaccount.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, adminaccount.FieldUpdatedAt)
	}
	if m.password_changed_at != nil {
		fields = append(fields, adminaccount.FieldPasswordChangedAt)
	}
	if m.singleton_slot != nil {
		fields = append(fields, adminaccount.FieldSingletonSlot)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AdminAccountMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case adminaccount.FieldUsername:
		return m.Username()
	case adminaccount.FieldUsernameNormalized:
		return m.UsernameNormalized()
	case adminaccount.FieldPasswordHash:
		return m.PasswordHash()
	case adminaccount.FieldCreatedAt:
		return m.CreatedAt()
	case adminaccount.FieldUpdatedAt:
		return m.UpdatedAt()
	case adminaccount.FieldPasswordChangedAt:
		return m.PasswordChangedAt()
	case adminaccount.FieldSingletonSlot:
		return m.SingletonSlot()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AdminAccountMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case adminaccount.FieldUsername:
		return m.OldUsername(ctx)
	case adminaccount.FieldUsernameNormalized:
		return m.OldUsernameNormalized(ctx)
	case adminaccount.FieldPasswordHash:
		return m.OldPasswordHash(ctx)
	case adminaccount.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case adminaccount.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case adminaccount.FieldPasswordChangedAt:
		return m.OldPasswordChangedAt(ctx)
	case adminaccount.FieldSingletonSlot:
		return m.OldSingletonSlot(ctx)
	}
	return nil, fmt.Errorf("unknown AdminAccount field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AdminAccountMutation) SetField(name string, value ent.Value) error {
	switch name {
	case adminaccount.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case adminaccount.FieldUsernameNormalized:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsernameNormalized(v)
		return nil
	case adminaccount.FieldPasswordHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPasswordHash(v)
		return nil
	case adminaccount.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case adminaccount.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case adminaccount.FieldPasswordChangedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPasswordChangedAt(v)
		return nil
	case adminaccount.FieldSingletonSlot:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSingletonSlot(v)
		return nil
	}
	return fmt.Errorf("unknown AdminAccount field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AdminAccountMutation) AddedFields() []string {
	var fields []string
	if m.addsingleton_slot != nil {
		fields = append(fields, adminaccount.FieldSingletonSlot)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AdminAccountMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case adminaccount.FieldSingletonSlot:
		return m.AddedSingletonSlot()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AdminAccountMutation) AddField(name string, value ent.Value) error {
	switch name {
	case adminaccount.FieldSingletonSlot:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSingletonSlot(v)
		return nil
	}
	return fmt.Errorf("unknown AdminAccount numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AdminAccountMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AdminAccountMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AdminAccountMutation) ClearField(name string) error {
	return fmt.Errorf("unknown AdminAccount nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AdminAccountMutation) ResetField(name string) error {
	switch name {
	case adminaccount.FieldUsername:
		m.ResetUsername()
		return nil
	case adminaccount.FieldUsernameNormalized:
		m.ResetUsernameNormalized()
		return nil
	case adminaccount.FieldPasswordHash:
		m.ResetPasswordHash()
		return nil
	case adminaccount.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case adminaccount.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case adminaccount.FieldPasswordChangedAt:
		m.ResetPasswordChangedAt()
		return nil
	case adminaccount.FieldSingletonSlot:
		m.ResetSingletonSlot()
		return nil
	}
	return fmt.Errorf("unknown AdminAccount field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AdminAccountMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.sessions != nil {
		edges = append(edges, adminaccount.EdgeSessions)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AdminAccountMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case adminaccount.EdgeSessions:
		ids := make([]ent.Value, 0, len(m.sessions))
		for id := range m.sessions {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AdminAccountMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedsessions != nil {
		edges = append(edges, adminaccount.EdgeSessions)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AdminAccountMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case adminaccount.EdgeSessions:
		ids := make([]ent.Value, 0, len(m.removedsessions))
		for id := range m.removedsessions {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AdminAccountMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedsessions {
		edges = append(edges, adminaccount.EdgeSessions)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AdminAccountMutation) EdgeCleared(name string) bool {
	switch name {
	case adminaccount.EdgeSessions:
		return m.clearedsessions
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AdminAccountMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown AdminAccount unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AdminAccountMutation) ResetEdge(name string) error {
	switch name {
	case adminaccount.EdgeSessions:
		m.ResetSessions()
		return nil
	}
	return fmt.Errorf("unknown AdminAccount edge %s", name)
}

// AdminSessionMutation represents an operation that mutates the AdminSession nodes in the graph.
type AdminSessionMutation struct {
	config
	op            Op
	typ           string
	id            *string
	token_hash    *string
	csrf_hash     *string
	created_at    *time.Time
	expires_at    *time.Time
	last_seen_at  *time.Time
	ip_address    *string
	user_agent    *string
	clearedFields map[string]struct{}
	admin         *string
	clearedadmin  bool
	done          bool
	oldValue      func(context.Context) (*AdminSession, error)
	predicates    []predicate.AdminSession
}

var _ ent.Mutation = (*AdminSessionMutation)(nil)

// adminsessionOption allows management of the mutation configuration using functional options.
type adminsessionOption func(*AdminSessionMutation)

// newAdminSessionMutation creates new mutation for the AdminSession entity.
func newAdminSessionMutation(c config, op Op, opts ...adminsessionOption) *AdminSessionMutation {
	m := &AdminSessionMutation{
		config:        c,
		op:            op,
		typ:           TypeAdminSession,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAdminSessionID sets the ID field of the mutation.
func withAdminSessionID(id string) adminsessionOption {
	return func(m *AdminSessionMutation) {
		var (
			err   error
			once  sync.Once
			value *AdminSession
		)
		m.oldValue = func(ctx context.Context) (*AdminSession, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AdminSession.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAdminSession sets the old AdminSession of the mutation.
func withAdminSession(node *AdminSession) adminsessionOption {
	return func(m *AdminSessionMutation) {
		m.oldValue = func(context.Context) (*AdminSession, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AdminSessionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AdminSessionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of AdminSession entities.
func (m *AdminSessionMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AdminSessionMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AdminSessionMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AdminSession.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAdminID sets the "admin_id" field.
func (m *AdminSessionMutation) SetAdminID(s string) {
	m.admin = &s
}

// AdminID returns the value of the "admin_id" field in the mutation.
func (m *AdminSessionMutation) AdminID() (r string, exists bool) {
	v := m.admin
	if v == nil {
		return
	}
	return *v, true
}

// OldAdminID returns the old "admin_id" field's value of the AdminSession entity.
// If the AdminSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminSessionMutation) OldAdminID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAdminID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAdminID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAdminID: %w", err)
	}
	return oldValue.AdminID, nil
}

// ResetAdminID resets all changes to the "admin_id" field.
func (m *AdminSessionMutation) ResetAdminID() {
	m.admin = nil
}

// SetTokenHash sets the "token_hash" field.
func (m *AdminSessionMutation) SetTokenHash(s string) {
	m.token_hash = &s
}

// TokenHash returns the value of the "token_hash" field in the mutation.
func (m *AdminSessionMutation) TokenHash() (r string, exists bool) {
	v := m.token_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldTokenHash returns the old "token_hash" field's value of the AdminSession entity.
// If the AdminSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminSessionMutation) OldTokenHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTokenHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTokenHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTokenHash: %w", err)
	}
	return oldValue.TokenHash, nil
}

// ResetTokenHash resets all changes to the "token_hash" field.
func (m *AdminSessionMutation) ResetTokenHash() {
	m.token_hash = nil
}

// SetCsrfHash sets the "csrf_hash" field.
func (m *AdminSessionMutation) SetCsrfHash(s string) {
	m.csrf_hash = &s
}

// CsrfHash returns the value of the "csrf_hash" field in the mutation.
func (m *AdminSessionMutation) CsrfHash() (r string, exists bool) {
	v := m.csrf_hash
	if v == nil {
		return
	}
	return *v, true
}

// OldCsrfHash returns the old "csrf_hash" field's value of the AdminSession entity.
// If the AdminSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminSessionMutation) OldCsrfHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCsrfHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCsrfHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCsrfHash: %w", err)
	}
	return oldValue.CsrfHash, nil
}

// ResetCsrfHash resets all changes to the "csrf_hash" field.
func (m *AdminSessionMutation) ResetCsrfHash() {
	m.csrf_hash = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *AdminSessionMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AdminSessionMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the AdminSession entity.
// If the AdminSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminSessionMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AdminSessionMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetExpiresAt sets the "expires_at" field.
func (m *AdminSessionMutation) SetExpiresAt(t time.Time) {
	m.expires_at = &t
}

// ExpiresAt returns the value of the "expires_at" field in the mutation.
func (m *AdminSessionMutation) ExpiresAt() (r time.Time, exists bool) {
	v := m.expires_at
	if v == nil {
		return
	}
	return *v, true
}

// OldExpiresAt returns the old "expires_at" field's value of the AdminSession entity.
// If the AdminSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminSessionMutation) OldExpiresAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpiresAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpiresAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpiresAt: %w", err)
	}
	return oldValue.ExpiresAt, nil
}

// ResetExpiresAt resets all changes to the "expires_at" field.
func (m *AdminSessionMutation) ResetExpiresAt() {
	m.expires_at = nil
}

// SetLastSeenAt sets the "last_seen_at" field.
func (m *AdminSessionMutation) SetLastSeenAt(t time.Time) {
	m.last_seen_at = &t
}

// LastSeenAt returns the value of the "last_seen_at" field in the mutation.
func (m *AdminSessionMutation) LastSeenAt() (r time.Time, exists bool) {
	v := m.last_seen_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastSeenAt returns the old "last_seen_at" field's value of the AdminSession entity.
// If the AdminSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminSessionMutation) OldLastSeenAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastSeenAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastSeenAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastSeenAt: %w", err)
	}
	return oldValue.LastSeenAt, nil
}

// ResetLastSeenAt resets all changes to the "last_seen_at" field.
func (m *AdminSessionMutation) ResetLastSeenAt() {
	m.last_seen_at = nil
}

// SetIPAddress sets the "ip_address" field.
func (m *AdminSessionMutation) SetIPAddress(s string) {
	m.ip_address = &s
}

// IPAddress returns the value of the "ip_address" field in the mutation.
func (m *AdminSessionMutation) IPAddress() (r string, exists bool) {
	v := m.ip_address
	if v == nil {
		return
	}
	return *v, true
}

// OldIPAddress returns the old "ip_address" field's value of the AdminSession entity.
// If the AdminSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminSessionMutation) OldIPAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIPAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIPAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIPAddress: %w", err)
	}
	return oldValue.IPAddress, nil
}

// ResetIPAddress resets all changes to the "ip_address" field.
func (m *AdminSessionMutation) ResetIPAddress() {
	m.ip_address = nil
}

// SetUserAgent sets the "user_agent" field.
func (m *AdminSessionMutation) SetUserAgent(s string) {
	m.user_agent = &s
}

// UserAgent returns the value of the "user_agent" field in the mutation.
func (m *AdminSessionMutation) UserAgent() (r string, exists bool) {
	v := m.user_agent
	if v == nil {
		return
	}
	return *v, true
}

// OldUserAgent returns the old "user_agent" field's value of the AdminSession entity.
// If the AdminSession object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AdminSessionMutation) OldUserAgent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserAgent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserAgent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserAgent: %w", err)
	}
	return oldValue.UserAgent, nil
}

// ResetUserAgent resets all changes to the "user_agent" field.
func (m *AdminSessionMutation) ResetUserAgent() {
	m.user_agent = nil
}

// ClearAdmin clears the "admin" edge to the AdminAccount entity.
func (m *AdminSessionMutation) ClearAdmin() {
	m.clearedadmin = true
	m.clearedFields[adminsession.FieldAdminID] = struct{}{}
}

// AdminCleared reports if the "admin" edge to the AdminAccount entity was cleared.
func (m *AdminSessionMutation) AdminCleared() bool {
	return m.clearedadmin
}

// AdminIDs returns the "admin" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// AdminID instead. It exists only for internal usage by the builders.
func (m *AdminSessionMutation) AdminIDs() (ids []string) {
	if id := m.admin; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAdmin resets all changes to the "admin" edge.
func (m *AdminSessionMutation) ResetAdmin() {
	m.admin = nil
	m.clearedadmin = false
}

// Where appends a list predicates to the AdminSessionMutation builder.
func (m *AdminSessionMutation) Where(ps ...predicate.AdminSession) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AdminSessionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AdminSessionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AdminSession, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AdminSessionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AdminSessionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AdminSession).
func (m *AdminSessionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AdminSessionMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.admin != nil {
		fields = append(fields, adminsession.FieldAdminID)
	}
	if m.token_hash != nil {
		fields = append(fields, adminsession.FieldTokenHash)
	}
	if m.csrf_hash != nil {
		fields = append(fields, adminsession.FieldCsrfHash)
	}
	if m.created_at != nil {
		fields = append(fields, adminsession.FieldCreatedAt)
	}
	if m.expires_at != nil {
		fields = append(fields, adminsession.FieldExpiresAt)
	}
	if m.last_seen_at != nil {
		fields = append(fields, adminsession.FieldLastSeenAt)
	}
	if m.ip_address != nil {
		fields = append(fields, adminsession.FieldIPAddress)
	}
	if m.user_agent != nil {
		fields = append(fields, adminsession.FieldUserAgent)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AdminSessionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case adminsession.FieldAdminID:
		return m.AdminID()
	case adminsession.FieldTokenHash:
		return m.TokenHash()
	case adminsession.FieldCsrfHash:
		return m.CsrfHash()
	case adminsession.FieldCreatedAt:
		return m.CreatedAt()
	case adminsession.FieldExpiresAt:
		return m.ExpiresAt()
	case adminsession.FieldLastSeenAt:
		return m.LastSeenAt()
	case adminsession.FieldIPAddress:
		return m.IPAddress()
	case adminsession.FieldUserAgent:
		return m.UserAgent()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AdminSessionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case adminsession.FieldAdminID:
		return m.OldAdminID(ctx)
	case adminsession.FieldTokenHash:
		return m.OldTokenHash(ctx)
	case adminsession.FieldCsrfHash:
		return m.OldCsrfHash(ctx)
	case adminsession.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case adminsession.FieldExpiresAt:
		return m.OldExpiresAt(ctx)
	case adminsession.FieldLastSeenAt:
		return m.OldLastSeenAt(ctx)
	case adminsession.FieldIPAddress:
		return m.OldIPAddress(ctx)
	case adminsession.FieldUserAgent:
		return m.OldUserAgent(ctx)
	}
	return nil, fmt.Errorf("unknown AdminSession field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AdminSessionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case adminsession.FieldAdminID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAdminID(v)
		return nil
	case adminsession.FieldTokenHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTokenHash(v)
		return nil
	case adminsession.FieldCsrfHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCsrfHash(v)
		return nil
	case adminsession.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case adminsession.FieldExpiresAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpiresAt(v)
		return nil
	case adminsession.FieldLastSeenAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastSeenAt(v)
		return nil
	case adminsession.FieldIPAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIPAddress(v)
		return nil
	case adminsession.FieldUserAgent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserAgent(v)
		return nil
	}
	return fmt.Errorf("unknown AdminSession field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AdminSessionMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AdminSessionMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AdminSessionMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown AdminSession numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AdminSessionMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AdminSessionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AdminSessionMutation) ClearField(name string) error {
	return fmt.Errorf("unknown AdminSession nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AdminSessionMutation) ResetField(name string) error {
	switch name {
	case adminsession.FieldAdminID:
		m.ResetAdminID()
		return nil
	case adminsession.FieldTokenHash:
		m.ResetTokenHash()
		return nil
	case adminsession.FieldCsrfHash:
		m.ResetCsrfHash()
		return nil
	case adminsession.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case adminsession.FieldExpiresAt:
		m.ResetExpiresAt()
		return nil
	case adminsession.FieldLastSeenAt:
		m.ResetLastSeenAt()
		return nil
	case adminsession.FieldIPAddress:
		m.ResetIPAddress()
		return nil
	case adminsession.FieldUserAgent:
		m.ResetUserAgent()
		return nil
	}
	return fmt.Errorf("unknown AdminSession field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AdminSessionMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.admin != nil {
		edges = append(edges, adminsession.EdgeAdmin)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AdminSessionMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case adminsession.EdgeAdmin:
		if id := m.admin; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AdminSessionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AdminSessionMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AdminSessionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedadmin {
		edges = append(edges, adminsession.EdgeAdmin)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AdminSessionMutation) EdgeCleared(name string) bool {
	switch name {
	case adminsession.EdgeAdmin:
		return m.clearedadmin
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AdminSessionMutation) ClearEdge(name string) error {
	switch name {
	case adminsession.EdgeAdmin:
		m.ClearAdmin()
		return nil
	}
	return fmt.Errorf("unknown AdminSession unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AdminSessionMutation) ResetEdge(name string) error {
	switch name {
	case adminsession.EdgeAdmin:
		m.ResetAdmin()
		return nil
	}
	return fmt.Errorf("unknown AdminSession edge %s", name)
}

// AuditLogMutation represents an operation that mutates the AuditLog nodes in the graph.
type AuditLogMutation struct {
	config
	op                  Op
	typ                 string
	id                  *string
	action              *string
	actor_type          *string
	actor_id            *string
	target_type         *string
	target_id           *string
	metadata_json       *json.RawMessage
	appendmetadata_json json.RawMessage
	ip_address          *string
	created_at          *time.Time
	clearedFields       map[string]struct{}
	done                bool
	oldValue            func(context.Context) (*AuditLog, error)
	predicates          []predicate.AuditLog
}

var _ ent.Mutation = (*AuditLogMutation)(nil)

// auditlogOption allows management of the mutation configuration using functional options.
type auditlogOption func(*AuditLogMutation)

// newAuditLogMutation creates new mutation for the AuditLog entity.
func newAuditLogMutation(c config, op Op, opts ...auditlogOption) *AuditLogMutation {
	m := &AuditLogMutation{
		config:        c,
		op:            op,
		typ:           TypeAuditLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAuditLogID sets the ID field of the mutation.
func withAuditLogID(id string) auditlogOption {
	return func(m *AuditLogMutation) {
		var (
			err   error
			once  sync.Once
			value *AuditLog
		)
		m.oldValue = func(ctx context.Context) (*AuditLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AuditLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAuditLog sets the old AuditLog of the mutation.
func withAuditLog(node *AuditLog) auditlogOption {
	return func(m *AuditLogMutation) {
		m.oldValue = func(context.Context) (*AuditLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AuditLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AuditLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of AuditLog entities.
func (m *AuditLogMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AuditLogMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AuditLogMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AuditLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAction sets the "action" field.
func (m *AuditLogMutation) SetAction(s string) {
	m.action = &s
}

// Action returns the value of the "action" field in the mutation.
func (m *AuditLogMutation) Action() (r string, exists bool) {
	v := m.action
	if v == nil {
		return
	}
	return *v, true
}

// OldAction returns the old "action" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldAction(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAction is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAction requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAction: %w", err)
	}
	return oldValue.Action, nil
}

// ResetAction resets all changes to the "action" field.
func (m *AuditLogMutation) ResetAction() {
	m.action = nil
}

// SetActorType sets the "actor_type" field.
func (m *AuditLogMutation) SetActorType(s string) {
	m.actor_type = &s
}

// ActorType returns the value of the "actor_type" field in the mutation.
func (m *AuditLogMutation) ActorType() (r string, exists bool) {
	v := m.actor_type
	if v == nil {
		return
	}
	return *v, true
}

// OldActorType returns the old "actor_type" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldActorType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActorType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActorType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActorType: %w", err)
	}
	return oldValue.ActorType, nil
}

// ResetActorType resets all changes to the "actor_type" field.
func (m *AuditLogMutation) ResetActorType() {
	m.actor_type = nil
}

// SetActorID sets the "actor_id" field.
func (m *AuditLogMutation) SetActorID(s string) {
	m.actor_id = &s
}

// ActorID returns the value of the "actor_id" field in the mutation.
func (m *AuditLogMutation) ActorID() (r string, exists bool) {
	v := m.actor_id
	if v == nil {
		return
	}
	return *v, true
}

// OldActorID returns the old "actor_id" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldActorID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldActorID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldActorID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldActorID: %w", err)
	}
	return oldValue.ActorID, nil
}

// ResetActorID resets all changes to the "actor_id" field.
func (m *AuditLogMutation) ResetActorID() {
	m.actor_id = nil
}

// SetTargetType sets the "target_type" field.
func (m *AuditLogMutation) SetTargetType(s string) {
	m.target_type = &s
}

// TargetType returns the value of the "target_type" field in the mutation.
func (m *AuditLogMutation) TargetType() (r string, exists bool) {
	v := m.target_type
	if v == nil {
		return
	}
	return *v, true
}

// OldTargetType returns the old "target_type" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldTargetType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTargetType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTargetType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTargetType: %w", err)
	}
	return oldValue.TargetType, nil
}

// ResetTargetType resets all changes to the "target_type" field.
func (m *AuditLogMutation) ResetTargetType() {
	m.target_type = nil
}

// SetTargetID sets the "target_id" field.
func (m *AuditLogMutation) SetTargetID(s string) {
	m.target_id = &s
}

// TargetID returns the value of the "target_id" field in the mutation.
func (m *AuditLogMutation) TargetID() (r string, exists bool) {
	v := m.target_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTargetID returns the old "target_id" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldTargetID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTargetID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTargetID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTargetID: %w", err)
	}
	return oldValue.TargetID, nil
}

// ResetTargetID resets all changes to the "target_id" field.
func (m *AuditLogMutation) ResetTargetID() {
	m.target_id = nil
}

// SetMetadataJSON sets the "metadata_json" field.
func (m *AuditLogMutation) SetMetadataJSON(jm json.RawMessage) {
	m.metadata_json = &jm
	m.appendmetadata_json = nil
}

// MetadataJSON returns the value of the "metadata_json" field in the mutation.
func (m *AuditLogMutation) MetadataJSON() (r json.RawMessage, exists bool) {
	v := m.metadata_json
	if v == nil {
		return
	}
	return *v, true
}

// OldMetadataJSON returns the old "metadata_json" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldMetadataJSON(ctx context.Context) (v json.RawMessage, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMetadataJSON is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMetadataJSON requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMetadataJSON: %w", err)
	}
	return oldValue.MetadataJSON, nil
}

// AppendMetadataJSON adds jm to the "metadata_json" field.
func (m *AuditLogMutation) AppendMetadataJSON(jm json.RawMessage) {
	m.appendmetadata_json = append(m.appendmetadata_json, jm...)
}

// AppendedMetadataJSON returns the list of values that were appended to the "metadata_json" field in this mutation.
func (m *AuditLogMutation) AppendedMetadataJSON() (json.RawMessage, bool) {
	if len(m.appendmetadata_json) == 0 {
		return nil, false
	}
	return m.appendmetadata_json, true
}

// ResetMetadataJSON resets all changes to the "metadata_json" field.
func (m *AuditLogMutation) ResetMetadataJSON() {
	m.metadata_json = nil
	m.appendmetadata_json = nil
}

// SetIPAddress sets the "ip_address" field.
func (m *AuditLogMutation) SetIPAddress(s string) {
	m.ip_address = &s
}

// IPAddress returns the value of the "ip_address" field in the mutation.
func (m *AuditLogMutation) IPAddress() (r string, exists bool) {
	v := m.ip_address
	if v == nil {
		return
	}
	return *v, true
}

// OldIPAddress returns the old "ip_address" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldIPAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIPAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIPAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIPAddress: %w", err)
	}
	return oldValue.IPAddress, nil
}

// ResetIPAddress resets all changes to the "ip_address" field.
func (m *AuditLogMutation) ResetIPAddress() {
	m.ip_address = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *AuditLogMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AuditLogMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the AuditLog entity.
// If the AuditLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AuditLogMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AuditLogMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the AuditLogMutation builder.
func (m *AuditLogMutation) Where(ps ...predicate.AuditLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AuditLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AuditLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AuditLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AuditLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AuditLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AuditLog).
func (m *AuditLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AuditLogMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.action != nil {
		fields = append(fields, auditlog.FieldAction)
	}
	if m.actor_type != nil {
		fields = append(fields, auditlog.FieldActorType)
	}
	if m.actor_id != nil {
		fields = append(fields, auditlog.FieldActorID)
	}
	if m.target_type != nil {
		fields = append(fields, auditlog.FieldTargetType)
	}
	if m.target_id != nil {
		fields = append(fields, auditlog.FieldTargetID)
	}
	if m.metadata_json != nil {
		fields = append(fields, auditlog.FieldMetadataJSON)
	}
	if m.ip_address != nil {
		fields = append(fields, auditlog.FieldIPAddress)
	}
	if m.created_at != nil {
		fields = append(fields, auditlog.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AuditLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case auditlog.FieldAction:
		return m.Action()
	case auditlog.FieldActorType:
		return m.ActorType()
	case auditlog.FieldActorID:
		return m.ActorID()
	case auditlog.FieldTargetType:
		return m.TargetType()
	case auditlog.FieldTargetID:
		return m.TargetID()
	case auditlog.FieldMetadataJSON:
		return m.MetadataJSON()
	case auditlog.FieldIPAddress:
		return m.IPAddress()
	case auditlog.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AuditLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case auditlog.FieldAction:
		return m.OldAction(ctx)
	case auditlog.FieldActorType:
		return m.OldActorType(ctx)
	case auditlog.FieldActorID:
		return m.OldActorID(ctx)
	case auditlog.FieldTargetType:
		return m.OldTargetType(ctx)
	case auditlog.FieldTargetID:
		return m.OldTargetID(ctx)
	case auditlog.FieldMetadataJSON:
		return m.OldMetadataJSON(ctx)
	case auditlog.FieldIPAddress:
		return m.OldIPAddress(ctx)
	case auditlog.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown AuditLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuditLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case auditlog.FieldAction:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAction(v)
		return nil
	case auditlog.FieldActorType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActorType(v)
		return nil
	case auditlog.FieldActorID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActorID(v)
		return nil
	case auditlog.FieldTargetType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTargetType(v)
		return nil
	case auditlog.FieldTargetID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTargetID(v)
		return nil
	case auditlog.FieldMetadataJSON:
		v, ok := value.(json.RawMessage)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMetadataJSON(v)
		return nil
	case auditlog.FieldIPAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIPAddress(v)
		return nil
	case auditlog.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown AuditLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AuditLogMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AuditLogMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AuditLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown AuditLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AuditLogMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AuditLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AuditLogMutation) ClearField(name string) error {
	return fmt.Errorf("unknown AuditLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AuditLogMutation) ResetField(name string) error {
	switch name {
	case auditlog.FieldAction:
		m.ResetAction()
		return nil
	case auditlog.FieldActorType:
		m.ResetActorType()
		return nil
	case auditlog.FieldActorID:
		m.ResetActorID()
		return nil
	case auditlog.FieldTargetType:
		m.ResetTargetType()
		return nil
	case auditlog.FieldTargetID:
		m.ResetTargetID()
		return nil
	case auditlog.FieldMetadataJSON:
		m.ResetMetadataJSON()
		return nil
	case auditlog.FieldIPAddress:
		m.ResetIPAddress()
		return nil
	case auditlog.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown AuditLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AuditLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AuditLogMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AuditLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AuditLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AuditLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AuditLogMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AuditLogMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AuditLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AuditLogMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AuditLog edge %s", name)
}

// SystemSettingMutation represents an operation that mutates the SystemSetting nodes in the graph.
type SystemSettingMutation struct {
	config
	op               Op
	typ              string
	id               *string
	key              *string
	value_json       *json.RawMessage
	appendvalue_json json.RawMessage
	updated_at       *time.Time
	updated_by       *string
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*SystemSetting, error)
	predicates       []predicate.SystemSetting
}

var _ ent.Mutation = (*SystemSettingMutation)(nil)

// systemsettingOption allows management of the mutation configuration using functional options.
type systemsettingOption func(*SystemSettingMutation)

// newSystemSettingMutation creates new mutation for the SystemSetting entity.
func newSystemSettingMutation(c config, op Op, opts ...systemsettingOption) *SystemSettingMutation {
	m := &SystemSettingMutation{
		config:        c,
		op:            op,
		typ:           TypeSystemSetting,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSystemSettingID sets the ID field of the mutation.
func withSystemSettingID(id string) systemsettingOption {
	return func(m *SystemSettingMutation) {
		var (
			err   error
			once  sync.Once
			value *SystemSetting
		)
		m.oldValue = func(ctx context.Context) (*SystemSetting, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SystemSetting.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSystemSetting sets the old SystemSetting of the mutation.
func withSystemSetting(node *SystemSetting) systemsettingOption {
	return func(m *SystemSettingMutation) {
		m.oldValue = func(context.Context) (*SystemSetting, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SystemSettingMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SystemSettingMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of SystemSetting entities.
func (m *SystemSettingMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SystemSettingMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SystemSettingMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SystemSetting.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetKey sets the "key" field.
func (m *SystemSettingMutation) SetKey(s string) {
	m.key = &s
}

// Key returns the value of the "key" field in the mutation.
func (m *SystemSettingMutation) Key() (r string, exists bool) {
	v := m.key
	if v == nil {
		return
	}
	return *v, true
}

// OldKey returns the old "key" field's value of the SystemSetting entity.
// If the SystemSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SystemSettingMutation) OldKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKey: %w", err)
	}
	return oldValue.Key, nil
}

// ResetKey resets all changes to the "key" field.
func (m *SystemSettingMutation) ResetKey() {
	m.key = nil
}

// SetValueJSON sets the "value_json" field.
func (m *SystemSettingMutation) SetValueJSON(jm json.RawMessage) {
	m.value_json = &jm
	m.appendvalue_json = nil
}

// ValueJSON returns the value of the "value_json" field in the mutation.
func (m *SystemSettingMutation) ValueJSON() (r json.RawMessage, exists bool) {
	v := m.value_json
	if v == nil {
		return
	}
	return *v, true
}

// OldValueJSON returns the old "value_json" field's value of the SystemSetting entity.
// If the SystemSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SystemSettingMutation) OldValueJSON(ctx context.Context) (v json.RawMessage, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValueJSON is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValueJSON requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValueJSON: %w", err)
	}
	return oldValue.ValueJSON, nil
}

// AppendValueJSON adds jm to the "value_json" field.
func (m *SystemSettingMutation) AppendValueJSON(jm json.RawMessage) {
	m.appendvalue_json = append(m.appendvalue_json, jm...)
}

// AppendedValueJSON returns the list of values that were appended to the "value_json" field in this mutation.
func (m *SystemSettingMutation) AppendedValueJSON() (json.RawMessage, bool) {
	if len(m.appendvalue_json) == 0 {
		return nil, false
	}
	return m.appendvalue_json, true
}

// ResetValueJSON resets all changes to the "value_json" field.
func (m *SystemSettingMutation) ResetValueJSON() {
	m.value_json = nil
	m.appendvalue_json = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *SystemSettingMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *SystemSettingMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the SystemSetting entity.
// If the SystemSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SystemSettingMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *SystemSettingMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetUpdatedBy sets the "updated_by" field.
func (m *SystemSettingMutation) SetUpdatedBy(s string) {
	m.updated_by = &s
}

// UpdatedBy returns the value of the "updated_by" field in the mutation.
func (m *SystemSettingMutation) UpdatedBy() (r string, exists bool) {
	v := m.updated_by
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedBy returns the old "updated_by" field's value of the SystemSetting entity.
// If the SystemSetting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SystemSettingMutation) OldUpdatedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedBy: %w", err)
	}
	return oldValue.UpdatedBy, nil
}

// ResetUpdatedBy resets all changes to the "updated_by" field.
func (m *SystemSettingMutation) ResetUpdatedBy() {
	m.updated_by = nil
}

// Where appends a list predicates to the SystemSettingMutation builder.
func (m *SystemSettingMutation) Where(ps ...predicate.SystemSetting) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SystemSettingMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SystemSettingMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SystemSetting, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SystemSettingMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SystemSettingMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SystemSetting).
func (m *SystemSettingMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SystemSettingMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.key != nil {
		fields = append(fields, systemsetting.FieldKey)
	}
	if m.value_json != nil {
		fields = append(fields, systemsetting.FieldValueJSON)
	}
	if m.updated_at != nil {
		fields = append(fields, systemsetting.FieldUpdatedAt)
	}
	if m.updated_by != nil {
		fields = append(fields, systemsetting.FieldUpdatedBy)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SystemSettingMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case systemsetting.FieldKey:
		return m.Key()
	case systemsetting.FieldValueJSON:
		return m.ValueJSON()
	case systemsetting.FieldUpdatedAt:
		return m.UpdatedAt()
	case systemsetting.FieldUpdatedBy:
		return m.UpdatedBy()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SystemSettingMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case systemsetting.FieldKey:
		return m.OldKey(ctx)
	case systemsetting.FieldValueJSON:
		return m.OldValueJSON(ctx)
	case systemsetting.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case systemsetting.FieldUpdatedBy:
		return m.OldUpdatedBy(ctx)
	}
	return nil, fmt.Errorf("unknown SystemSetting field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SystemSettingMutation) SetField(name string, value ent.Value) error {
	switch name {
	case systemsetting.FieldKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKey(v)
		return nil
	case systemsetting.FieldValueJSON:
		v, ok := value.(json.RawMessage)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValueJSON(v)
		return nil
	case systemsetting.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case systemsetting.FieldUpdatedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedBy(v)
		return nil
	}
	return fmt.Errorf("unknown SystemSetting field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SystemSettingMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SystemSettingMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SystemSettingMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown SystemSetting numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SystemSettingMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SystemSettingMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SystemSettingMutation) ClearField(name string) error {
	return fmt.Errorf("unknown SystemSetting nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SystemSettingMutation) ResetField(name string) error {
	switch name {
	case systemsetting.FieldKey:
		m.ResetKey()
		return nil
	case systemsetting.FieldValueJSON:
		m.ResetValueJSON()
		return nil
	case systemsetting.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case systemsetting.FieldUpdatedBy:
		m.ResetUpdatedBy()
		return nil
	}
	return fmt.Errorf("unknown SystemSetting field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SystemSettingMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SystemSettingMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SystemSettingMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SystemSettingMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SystemSettingMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SystemSettingMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SystemSettingMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown SystemSetting unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SystemSettingMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown SystemSetting edge %s", name)
}
