// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/notificationchannel"
)

// NotificationChannelCreate is the builder for creating a NotificationChannel entity.
type NotificationChannelCreate struct {
	config
	mutation *NotificationChannelMutation
	hooks    []Hook
}

// SetChannelType sets the "channel_type" field.
func (_c *NotificationChannelCreate) SetChannelType(v string) *NotificationChannelCreate {
	_c.mutation.SetChannelType(v)
	return _c
}

// SetName sets the "name" field.
func (_c *NotificationChannelCreate) SetName(v string) *NotificationChannelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *NotificationChannelCreate) SetNillableName(v *string) *NotificationChannelCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *NotificationChannelCreate) SetEnabled(v bool) *NotificationChannelCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *NotificationChannelCreate) SetNillableEnabled(v *bool) *NotificationChannelCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *NotificationChannelCreate) SetTarget(v string) *NotificationChannelCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_c *NotificationChannelCreate) SetNillableTarget(v *string) *NotificationChannelCreate {
	if v != nil {
		_c.SetTarget(*v)
	}
	return _c
}

// SetSecretEnvelope sets the "secret_envelope" field.
func (_c *NotificationChannelCreate) SetSecretEnvelope(v string) *NotificationChannelCreate {
	_c.mutation.SetSecretEnvelope(v)
	return _c
}

// SetNillableSecretEnvelope sets the "secret_envelope" field if the given value is not nil.
func (_c *NotificationChannelCreate) SetNillableSecretEnvelope(v *string) *NotificationChannelCreate {
	if v != nil {
		_c.SetSecretEnvelope(*v)
	}
	return _c
}

// SetAllowPrivate sets the "allow_private" field.
func (_c *NotificationChannelCreate) SetAllowPrivate(v bool) *NotificationChannelCreate {
	_c.mutation.SetAllowPrivate(v)
	return _c
}

// SetNillableAllowPrivate sets the "allow_private" field if the given value is not nil.
func (_c *NotificationChannelCreate) SetNillableAllowPrivate(v *bool) *NotificationChannelCreate {
	if v != nil {
		_c.SetAllowPrivate(*v)
	}
	return _c
}

// SetEventKinds sets the "event_kinds" field.
func (_c *NotificationChannelCreate) SetEventKinds(v []string) *NotificationChannelCreate {
	_c.mutation.SetEventKinds(v)
	return _c
}

// SetDigestEnabled sets the "digest_enabled" field.
func (_c *NotificationChannelCreate) SetDigestEnabled(v bool) *NotificationChannelCreate {
	_c.mutation.SetDigestEnabled(v)
	return _c
}

// SetNillableDigestEnabled sets the "digest_enabled" field if the given value is not nil.
func (_c *NotificationChannelCreate) SetNillableDigestEnabled(v *bool) *NotificationChannelCreate {
	if v != nil {
		_c.SetDigestEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationChannelCreate) SetCreatedAt(v time.Time) *NotificationChannelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationChannelCreate) SetUpdatedAt(v time.Time) *NotificationChannelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationChannelCreate) SetID(v string) *NotificationChannelCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NotificationChannelMutation object of the builder.
func (_c *NotificationChannelCreate) Mutation() *NotificationChannelMutation {
	return _c.mutation
}

// Save creates the NotificationChannel in the database.
func (_c *NotificationChannelCreate) Save(ctx context.Context) (*NotificationChannel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationChannelCreate) SaveX(ctx context.Context) *NotificationChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationChannelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationChannelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationChannelCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := notificationchannel.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := notificationchannel.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Target(); !ok {
		v := notificationchannel.DefaultTarget
		_c.mutation.SetTarget(v)
	}
	if _, ok := _c.mutation.SecretEnvelope(); !ok {
		v := notificationchannel.DefaultSecretEnvelope
		_c.mutation.SetSecretEnvelope(v)
	}
	if _, ok := _c.mutation.AllowPrivate(); !ok {
		v := notificationchannel.DefaultAllowPrivate
		_c.mutation.SetAllowPrivate(v)
	}
	if _, ok := _c.mutation.DigestEnabled(); !ok {
		v := notificationchannel.DefaultDigestEnabled
		_c.mutation.SetDigestEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationChannelCreate) check() error {
	if _, ok := _c.mutation.ChannelType(); !ok {
		return &ValidationError{Name: "channel_type", err: errors.New(`ent: missing required field "NotificationChannel.channel_type"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "NotificationChannel.name"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "NotificationChannel.enabled"`)}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "NotificationChannel.target"`)}
	}
	if _, ok := _c.mutation.SecretEnvelope(); !ok {
		return &ValidationError{Name: "secret_envelope", err: errors.New(`ent: missing required field "NotificationChannel.secret_envelope"`)}
	}
	if _, ok := _c.mutation.AllowPrivate(); !ok {
		return &ValidationError{Name: "allow_private", err: errors.New(`ent: missing required field "NotificationChannel.allow_private"`)}
	}
	if _, ok := _c.mutation.DigestEnabled(); !ok {
		return &ValidationError{Name: "digest_enabled", err: errors.New(`ent: missing required field "NotificationChannel.digest_enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationChannel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationChannel.updated_at"`)}
	}
	return nil
}

func (_c *NotificationChannelCreate) sqlSave(ctx context.Context) (*NotificationChannel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected NotificationChannel.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationChannelCreate) createSpec() (*NotificationChannel, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationChannel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationchannel.Table, sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ChannelType(); ok {
		_spec.SetField(notificationchannel.FieldChannelType, field.TypeString, value)
		_node.ChannelType = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(notificationchannel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(notificationchannel.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(notificationchannel.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.SecretEnvelope(); ok {
		_spec.SetField(notificationchannel.FieldSecretEnvelope, field.TypeString, value)
		_node.SecretEnvelope = value
	}
	if value, ok := _c.mutation.AllowPrivate(); ok {
		_spec.SetField(notificationchannel.FieldAllowPrivate, field.TypeBool, value)
		_node.AllowPrivate = value
	}
	if value, ok := _c.mutation.EventKinds(); ok {
		_spec.SetField(notificationchannel.FieldEventKinds, field.TypeJSON, value)
		_node.EventKinds = value
	}
	if value, ok := _c.mutation.DigestEnabled(); ok {
		_spec.SetField(notificationchannel.FieldDigestEnabled, field.TypeBool, value)
		_node.DigestEnabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationchannel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationchannel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// NotificationChannelCreateBulk is the builder for creating many NotificationChannel entities in bulk.
type NotificationChannelCreateBulk struct {
	config
	err      error
	builders []*NotificationChannelCreate
}

// Save creates the NotificationChannel entities in the database.
func (_c *NotificationChannelCreateBulk) Save(ctx context.Context) ([]*NotificationChannel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationChannel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationChannelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationChannelCreateBulk) SaveX(ctx context.Context) []*NotificationChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationChannelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationChannelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
