// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/notificationchannel"
)

// NotificationChannel is the model entity for the NotificationChannel schema.
type NotificationChannel struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ChannelType holds the value of the "channel_type" field.
	ChannelType string `json:"channel_type,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Target holds the value of the "target" field.
	Target string `json:"target,omitempty"`
	// SecretEnvelope holds the value of the "secret_envelope" field.
	SecretEnvelope string `json:"secret_envelope,omitempty"`
	// AllowPrivate holds the value of the "allow_private" field.
	AllowPrivate bool `json:"allow_private,omitempty"`
	// EventKinds holds the value of the "event_kinds" field.
	EventKinds []string `json:"event_kinds,omitempty"`
	// DigestEnabled holds the value of the "digest_enabled" field.
	DigestEnabled bool `json:"digest_enabled,omitempty"`
	// ReceiveDailyDigest holds the value of the "receive_daily_digest" field.
	ReceiveDailyDigest bool `json:"receive_daily_digest,omitempty"`
	// ReceiveWeeklyReport holds the value of the "receive_weekly_report" field.
	ReceiveWeeklyReport bool `json:"receive_weekly_report,omitempty"`
	// ReceiveMonthlyReport holds the value of the "receive_monthly_report" field.
	ReceiveMonthlyReport bool `json:"receive_monthly_report,omitempty"`
	// QuietHoursEnabled holds the value of the "quiet_hours_enabled" field.
	QuietHoursEnabled bool `json:"quiet_hours_enabled,omitempty"`
	// QuietHoursStart holds the value of the "quiet_hours_start" field.
	QuietHoursStart string `json:"quiet_hours_start,omitempty"`
	// QuietHoursEnd holds the value of the "quiet_hours_end" field.
	QuietHoursEnd string `json:"quiet_hours_end,omitempty"`
	// QuietHoursTz holds the value of the "quiet_hours_tz" field.
	QuietHoursTz string `json:"quiet_hours_tz,omitempty"`
	// IgnoreBots holds the value of the "ignore_bots" field.
	IgnoreBots bool `json:"ignore_bots,omitempty"`
	// RepoPattern holds the value of the "repo_pattern" field.
	RepoPattern string `json:"repo_pattern,omitempty"`
	// BranchFilter holds the value of the "branch_filter" field.
	BranchFilter string `json:"branch_filter,omitempty"`
	// MinSeverity holds the value of the "min_severity" field.
	MinSeverity string `json:"min_severity,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationChannel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationchannel.FieldEventKinds:
			values[i] = new([]byte)
		case notificationchannel.FieldEnabled, notificationchannel.FieldAllowPrivate, notificationchannel.FieldDigestEnabled, notificationchannel.FieldReceiveDailyDigest, notificationchannel.FieldReceiveWeeklyReport, notificationchannel.FieldReceiveMonthlyReport, notificationchannel.FieldQuietHoursEnabled, notificationchannel.FieldIgnoreBots:
			values[i] = new(sql.NullBool)
		case notificationchannel.FieldID, notificationchannel.FieldChannelType, notificationchannel.FieldName, notificationchannel.FieldTarget, notificationchannel.FieldSecretEnvelope, notificationchannel.FieldQuietHoursStart, notificationchannel.FieldQuietHoursEnd, notificationchannel.FieldQuietHoursTz, notificationchannel.FieldRepoPattern, notificationchannel.FieldBranchFilter, notificationchannel.FieldMinSeverity:
			values[i] = new(sql.NullString)
		case notificationchannel.FieldCreatedAt, notificationchannel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationChannel fields.
func (_m *NotificationChannel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationchannel.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case notificationchannel.FieldChannelType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_type", values[i])
			} else if value.Valid {
				_m.ChannelType = value.String
			}
		case notificationchannel.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case notificationchannel.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case notificationchannel.FieldTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target", values[i])
			} else if value.Valid {
				_m.Target = value.String
			}
		case notificationchannel.FieldSecretEnvelope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_envelope", values[i])
			} else if value.Valid {
				_m.SecretEnvelope = value.String
			}
		case notificationchannel.FieldAllowPrivate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_private", values[i])
			} else if value.Valid {
				_m.AllowPrivate = value.Bool
			}
		case notificationchannel.FieldEventKinds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field event_kinds", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.EventKinds); err != nil {
					return fmt.Errorf("unmarshal field event_kinds: %w", err)
				}
			}
		case notificationchannel.FieldDigestEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field digest_enabled", values[i])
			} else if value.Valid {
				_m.DigestEnabled = value.Bool
			}
		case notificationchannel.FieldReceiveDailyDigest:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field receive_daily_digest", values[i])
			} else if value.Valid {
				_m.ReceiveDailyDigest = value.Bool
			}
		case notificationchannel.FieldReceiveWeeklyReport:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field receive_weekly_report", values[i])
			} else if value.Valid {
				_m.ReceiveWeeklyReport = value.Bool
			}
		case notificationchannel.FieldReceiveMonthlyReport:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field receive_monthly_report", values[i])
			} else if value.Valid {
				_m.ReceiveMonthlyReport = value.Bool
			}
		case notificationchannel.FieldQuietHoursEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field quiet_hours_enabled", values[i])
			} else if value.Valid {
				_m.QuietHoursEnabled = value.Bool
			}
		case notificationchannel.FieldQuietHoursStart:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quiet_hours_start", values[i])
			} else if value.Valid {
				_m.QuietHoursStart = value.String
			}
		case notificationchannel.FieldQuietHoursEnd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quiet_hours_end", values[i])
			} else if value.Valid {
				_m.QuietHoursEnd = value.String
			}
		case notificationchannel.FieldQuietHoursTz:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quiet_hours_tz", values[i])
			} else if value.Valid {
				_m.QuietHoursTz = value.String
			}
		case notificationchannel.FieldIgnoreBots:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field ignore_bots", values[i])
			} else if value.Valid {
				_m.IgnoreBots = value.Bool
			}
		case notificationchannel.FieldRepoPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_pattern", values[i])
			} else if value.Valid {
				_m.RepoPattern = value.String
			}
		case notificationchannel.FieldBranchFilter:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field branch_filter", values[i])
			} else if value.Valid {
				_m.BranchFilter = value.String
			}
		case notificationchannel.FieldMinSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field min_severity", values[i])
			} else if value.Valid {
				_m.MinSeverity = value.String
			}
		case notificationchannel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case notificationchannel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationChannel.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationChannel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NotificationChannel.
// Note that you need to call NotificationChannel.Unwrap() before calling this method if this NotificationChannel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationChannel) Update() *NotificationChannelUpdateOne {
	return NewNotificationChannelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationChannel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationChannel) Unwrap() *NotificationChannel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationChannel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationChannel) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationChannel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("channel_type=")
	builder.WriteString(_m.ChannelType)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("target=")
	builder.WriteString(_m.Target)
	builder.WriteString(", ")
	builder.WriteString("secret_envelope=")
	builder.WriteString(_m.SecretEnvelope)
	builder.WriteString(", ")
	builder.WriteString("allow_private=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowPrivate))
	builder.WriteString(", ")
	builder.WriteString("event_kinds=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventKinds))
	builder.WriteString(", ")
	builder.WriteString("digest_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.DigestEnabled))
	builder.WriteString(", ")
	builder.WriteString("receive_daily_digest=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReceiveDailyDigest))
	builder.WriteString(", ")
	builder.WriteString("receive_weekly_report=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReceiveWeeklyReport))
	builder.WriteString(", ")
	builder.WriteString("receive_monthly_report=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReceiveMonthlyReport))
	builder.WriteString(", ")
	builder.WriteString("quiet_hours_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuietHoursEnabled))
	builder.WriteString(", ")
	builder.WriteString("quiet_hours_start=")
	builder.WriteString(_m.QuietHoursStart)
	builder.WriteString(", ")
	builder.WriteString("quiet_hours_end=")
	builder.WriteString(_m.QuietHoursEnd)
	builder.WriteString(", ")
	builder.WriteString("quiet_hours_tz=")
	builder.WriteString(_m.QuietHoursTz)
	builder.WriteString(", ")
	builder.WriteString("ignore_bots=")
	builder.WriteString(fmt.Sprintf("%v", _m.IgnoreBots))
	builder.WriteString(", ")
	builder.WriteString("repo_pattern=")
	builder.WriteString(_m.RepoPattern)
	builder.WriteString(", ")
	builder.WriteString("branch_filter=")
	builder.WriteString(_m.BranchFilter)
	builder.WriteString(", ")
	builder.WriteString("min_severity=")
	builder.WriteString(_m.MinSeverity)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationChannels is a parsable slice of NotificationChannel.
type NotificationChannels []*NotificationChannel
