// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/predicate"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/repository"
)

// RepositoryUpdate is the builder for updating Repository entities.
type RepositoryUpdate struct {
	config
	hooks    []Hook
	mutation *RepositoryMutation
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdate) Where(ps ...predicate.Repository) *RepositoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *RepositoryUpdate) SetType(v string) *RepositoryUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableType(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSyncStatus sets the "sync_status" field.
func (_u *RepositoryUpdate) SetSyncStatus(v string) *RepositoryUpdate {
	_u.mutation.SetSyncStatus(v)
	return _u
}

// SetNillableSyncStatus sets the "sync_status" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableSyncStatus(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetSyncStatus(*v)
	}
	return _u
}

// SetGithubRepoID sets the "github_repo_id" field.
func (_u *RepositoryUpdate) SetGithubRepoID(v int64) *RepositoryUpdate {
	_u.mutation.ResetGithubRepoID()
	_u.mutation.SetGithubRepoID(v)
	return _u
}

// SetNillableGithubRepoID sets the "github_repo_id" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableGithubRepoID(v *int64) *RepositoryUpdate {
	if v != nil {
		_u.SetGithubRepoID(*v)
	}
	return _u
}

// AddGithubRepoID adds value to the "github_repo_id" field.
func (_u *RepositoryUpdate) AddGithubRepoID(v int64) *RepositoryUpdate {
	_u.mutation.AddGithubRepoID(v)
	return _u
}

// ClearGithubRepoID clears the value of the "github_repo_id" field.
func (_u *RepositoryUpdate) ClearGithubRepoID() *RepositoryUpdate {
	_u.mutation.ClearGithubRepoID()
	return _u
}

// SetOwner sets the "owner" field.
func (_u *RepositoryUpdate) SetOwner(v string) *RepositoryUpdate {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableOwner(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RepositoryUpdate) SetName(v string) *RepositoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableName(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *RepositoryUpdate) SetFullName(v string) *RepositoryUpdate {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableFullName(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetInstallationID sets the "installation_id" field.
func (_u *RepositoryUpdate) SetInstallationID(v string) *RepositoryUpdate {
	_u.mutation.SetInstallationID(v)
	return _u
}

// SetNillableInstallationID sets the "installation_id" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableInstallationID(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetInstallationID(*v)
	}
	return _u
}

// ClearInstallationID clears the value of the "installation_id" field.
func (_u *RepositoryUpdate) ClearInstallationID() *RepositoryUpdate {
	_u.mutation.ClearInstallationID()
	return _u
}

// SetIsArchived sets the "is_archived" field.
func (_u *RepositoryUpdate) SetIsArchived(v bool) *RepositoryUpdate {
	_u.mutation.SetIsArchived(v)
	return _u
}

// SetNillableIsArchived sets the "is_archived" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableIsArchived(v *bool) *RepositoryUpdate {
	if v != nil {
		_u.SetIsArchived(*v)
	}
	return _u
}

// SetIsPrivate sets the "is_private" field.
func (_u *RepositoryUpdate) SetIsPrivate(v bool) *RepositoryUpdate {
	_u.mutation.SetIsPrivate(v)
	return _u
}

// SetNillableIsPrivate sets the "is_private" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableIsPrivate(v *bool) *RepositoryUpdate {
	if v != nil {
		_u.SetIsPrivate(*v)
	}
	return _u
}

// SetMonitorEnabled sets the "monitor_enabled" field.
func (_u *RepositoryUpdate) SetMonitorEnabled(v bool) *RepositoryUpdate {
	_u.mutation.SetMonitorEnabled(v)
	return _u
}

// SetNillableMonitorEnabled sets the "monitor_enabled" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableMonitorEnabled(v *bool) *RepositoryUpdate {
	if v != nil {
		_u.SetMonitorEnabled(*v)
	}
	return _u
}

// SetIssuesEnabled sets the "issues_enabled" field.
func (_u *RepositoryUpdate) SetIssuesEnabled(v bool) *RepositoryUpdate {
	_u.mutation.SetIssuesEnabled(v)
	return _u
}

// SetNillableIssuesEnabled sets the "issues_enabled" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableIssuesEnabled(v *bool) *RepositoryUpdate {
	if v != nil {
		_u.SetIssuesEnabled(*v)
	}
	return _u
}

// SetPrEnabled sets the "pr_enabled" field.
func (_u *RepositoryUpdate) SetPrEnabled(v bool) *RepositoryUpdate {
	_u.mutation.SetPrEnabled(v)
	return _u
}

// SetNillablePrEnabled sets the "pr_enabled" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillablePrEnabled(v *bool) *RepositoryUpdate {
	if v != nil {
		_u.SetPrEnabled(*v)
	}
	return _u
}

// SetActionsEnabled sets the "actions_enabled" field.
func (_u *RepositoryUpdate) SetActionsEnabled(v bool) *RepositoryUpdate {
	_u.mutation.SetActionsEnabled(v)
	return _u
}

// SetNillableActionsEnabled sets the "actions_enabled" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableActionsEnabled(v *bool) *RepositoryUpdate {
	if v != nil {
		_u.SetActionsEnabled(*v)
	}
	return _u
}

// SetAlertsEnabled sets the "alerts_enabled" field.
func (_u *RepositoryUpdate) SetAlertsEnabled(v bool) *RepositoryUpdate {
	_u.mutation.SetAlertsEnabled(v)
	return _u
}

// SetNillableAlertsEnabled sets the "alerts_enabled" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableAlertsEnabled(v *bool) *RepositoryUpdate {
	if v != nil {
		_u.SetAlertsEnabled(*v)
	}
	return _u
}

// SetHTMLURL sets the "html_url" field.
func (_u *RepositoryUpdate) SetHTMLURL(v string) *RepositoryUpdate {
	_u.mutation.SetHTMLURL(v)
	return _u
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableHTMLURL(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetHTMLURL(*v)
	}
	return _u
}

// SetDefaultBranch sets the "default_branch" field.
func (_u *RepositoryUpdate) SetDefaultBranch(v string) *RepositoryUpdate {
	_u.mutation.SetDefaultBranch(v)
	return _u
}

// SetNillableDefaultBranch sets the "default_branch" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableDefaultBranch(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetDefaultBranch(*v)
	}
	return _u
}

// SetBaselineStartedAt sets the "baseline_started_at" field.
func (_u *RepositoryUpdate) SetBaselineStartedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetBaselineStartedAt(v)
	return _u
}

// SetNillableBaselineStartedAt sets the "baseline_started_at" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableBaselineStartedAt(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetBaselineStartedAt(*v)
	}
	return _u
}

// ClearBaselineStartedAt clears the value of the "baseline_started_at" field.
func (_u *RepositoryUpdate) ClearBaselineStartedAt() *RepositoryUpdate {
	_u.mutation.ClearBaselineStartedAt()
	return _u
}

// SetBaselineFinishedAt sets the "baseline_finished_at" field.
func (_u *RepositoryUpdate) SetBaselineFinishedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetBaselineFinishedAt(v)
	return _u
}

// SetNillableBaselineFinishedAt sets the "baseline_finished_at" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableBaselineFinishedAt(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetBaselineFinishedAt(*v)
	}
	return _u
}

// ClearBaselineFinishedAt clears the value of the "baseline_finished_at" field.
func (_u *RepositoryUpdate) ClearBaselineFinishedAt() *RepositoryUpdate {
	_u.mutation.ClearBaselineFinishedAt()
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *RepositoryUpdate) SetLastSyncedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableLastSyncedAt(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *RepositoryUpdate) ClearLastSyncedAt() *RepositoryUpdate {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetLastSyncErrorCode sets the "last_sync_error_code" field.
func (_u *RepositoryUpdate) SetLastSyncErrorCode(v string) *RepositoryUpdate {
	_u.mutation.SetLastSyncErrorCode(v)
	return _u
}

// SetNillableLastSyncErrorCode sets the "last_sync_error_code" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableLastSyncErrorCode(v *string) *RepositoryUpdate {
	if v != nil {
		_u.SetLastSyncErrorCode(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepositoryUpdate) SetUpdatedAt(v time.Time) *RepositoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RepositoryUpdate) SetNillableUpdatedAt(v *time.Time) *RepositoryUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdate) Mutation() *RepositoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RepositoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RepositoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RepositoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(repository.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncStatus(); ok {
		_spec.SetField(repository.FieldSyncStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GithubRepoID(); ok {
		_spec.SetField(repository.FieldGithubRepoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGithubRepoID(); ok {
		_spec.AddField(repository.FieldGithubRepoID, field.TypeInt64, value)
	}
	if _u.mutation.GithubRepoIDCleared() {
		_spec.ClearField(repository.FieldGithubRepoID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repository.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(repository.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstallationID(); ok {
		_spec.SetField(repository.FieldInstallationID, field.TypeString, value)
	}
	if _u.mutation.InstallationIDCleared() {
		_spec.ClearField(repository.FieldInstallationID, field.TypeString)
	}
	if value, ok := _u.mutation.IsArchived(); ok {
		_spec.SetField(repository.FieldIsArchived, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPrivate(); ok {
		_spec.SetField(repository.FieldIsPrivate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MonitorEnabled(); ok {
		_spec.SetField(repository.FieldMonitorEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IssuesEnabled(); ok {
		_spec.SetField(repository.FieldIssuesEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PrEnabled(); ok {
		_spec.SetField(repository.FieldPrEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ActionsEnabled(); ok {
		_spec.SetField(repository.FieldActionsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AlertsEnabled(); ok {
		_spec.SetField(repository.FieldAlertsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HTMLURL(); ok {
		_spec.SetField(repository.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultBranch(); ok {
		_spec.SetField(repository.FieldDefaultBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaselineStartedAt(); ok {
		_spec.SetField(repository.FieldBaselineStartedAt, field.TypeTime, value)
	}
	if _u.mutation.BaselineStartedAtCleared() {
		_spec.ClearField(repository.FieldBaselineStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BaselineFinishedAt(); ok {
		_spec.SetField(repository.FieldBaselineFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.BaselineFinishedAtCleared() {
		_spec.ClearField(repository.FieldBaselineFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(repository.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(repository.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncErrorCode(); ok {
		_spec.SetField(repository.FieldLastSyncErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RepositoryUpdateOne is the builder for updating a single Repository entity.
type RepositoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepositoryMutation
}

// SetType sets the "type" field.
func (_u *RepositoryUpdateOne) SetType(v string) *RepositoryUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableType(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSyncStatus sets the "sync_status" field.
func (_u *RepositoryUpdateOne) SetSyncStatus(v string) *RepositoryUpdateOne {
	_u.mutation.SetSyncStatus(v)
	return _u
}

// SetNillableSyncStatus sets the "sync_status" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableSyncStatus(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetSyncStatus(*v)
	}
	return _u
}

// SetGithubRepoID sets the "github_repo_id" field.
func (_u *RepositoryUpdateOne) SetGithubRepoID(v int64) *RepositoryUpdateOne {
	_u.mutation.ResetGithubRepoID()
	_u.mutation.SetGithubRepoID(v)
	return _u
}

// SetNillableGithubRepoID sets the "github_repo_id" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableGithubRepoID(v *int64) *RepositoryUpdateOne {
	if v != nil {
		_u.SetGithubRepoID(*v)
	}
	return _u
}

// AddGithubRepoID adds value to the "github_repo_id" field.
func (_u *RepositoryUpdateOne) AddGithubRepoID(v int64) *RepositoryUpdateOne {
	_u.mutation.AddGithubRepoID(v)
	return _u
}

// ClearGithubRepoID clears the value of the "github_repo_id" field.
func (_u *RepositoryUpdateOne) ClearGithubRepoID() *RepositoryUpdateOne {
	_u.mutation.ClearGithubRepoID()
	return _u
}

// SetOwner sets the "owner" field.
func (_u *RepositoryUpdateOne) SetOwner(v string) *RepositoryUpdateOne {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableOwner(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RepositoryUpdateOne) SetName(v string) *RepositoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableName(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *RepositoryUpdateOne) SetFullName(v string) *RepositoryUpdateOne {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableFullName(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetInstallationID sets the "installation_id" field.
func (_u *RepositoryUpdateOne) SetInstallationID(v string) *RepositoryUpdateOne {
	_u.mutation.SetInstallationID(v)
	return _u
}

// SetNillableInstallationID sets the "installation_id" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableInstallationID(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetInstallationID(*v)
	}
	return _u
}

// ClearInstallationID clears the value of the "installation_id" field.
func (_u *RepositoryUpdateOne) ClearInstallationID() *RepositoryUpdateOne {
	_u.mutation.ClearInstallationID()
	return _u
}

// SetIsArchived sets the "is_archived" field.
func (_u *RepositoryUpdateOne) SetIsArchived(v bool) *RepositoryUpdateOne {
	_u.mutation.SetIsArchived(v)
	return _u
}

// SetNillableIsArchived sets the "is_archived" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableIsArchived(v *bool) *RepositoryUpdateOne {
	if v != nil {
		_u.SetIsArchived(*v)
	}
	return _u
}

// SetIsPrivate sets the "is_private" field.
func (_u *RepositoryUpdateOne) SetIsPrivate(v bool) *RepositoryUpdateOne {
	_u.mutation.SetIsPrivate(v)
	return _u
}

// SetNillableIsPrivate sets the "is_private" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableIsPrivate(v *bool) *RepositoryUpdateOne {
	if v != nil {
		_u.SetIsPrivate(*v)
	}
	return _u
}

// SetMonitorEnabled sets the "monitor_enabled" field.
func (_u *RepositoryUpdateOne) SetMonitorEnabled(v bool) *RepositoryUpdateOne {
	_u.mutation.SetMonitorEnabled(v)
	return _u
}

// SetNillableMonitorEnabled sets the "monitor_enabled" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableMonitorEnabled(v *bool) *RepositoryUpdateOne {
	if v != nil {
		_u.SetMonitorEnabled(*v)
	}
	return _u
}

// SetIssuesEnabled sets the "issues_enabled" field.
func (_u *RepositoryUpdateOne) SetIssuesEnabled(v bool) *RepositoryUpdateOne {
	_u.mutation.SetIssuesEnabled(v)
	return _u
}

// SetNillableIssuesEnabled sets the "issues_enabled" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableIssuesEnabled(v *bool) *RepositoryUpdateOne {
	if v != nil {
		_u.SetIssuesEnabled(*v)
	}
	return _u
}

// SetPrEnabled sets the "pr_enabled" field.
func (_u *RepositoryUpdateOne) SetPrEnabled(v bool) *RepositoryUpdateOne {
	_u.mutation.SetPrEnabled(v)
	return _u
}

// SetNillablePrEnabled sets the "pr_enabled" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillablePrEnabled(v *bool) *RepositoryUpdateOne {
	if v != nil {
		_u.SetPrEnabled(*v)
	}
	return _u
}

// SetActionsEnabled sets the "actions_enabled" field.
func (_u *RepositoryUpdateOne) SetActionsEnabled(v bool) *RepositoryUpdateOne {
	_u.mutation.SetActionsEnabled(v)
	return _u
}

// SetNillableActionsEnabled sets the "actions_enabled" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableActionsEnabled(v *bool) *RepositoryUpdateOne {
	if v != nil {
		_u.SetActionsEnabled(*v)
	}
	return _u
}

// SetAlertsEnabled sets the "alerts_enabled" field.
func (_u *RepositoryUpdateOne) SetAlertsEnabled(v bool) *RepositoryUpdateOne {
	_u.mutation.SetAlertsEnabled(v)
	return _u
}

// SetNillableAlertsEnabled sets the "alerts_enabled" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableAlertsEnabled(v *bool) *RepositoryUpdateOne {
	if v != nil {
		_u.SetAlertsEnabled(*v)
	}
	return _u
}

// SetHTMLURL sets the "html_url" field.
func (_u *RepositoryUpdateOne) SetHTMLURL(v string) *RepositoryUpdateOne {
	_u.mutation.SetHTMLURL(v)
	return _u
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableHTMLURL(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetHTMLURL(*v)
	}
	return _u
}

// SetDefaultBranch sets the "default_branch" field.
func (_u *RepositoryUpdateOne) SetDefaultBranch(v string) *RepositoryUpdateOne {
	_u.mutation.SetDefaultBranch(v)
	return _u
}

// SetNillableDefaultBranch sets the "default_branch" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableDefaultBranch(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetDefaultBranch(*v)
	}
	return _u
}

// SetBaselineStartedAt sets the "baseline_started_at" field.
func (_u *RepositoryUpdateOne) SetBaselineStartedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetBaselineStartedAt(v)
	return _u
}

// SetNillableBaselineStartedAt sets the "baseline_started_at" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableBaselineStartedAt(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetBaselineStartedAt(*v)
	}
	return _u
}

// ClearBaselineStartedAt clears the value of the "baseline_started_at" field.
func (_u *RepositoryUpdateOne) ClearBaselineStartedAt() *RepositoryUpdateOne {
	_u.mutation.ClearBaselineStartedAt()
	return _u
}

// SetBaselineFinishedAt sets the "baseline_finished_at" field.
func (_u *RepositoryUpdateOne) SetBaselineFinishedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetBaselineFinishedAt(v)
	return _u
}

// SetNillableBaselineFinishedAt sets the "baseline_finished_at" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableBaselineFinishedAt(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetBaselineFinishedAt(*v)
	}
	return _u
}

// ClearBaselineFinishedAt clears the value of the "baseline_finished_at" field.
func (_u *RepositoryUpdateOne) ClearBaselineFinishedAt() *RepositoryUpdateOne {
	_u.mutation.ClearBaselineFinishedAt()
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *RepositoryUpdateOne) SetLastSyncedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableLastSyncedAt(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *RepositoryUpdateOne) ClearLastSyncedAt() *RepositoryUpdateOne {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetLastSyncErrorCode sets the "last_sync_error_code" field.
func (_u *RepositoryUpdateOne) SetLastSyncErrorCode(v string) *RepositoryUpdateOne {
	_u.mutation.SetLastSyncErrorCode(v)
	return _u
}

// SetNillableLastSyncErrorCode sets the "last_sync_error_code" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableLastSyncErrorCode(v *string) *RepositoryUpdateOne {
	if v != nil {
		_u.SetLastSyncErrorCode(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RepositoryUpdateOne) SetUpdatedAt(v time.Time) *RepositoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RepositoryUpdateOne) SetNillableUpdatedAt(v *time.Time) *RepositoryUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the RepositoryMutation object of the builder.
func (_u *RepositoryUpdateOne) Mutation() *RepositoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the RepositoryUpdate builder.
func (_u *RepositoryUpdateOne) Where(ps ...predicate.Repository) *RepositoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RepositoryUpdateOne) Select(field string, fields ...string) *RepositoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Repository entity.
func (_u *RepositoryUpdateOne) Save(ctx context.Context) (*Repository, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepositoryUpdateOne) SaveX(ctx context.Context) *Repository {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RepositoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepositoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RepositoryUpdateOne) sqlSave(ctx context.Context) (_node *Repository, err error) {
	_spec := sqlgraph.NewUpdateSpec(repository.Table, repository.Columns, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Repository.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repository.FieldID)
		for _, f := range fields {
			if !repository.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repository.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(repository.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncStatus(); ok {
		_spec.SetField(repository.FieldSyncStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GithubRepoID(); ok {
		_spec.SetField(repository.FieldGithubRepoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGithubRepoID(); ok {
		_spec.AddField(repository.FieldGithubRepoID, field.TypeInt64, value)
	}
	if _u.mutation.GithubRepoIDCleared() {
		_spec.ClearField(repository.FieldGithubRepoID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repository.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(repository.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstallationID(); ok {
		_spec.SetField(repository.FieldInstallationID, field.TypeString, value)
	}
	if _u.mutation.InstallationIDCleared() {
		_spec.ClearField(repository.FieldInstallationID, field.TypeString)
	}
	if value, ok := _u.mutation.IsArchived(); ok {
		_spec.SetField(repository.FieldIsArchived, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsPrivate(); ok {
		_spec.SetField(repository.FieldIsPrivate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MonitorEnabled(); ok {
		_spec.SetField(repository.FieldMonitorEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IssuesEnabled(); ok {
		_spec.SetField(repository.FieldIssuesEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PrEnabled(); ok {
		_spec.SetField(repository.FieldPrEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ActionsEnabled(); ok {
		_spec.SetField(repository.FieldActionsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AlertsEnabled(); ok {
		_spec.SetField(repository.FieldAlertsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HTMLURL(); ok {
		_spec.SetField(repository.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultBranch(); ok {
		_spec.SetField(repository.FieldDefaultBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaselineStartedAt(); ok {
		_spec.SetField(repository.FieldBaselineStartedAt, field.TypeTime, value)
	}
	if _u.mutation.BaselineStartedAtCleared() {
		_spec.ClearField(repository.FieldBaselineStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BaselineFinishedAt(); ok {
		_spec.SetField(repository.FieldBaselineFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.BaselineFinishedAtCleared() {
		_spec.ClearField(repository.FieldBaselineFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(repository.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(repository.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncErrorCode(); ok {
		_spec.SetField(repository.FieldLastSyncErrorCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Repository{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repository.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
