// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/predicate"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/securityalert"
)

// SecurityAlertDelete is the builder for deleting a SecurityAlert entity.
type SecurityAlertDelete struct {
	config
	hooks    []Hook
	mutation *SecurityAlertMutation
}

// Where appends a list predicates to the SecurityAlertDelete builder.
func (_d *SecurityAlertDelete) Where(ps ...predicate.SecurityAlert) *SecurityAlertDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SecurityAlertDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SecurityAlertDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SecurityAlertDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(securityalert.Table, sqlgraph.NewFieldSpec(securityalert.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SecurityAlertDeleteOne is the builder for deleting a single SecurityAlert entity.
type SecurityAlertDeleteOne struct {
	_d *SecurityAlertDelete
}

// Where appends a list predicates to the SecurityAlertDelete builder.
func (_d *SecurityAlertDeleteOne) Where(ps ...predicate.SecurityAlert) *SecurityAlertDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SecurityAlertDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{securityalert.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SecurityAlertDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
