// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/synccursor"
)

// SyncCursorCreate is the builder for creating a SyncCursor entity.
type SyncCursorCreate struct {
	config
	mutation *SyncCursorMutation
	hooks    []Hook
}

// SetRepositoryID sets the "repository_id" field.
func (_c *SyncCursorCreate) SetRepositoryID(v string) *SyncCursorCreate {
	_c.mutation.SetRepositoryID(v)
	return _c
}

// SetResource sets the "resource" field.
func (_c *SyncCursorCreate) SetResource(v string) *SyncCursorCreate {
	_c.mutation.SetResource(v)
	return _c
}

// SetCursorValue sets the "cursor_value" field.
func (_c *SyncCursorCreate) SetCursorValue(v string) *SyncCursorCreate {
	_c.mutation.SetCursorValue(v)
	return _c
}

// SetNillableCursorValue sets the "cursor_value" field if the given value is not nil.
func (_c *SyncCursorCreate) SetNillableCursorValue(v *string) *SyncCursorCreate {
	if v != nil {
		_c.SetCursorValue(*v)
	}
	return _c
}

// SetEtag sets the "etag" field.
func (_c *SyncCursorCreate) SetEtag(v string) *SyncCursorCreate {
	_c.mutation.SetEtag(v)
	return _c
}

// SetNillableEtag sets the "etag" field if the given value is not nil.
func (_c *SyncCursorCreate) SetNillableEtag(v *string) *SyncCursorCreate {
	if v != nil {
		_c.SetEtag(*v)
	}
	return _c
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_c *SyncCursorCreate) SetLastSuccessAt(v time.Time) *SyncCursorCreate {
	_c.mutation.SetLastSuccessAt(v)
	return _c
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_c *SyncCursorCreate) SetNillableLastSuccessAt(v *time.Time) *SyncCursorCreate {
	if v != nil {
		_c.SetLastSuccessAt(*v)
	}
	return _c
}

// SetLastErrorCode sets the "last_error_code" field.
func (_c *SyncCursorCreate) SetLastErrorCode(v string) *SyncCursorCreate {
	_c.mutation.SetLastErrorCode(v)
	return _c
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_c *SyncCursorCreate) SetNillableLastErrorCode(v *string) *SyncCursorCreate {
	if v != nil {
		_c.SetLastErrorCode(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SyncCursorCreate) SetUpdatedAt(v time.Time) *SyncCursorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SyncCursorCreate) SetID(v string) *SyncCursorCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SyncCursorMutation object of the builder.
func (_c *SyncCursorCreate) Mutation() *SyncCursorMutation {
	return _c.mutation
}

// Save creates the SyncCursor in the database.
func (_c *SyncCursorCreate) Save(ctx context.Context) (*SyncCursor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SyncCursorCreate) SaveX(ctx context.Context) *SyncCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncCursorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncCursorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SyncCursorCreate) defaults() {
	if _, ok := _c.mutation.CursorValue(); !ok {
		v := synccursor.DefaultCursorValue
		_c.mutation.SetCursorValue(v)
	}
	if _, ok := _c.mutation.Etag(); !ok {
		v := synccursor.DefaultEtag
		_c.mutation.SetEtag(v)
	}
	if _, ok := _c.mutation.LastErrorCode(); !ok {
		v := synccursor.DefaultLastErrorCode
		_c.mutation.SetLastErrorCode(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SyncCursorCreate) check() error {
	if _, ok := _c.mutation.RepositoryID(); !ok {
		return &ValidationError{Name: "repository_id", err: errors.New(`ent: missing required field "SyncCursor.repository_id"`)}
	}
	if _, ok := _c.mutation.Resource(); !ok {
		return &ValidationError{Name: "resource", err: errors.New(`ent: missing required field "SyncCursor.resource"`)}
	}
	if _, ok := _c.mutation.CursorValue(); !ok {
		return &ValidationError{Name: "cursor_value", err: errors.New(`ent: missing required field "SyncCursor.cursor_value"`)}
	}
	if _, ok := _c.mutation.Etag(); !ok {
		return &ValidationError{Name: "etag", err: errors.New(`ent: missing required field "SyncCursor.etag"`)}
	}
	if _, ok := _c.mutation.LastErrorCode(); !ok {
		return &ValidationError{Name: "last_error_code", err: errors.New(`ent: missing required field "SyncCursor.last_error_code"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SyncCursor.updated_at"`)}
	}
	return nil
}

func (_c *SyncCursorCreate) sqlSave(ctx context.Context) (*SyncCursor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SyncCursor.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SyncCursorCreate) createSpec() (*SyncCursor, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncCursor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(synccursor.Table, sqlgraph.NewFieldSpec(synccursor.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RepositoryID(); ok {
		_spec.SetField(synccursor.FieldRepositoryID, field.TypeString, value)
		_node.RepositoryID = value
	}
	if value, ok := _c.mutation.Resource(); ok {
		_spec.SetField(synccursor.FieldResource, field.TypeString, value)
		_node.Resource = value
	}
	if value, ok := _c.mutation.CursorValue(); ok {
		_spec.SetField(synccursor.FieldCursorValue, field.TypeString, value)
		_node.CursorValue = value
	}
	if value, ok := _c.mutation.Etag(); ok {
		_spec.SetField(synccursor.FieldEtag, field.TypeString, value)
		_node.Etag = value
	}
	if value, ok := _c.mutation.LastSuccessAt(); ok {
		_spec.SetField(synccursor.FieldLastSuccessAt, field.TypeTime, value)
		_node.LastSuccessAt = &value
	}
	if value, ok := _c.mutation.LastErrorCode(); ok {
		_spec.SetField(synccursor.FieldLastErrorCode, field.TypeString, value)
		_node.LastErrorCode = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(synccursor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// SyncCursorCreateBulk is the builder for creating many SyncCursor entities in bulk.
type SyncCursorCreateBulk struct {
	config
	err      error
	builders []*SyncCursorCreate
}

// Save creates the SyncCursor entities in the database.
func (_c *SyncCursorCreateBulk) Save(ctx context.Context) ([]*SyncCursor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SyncCursor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncCursorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SyncCursorCreateBulk) SaveX(ctx context.Context) []*SyncCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncCursorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncCursorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
