// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/predicate"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/systemlease"
)

// SystemLeaseUpdate is the builder for updating SystemLease entities.
type SystemLeaseUpdate struct {
	config
	hooks    []Hook
	mutation *SystemLeaseMutation
}

// Where appends a list predicates to the SystemLeaseUpdate builder.
func (_u *SystemLeaseUpdate) Where(ps ...predicate.SystemLease) *SystemLeaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskName sets the "task_name" field.
func (_u *SystemLeaseUpdate) SetTaskName(v string) *SystemLeaseUpdate {
	_u.mutation.SetTaskName(v)
	return _u
}

// SetNillableTaskName sets the "task_name" field if the given value is not nil.
func (_u *SystemLeaseUpdate) SetNillableTaskName(v *string) *SystemLeaseUpdate {
	if v != nil {
		_u.SetTaskName(*v)
	}
	return _u
}

// SetHolderID sets the "holder_id" field.
func (_u *SystemLeaseUpdate) SetHolderID(v string) *SystemLeaseUpdate {
	_u.mutation.SetHolderID(v)
	return _u
}

// SetNillableHolderID sets the "holder_id" field if the given value is not nil.
func (_u *SystemLeaseUpdate) SetNillableHolderID(v *string) *SystemLeaseUpdate {
	if v != nil {
		_u.SetHolderID(*v)
	}
	return _u
}

// SetAcquiredAt sets the "acquired_at" field.
func (_u *SystemLeaseUpdate) SetAcquiredAt(v time.Time) *SystemLeaseUpdate {
	_u.mutation.SetAcquiredAt(v)
	return _u
}

// SetNillableAcquiredAt sets the "acquired_at" field if the given value is not nil.
func (_u *SystemLeaseUpdate) SetNillableAcquiredAt(v *time.Time) *SystemLeaseUpdate {
	if v != nil {
		_u.SetAcquiredAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SystemLeaseUpdate) SetExpiresAt(v time.Time) *SystemLeaseUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SystemLeaseUpdate) SetNillableExpiresAt(v *time.Time) *SystemLeaseUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetFencingToken sets the "fencing_token" field.
func (_u *SystemLeaseUpdate) SetFencingToken(v int64) *SystemLeaseUpdate {
	_u.mutation.ResetFencingToken()
	_u.mutation.SetFencingToken(v)
	return _u
}

// SetNillableFencingToken sets the "fencing_token" field if the given value is not nil.
func (_u *SystemLeaseUpdate) SetNillableFencingToken(v *int64) *SystemLeaseUpdate {
	if v != nil {
		_u.SetFencingToken(*v)
	}
	return _u
}

// AddFencingToken adds value to the "fencing_token" field.
func (_u *SystemLeaseUpdate) AddFencingToken(v int64) *SystemLeaseUpdate {
	_u.mutation.AddFencingToken(v)
	return _u
}

// Mutation returns the SystemLeaseMutation object of the builder.
func (_u *SystemLeaseUpdate) Mutation() *SystemLeaseMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemLeaseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemLeaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemLeaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemLeaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemLeaseUpdate) check() error {
	if v, ok := _u.mutation.TaskName(); ok {
		if err := systemlease.TaskNameValidator(v); err != nil {
			return &ValidationError{Name: "task_name", err: fmt.Errorf(`ent: validator failed for field "SystemLease.task_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemLeaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemlease.Table, systemlease.Columns, sqlgraph.NewFieldSpec(systemlease.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskName(); ok {
		_spec.SetField(systemlease.FieldTaskName, field.TypeString, value)
	}
	if value, ok := _u.mutation.HolderID(); ok {
		_spec.SetField(systemlease.FieldHolderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AcquiredAt(); ok {
		_spec.SetField(systemlease.FieldAcquiredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(systemlease.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FencingToken(); ok {
		_spec.SetField(systemlease.FieldFencingToken, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFencingToken(); ok {
		_spec.AddField(systemlease.FieldFencingToken, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemlease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemLeaseUpdateOne is the builder for updating a single SystemLease entity.
type SystemLeaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemLeaseMutation
}

// SetTaskName sets the "task_name" field.
func (_u *SystemLeaseUpdateOne) SetTaskName(v string) *SystemLeaseUpdateOne {
	_u.mutation.SetTaskName(v)
	return _u
}

// SetNillableTaskName sets the "task_name" field if the given value is not nil.
func (_u *SystemLeaseUpdateOne) SetNillableTaskName(v *string) *SystemLeaseUpdateOne {
	if v != nil {
		_u.SetTaskName(*v)
	}
	return _u
}

// SetHolderID sets the "holder_id" field.
func (_u *SystemLeaseUpdateOne) SetHolderID(v string) *SystemLeaseUpdateOne {
	_u.mutation.SetHolderID(v)
	return _u
}

// SetNillableHolderID sets the "holder_id" field if the given value is not nil.
func (_u *SystemLeaseUpdateOne) SetNillableHolderID(v *string) *SystemLeaseUpdateOne {
	if v != nil {
		_u.SetHolderID(*v)
	}
	return _u
}

// SetAcquiredAt sets the "acquired_at" field.
func (_u *SystemLeaseUpdateOne) SetAcquiredAt(v time.Time) *SystemLeaseUpdateOne {
	_u.mutation.SetAcquiredAt(v)
	return _u
}

// SetNillableAcquiredAt sets the "acquired_at" field if the given value is not nil.
func (_u *SystemLeaseUpdateOne) SetNillableAcquiredAt(v *time.Time) *SystemLeaseUpdateOne {
	if v != nil {
		_u.SetAcquiredAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SystemLeaseUpdateOne) SetExpiresAt(v time.Time) *SystemLeaseUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SystemLeaseUpdateOne) SetNillableExpiresAt(v *time.Time) *SystemLeaseUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetFencingToken sets the "fencing_token" field.
func (_u *SystemLeaseUpdateOne) SetFencingToken(v int64) *SystemLeaseUpdateOne {
	_u.mutation.ResetFencingToken()
	_u.mutation.SetFencingToken(v)
	return _u
}

// SetNillableFencingToken sets the "fencing_token" field if the given value is not nil.
func (_u *SystemLeaseUpdateOne) SetNillableFencingToken(v *int64) *SystemLeaseUpdateOne {
	if v != nil {
		_u.SetFencingToken(*v)
	}
	return _u
}

// AddFencingToken adds value to the "fencing_token" field.
func (_u *SystemLeaseUpdateOne) AddFencingToken(v int64) *SystemLeaseUpdateOne {
	_u.mutation.AddFencingToken(v)
	return _u
}

// Mutation returns the SystemLeaseMutation object of the builder.
func (_u *SystemLeaseUpdateOne) Mutation() *SystemLeaseMutation {
	return _u.mutation
}

// Where appends a list predicates to the SystemLeaseUpdate builder.
func (_u *SystemLeaseUpdateOne) Where(ps ...predicate.SystemLease) *SystemLeaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemLeaseUpdateOne) Select(field string, fields ...string) *SystemLeaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemLease entity.
func (_u *SystemLeaseUpdateOne) Save(ctx context.Context) (*SystemLease, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemLeaseUpdateOne) SaveX(ctx context.Context) *SystemLease {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemLeaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemLeaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemLeaseUpdateOne) check() error {
	if v, ok := _u.mutation.TaskName(); ok {
		if err := systemlease.TaskNameValidator(v); err != nil {
			return &ValidationError{Name: "task_name", err: fmt.Errorf(`ent: validator failed for field "SystemLease.task_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemLeaseUpdateOne) sqlSave(ctx context.Context) (_node *SystemLease, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemlease.Table, systemlease.Columns, sqlgraph.NewFieldSpec(systemlease.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemLease.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemlease.FieldID)
		for _, f := range fields {
			if !systemlease.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemlease.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskName(); ok {
		_spec.SetField(systemlease.FieldTaskName, field.TypeString, value)
	}
	if value, ok := _u.mutation.HolderID(); ok {
		_spec.SetField(systemlease.FieldHolderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AcquiredAt(); ok {
		_spec.SetField(systemlease.FieldAcquiredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(systemlease.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FencingToken(); ok {
		_spec.SetField(systemlease.FieldFencingToken, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFencingToken(); ok {
		_spec.AddField(systemlease.FieldFencingToken, field.TypeInt64, value)
	}
	_node = &SystemLease{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemlease.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
