// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/webhookdelivery"
)

// WebhookDeliveryCreate is the builder for creating a WebhookDelivery entity.
type WebhookDeliveryCreate struct {
	config
	mutation *WebhookDeliveryMutation
	hooks    []Hook
}

// SetDeliveryID sets the "delivery_id" field.
func (_c *WebhookDeliveryCreate) SetDeliveryID(v string) *WebhookDeliveryCreate {
	_c.mutation.SetDeliveryID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *WebhookDeliveryCreate) SetEventType(v string) *WebhookDeliveryCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *WebhookDeliveryCreate) SetAction(v string) *WebhookDeliveryCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableAction(v *string) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetRepositoryFullName sets the "repository_full_name" field.
func (_c *WebhookDeliveryCreate) SetRepositoryFullName(v string) *WebhookDeliveryCreate {
	_c.mutation.SetRepositoryFullName(v)
	return _c
}

// SetNillableRepositoryFullName sets the "repository_full_name" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableRepositoryFullName(v *string) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetRepositoryFullName(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *WebhookDeliveryCreate) SetStatus(v string) *WebhookDeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableStatus(v *string) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *WebhookDeliveryCreate) SetErrorCode(v string) *WebhookDeliveryCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableErrorCode(v *string) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *WebhookDeliveryCreate) SetPayload(v []byte) *WebhookDeliveryCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *WebhookDeliveryCreate) SetReceivedAt(v time.Time) *WebhookDeliveryCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetProcessedAt sets the "processed_at" field.
func (_c *WebhookDeliveryCreate) SetProcessedAt(v time.Time) *WebhookDeliveryCreate {
	_c.mutation.SetProcessedAt(v)
	return _c
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableProcessedAt(v *time.Time) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetProcessedAt(*v)
	}
	return _c
}

// SetClaimToken sets the "claim_token" field.
func (_c *WebhookDeliveryCreate) SetClaimToken(v string) *WebhookDeliveryCreate {
	_c.mutation.SetClaimToken(v)
	return _c
}

// SetNillableClaimToken sets the "claim_token" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableClaimToken(v *string) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetClaimToken(*v)
	}
	return _c
}

// SetClaimVersion sets the "claim_version" field.
func (_c *WebhookDeliveryCreate) SetClaimVersion(v int64) *WebhookDeliveryCreate {
	_c.mutation.SetClaimVersion(v)
	return _c
}

// SetNillableClaimVersion sets the "claim_version" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableClaimVersion(v *int64) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetClaimVersion(*v)
	}
	return _c
}

// SetClaimedBy sets the "claimed_by" field.
func (_c *WebhookDeliveryCreate) SetClaimedBy(v string) *WebhookDeliveryCreate {
	_c.mutation.SetClaimedBy(v)
	return _c
}

// SetNillableClaimedBy sets the "claimed_by" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableClaimedBy(v *string) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetClaimedBy(*v)
	}
	return _c
}

// SetClaimedUntil sets the "claimed_until" field.
func (_c *WebhookDeliveryCreate) SetClaimedUntil(v time.Time) *WebhookDeliveryCreate {
	_c.mutation.SetClaimedUntil(v)
	return _c
}

// SetNillableClaimedUntil sets the "claimed_until" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableClaimedUntil(v *time.Time) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetClaimedUntil(*v)
	}
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *WebhookDeliveryCreate) SetAttemptCount(v int) *WebhookDeliveryCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableAttemptCount(v *int) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetLastErrorCode sets the "last_error_code" field.
func (_c *WebhookDeliveryCreate) SetLastErrorCode(v string) *WebhookDeliveryCreate {
	_c.mutation.SetLastErrorCode(v)
	return _c
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_c *WebhookDeliveryCreate) SetNillableLastErrorCode(v *string) *WebhookDeliveryCreate {
	if v != nil {
		_c.SetLastErrorCode(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WebhookDeliveryCreate) SetID(v string) *WebhookDeliveryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the WebhookDeliveryMutation object of the builder.
func (_c *WebhookDeliveryCreate) Mutation() *WebhookDeliveryMutation {
	return _c.mutation
}

// Save creates the WebhookDelivery in the database.
func (_c *WebhookDeliveryCreate) Save(ctx context.Context) (*WebhookDelivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebhookDeliveryCreate) SaveX(ctx context.Context) *WebhookDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebhookDeliveryCreate) defaults() {
	if _, ok := _c.mutation.Action(); !ok {
		v := webhookdelivery.DefaultAction
		_c.mutation.SetAction(v)
	}
	if _, ok := _c.mutation.RepositoryFullName(); !ok {
		v := webhookdelivery.DefaultRepositoryFullName
		_c.mutation.SetRepositoryFullName(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := webhookdelivery.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		v := webhookdelivery.DefaultErrorCode
		_c.mutation.SetErrorCode(v)
	}
	if _, ok := _c.mutation.ClaimToken(); !ok {
		v := webhookdelivery.DefaultClaimToken
		_c.mutation.SetClaimToken(v)
	}
	if _, ok := _c.mutation.ClaimVersion(); !ok {
		v := webhookdelivery.DefaultClaimVersion
		_c.mutation.SetClaimVersion(v)
	}
	if _, ok := _c.mutation.ClaimedBy(); !ok {
		v := webhookdelivery.DefaultClaimedBy
		_c.mutation.SetClaimedBy(v)
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := webhookdelivery.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
	if _, ok := _c.mutation.LastErrorCode(); !ok {
		v := webhookdelivery.DefaultLastErrorCode
		_c.mutation.SetLastErrorCode(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebhookDeliveryCreate) check() error {
	if _, ok := _c.mutation.DeliveryID(); !ok {
		return &ValidationError{Name: "delivery_id", err: errors.New(`ent: missing required field "WebhookDelivery.delivery_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "WebhookDelivery.event_type"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "WebhookDelivery.action"`)}
	}
	if _, ok := _c.mutation.RepositoryFullName(); !ok {
		return &ValidationError{Name: "repository_full_name", err: errors.New(`ent: missing required field "WebhookDelivery.repository_full_name"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WebhookDelivery.status"`)}
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "WebhookDelivery.error_code"`)}
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "WebhookDelivery.received_at"`)}
	}
	if _, ok := _c.mutation.ClaimToken(); !ok {
		return &ValidationError{Name: "claim_token", err: errors.New(`ent: missing required field "WebhookDelivery.claim_token"`)}
	}
	if _, ok := _c.mutation.ClaimVersion(); !ok {
		return &ValidationError{Name: "claim_version", err: errors.New(`ent: missing required field "WebhookDelivery.claim_version"`)}
	}
	if _, ok := _c.mutation.ClaimedBy(); !ok {
		return &ValidationError{Name: "claimed_by", err: errors.New(`ent: missing required field "WebhookDelivery.claimed_by"`)}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "WebhookDelivery.attempt_count"`)}
	}
	if _, ok := _c.mutation.LastErrorCode(); !ok {
		return &ValidationError{Name: "last_error_code", err: errors.New(`ent: missing required field "WebhookDelivery.last_error_code"`)}
	}
	return nil
}

func (_c *WebhookDeliveryCreate) sqlSave(ctx context.Context) (*WebhookDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected WebhookDelivery.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebhookDeliveryCreate) createSpec() (*WebhookDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &WebhookDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webhookdelivery.Table, sqlgraph.NewFieldSpec(webhookdelivery.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeliveryID(); ok {
		_spec.SetField(webhookdelivery.FieldDeliveryID, field.TypeString, value)
		_node.DeliveryID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(webhookdelivery.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(webhookdelivery.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.RepositoryFullName(); ok {
		_spec.SetField(webhookdelivery.FieldRepositoryFullName, field.TypeString, value)
		_node.RepositoryFullName = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(webhookdelivery.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(webhookdelivery.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(webhookdelivery.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(webhookdelivery.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	if value, ok := _c.mutation.ProcessedAt(); ok {
		_spec.SetField(webhookdelivery.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if value, ok := _c.mutation.ClaimToken(); ok {
		_spec.SetField(webhookdelivery.FieldClaimToken, field.TypeString, value)
		_node.ClaimToken = value
	}
	if value, ok := _c.mutation.ClaimVersion(); ok {
		_spec.SetField(webhookdelivery.FieldClaimVersion, field.TypeInt64, value)
		_node.ClaimVersion = value
	}
	if value, ok := _c.mutation.ClaimedBy(); ok {
		_spec.SetField(webhookdelivery.FieldClaimedBy, field.TypeString, value)
		_node.ClaimedBy = value
	}
	if value, ok := _c.mutation.ClaimedUntil(); ok {
		_spec.SetField(webhookdelivery.FieldClaimedUntil, field.TypeTime, value)
		_node.ClaimedUntil = &value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(webhookdelivery.FieldAttemptCount, field.TypeInt, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.LastErrorCode(); ok {
		_spec.SetField(webhookdelivery.FieldLastErrorCode, field.TypeString, value)
		_node.LastErrorCode = value
	}
	return _node, _spec
}

// WebhookDeliveryCreateBulk is the builder for creating many WebhookDelivery entities in bulk.
type WebhookDeliveryCreateBulk struct {
	config
	err      error
	builders []*WebhookDeliveryCreate
}

// Save creates the WebhookDelivery entities in the database.
func (_c *WebhookDeliveryCreateBulk) Save(ctx context.Context) ([]*WebhookDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebhookDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebhookDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebhookDeliveryCreateBulk) SaveX(ctx context.Context) []*WebhookDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
