// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/predicate"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/workitem"
)

// WorkItemUpdate is the builder for updating WorkItem entities.
type WorkItemUpdate struct {
	config
	hooks    []Hook
	mutation *WorkItemMutation
}

// Where appends a list predicates to the WorkItemUpdate builder.
func (_u *WorkItemUpdate) Where(ps ...predicate.WorkItem) *WorkItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRepositoryID sets the "repository_id" field.
func (_u *WorkItemUpdate) SetRepositoryID(v string) *WorkItemUpdate {
	_u.mutation.SetRepositoryID(v)
	return _u
}

// SetNillableRepositoryID sets the "repository_id" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableRepositoryID(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetRepositoryID(*v)
	}
	return _u
}

// SetNumber sets the "number" field.
func (_u *WorkItemUpdate) SetNumber(v int) *WorkItemUpdate {
	_u.mutation.ResetNumber()
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableNumber(v *int) *WorkItemUpdate {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// AddNumber adds value to the "number" field.
func (_u *WorkItemUpdate) AddNumber(v int) *WorkItemUpdate {
	_u.mutation.AddNumber(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *WorkItemUpdate) SetKind(v string) *WorkItemUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableKind(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *WorkItemUpdate) SetState(v string) *WorkItemUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableState(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *WorkItemUpdate) SetTitle(v string) *WorkItemUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableTitle(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *WorkItemUpdate) SetAuthor(v string) *WorkItemUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableAuthor(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetLabelsJSON sets the "labels_json" field.
func (_u *WorkItemUpdate) SetLabelsJSON(v []interface{}) *WorkItemUpdate {
	_u.mutation.SetLabelsJSON(v)
	return _u
}

// AppendLabelsJSON appends value to the "labels_json" field.
func (_u *WorkItemUpdate) AppendLabelsJSON(v []interface{}) *WorkItemUpdate {
	_u.mutation.AppendLabelsJSON(v)
	return _u
}

// ClearLabelsJSON clears the value of the "labels_json" field.
func (_u *WorkItemUpdate) ClearLabelsJSON() *WorkItemUpdate {
	_u.mutation.ClearLabelsJSON()
	return _u
}

// SetAssigneesJSON sets the "assignees_json" field.
func (_u *WorkItemUpdate) SetAssigneesJSON(v []interface{}) *WorkItemUpdate {
	_u.mutation.SetAssigneesJSON(v)
	return _u
}

// AppendAssigneesJSON appends value to the "assignees_json" field.
func (_u *WorkItemUpdate) AppendAssigneesJSON(v []interface{}) *WorkItemUpdate {
	_u.mutation.AppendAssigneesJSON(v)
	return _u
}

// ClearAssigneesJSON clears the value of the "assignees_json" field.
func (_u *WorkItemUpdate) ClearAssigneesJSON() *WorkItemUpdate {
	_u.mutation.ClearAssigneesJSON()
	return _u
}

// SetMilestone sets the "milestone" field.
func (_u *WorkItemUpdate) SetMilestone(v string) *WorkItemUpdate {
	_u.mutation.SetMilestone(v)
	return _u
}

// SetNillableMilestone sets the "milestone" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableMilestone(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetMilestone(*v)
	}
	return _u
}

// SetDraft sets the "draft" field.
func (_u *WorkItemUpdate) SetDraft(v bool) *WorkItemUpdate {
	_u.mutation.SetDraft(v)
	return _u
}

// SetNillableDraft sets the "draft" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableDraft(v *bool) *WorkItemUpdate {
	if v != nil {
		_u.SetDraft(*v)
	}
	return _u
}

// SetMerged sets the "merged" field.
func (_u *WorkItemUpdate) SetMerged(v bool) *WorkItemUpdate {
	_u.mutation.SetMerged(v)
	return _u
}

// SetNillableMerged sets the "merged" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableMerged(v *bool) *WorkItemUpdate {
	if v != nil {
		_u.SetMerged(*v)
	}
	return _u
}

// SetHTMLURL sets the "html_url" field.
func (_u *WorkItemUpdate) SetHTMLURL(v string) *WorkItemUpdate {
	_u.mutation.SetHTMLURL(v)
	return _u
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableHTMLURL(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetHTMLURL(*v)
	}
	return _u
}

// SetSourceUpdatedAt sets the "source_updated_at" field.
func (_u *WorkItemUpdate) SetSourceUpdatedAt(v time.Time) *WorkItemUpdate {
	_u.mutation.SetSourceUpdatedAt(v)
	return _u
}

// SetNillableSourceUpdatedAt sets the "source_updated_at" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableSourceUpdatedAt(v *time.Time) *WorkItemUpdate {
	if v != nil {
		_u.SetSourceUpdatedAt(*v)
	}
	return _u
}

// SetStateHash sets the "state_hash" field.
func (_u *WorkItemUpdate) SetStateHash(v string) *WorkItemUpdate {
	_u.mutation.SetStateHash(v)
	return _u
}

// SetNillableStateHash sets the "state_hash" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableStateHash(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetStateHash(*v)
	}
	return _u
}

// SetReviewState sets the "review_state" field.
func (_u *WorkItemUpdate) SetReviewState(v string) *WorkItemUpdate {
	_u.mutation.SetReviewState(v)
	return _u
}

// SetNillableReviewState sets the "review_state" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableReviewState(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetReviewState(*v)
	}
	return _u
}

// SetReviewDecision sets the "review_decision" field.
func (_u *WorkItemUpdate) SetReviewDecision(v string) *WorkItemUpdate {
	_u.mutation.SetReviewDecision(v)
	return _u
}

// SetNillableReviewDecision sets the "review_decision" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableReviewDecision(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetReviewDecision(*v)
	}
	return _u
}

// SetReviewers sets the "reviewers" field.
func (_u *WorkItemUpdate) SetReviewers(v []string) *WorkItemUpdate {
	_u.mutation.SetReviewers(v)
	return _u
}

// AppendReviewers appends value to the "reviewers" field.
func (_u *WorkItemUpdate) AppendReviewers(v []string) *WorkItemUpdate {
	_u.mutation.AppendReviewers(v)
	return _u
}

// ClearReviewers clears the value of the "reviewers" field.
func (_u *WorkItemUpdate) ClearReviewers() *WorkItemUpdate {
	_u.mutation.ClearReviewers()
	return _u
}

// SetCheckStatus sets the "check_status" field.
func (_u *WorkItemUpdate) SetCheckStatus(v string) *WorkItemUpdate {
	_u.mutation.SetCheckStatus(v)
	return _u
}

// SetNillableCheckStatus sets the "check_status" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableCheckStatus(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetCheckStatus(*v)
	}
	return _u
}

// SetCheckConclusion sets the "check_conclusion" field.
func (_u *WorkItemUpdate) SetCheckConclusion(v string) *WorkItemUpdate {
	_u.mutation.SetCheckConclusion(v)
	return _u
}

// SetNillableCheckConclusion sets the "check_conclusion" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableCheckConclusion(v *string) *WorkItemUpdate {
	if v != nil {
		_u.SetCheckConclusion(*v)
	}
	return _u
}

// SetChecksTotal sets the "checks_total" field.
func (_u *WorkItemUpdate) SetChecksTotal(v int) *WorkItemUpdate {
	_u.mutation.ResetChecksTotal()
	_u.mutation.SetChecksTotal(v)
	return _u
}

// SetNillableChecksTotal sets the "checks_total" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableChecksTotal(v *int) *WorkItemUpdate {
	if v != nil {
		_u.SetChecksTotal(*v)
	}
	return _u
}

// AddChecksTotal adds value to the "checks_total" field.
func (_u *WorkItemUpdate) AddChecksTotal(v int) *WorkItemUpdate {
	_u.mutation.AddChecksTotal(v)
	return _u
}

// SetChecksPassed sets the "checks_passed" field.
func (_u *WorkItemUpdate) SetChecksPassed(v int) *WorkItemUpdate {
	_u.mutation.ResetChecksPassed()
	_u.mutation.SetChecksPassed(v)
	return _u
}

// SetNillableChecksPassed sets the "checks_passed" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableChecksPassed(v *int) *WorkItemUpdate {
	if v != nil {
		_u.SetChecksPassed(*v)
	}
	return _u
}

// AddChecksPassed adds value to the "checks_passed" field.
func (_u *WorkItemUpdate) AddChecksPassed(v int) *WorkItemUpdate {
	_u.mutation.AddChecksPassed(v)
	return _u
}

// SetIgnored sets the "ignored" field.
func (_u *WorkItemUpdate) SetIgnored(v bool) *WorkItemUpdate {
	_u.mutation.SetIgnored(v)
	return _u
}

// SetNillableIgnored sets the "ignored" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableIgnored(v *bool) *WorkItemUpdate {
	if v != nil {
		_u.SetIgnored(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkItemUpdate) SetUpdatedAt(v time.Time) *WorkItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WorkItemUpdate) SetNillableUpdatedAt(v *time.Time) *WorkItemUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the WorkItemMutation object of the builder.
func (_u *WorkItemUpdate) Mutation() *WorkItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workitem.Table, workitem.Columns, sqlgraph.NewFieldSpec(workitem.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepositoryID(); ok {
		_spec.SetField(workitem.FieldRepositoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(workitem.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumber(); ok {
		_spec.AddField(workitem.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(workitem.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(workitem.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(workitem.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(workitem.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.LabelsJSON(); ok {
		_spec.SetField(workitem.FieldLabelsJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLabelsJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workitem.FieldLabelsJSON, value)
		})
	}
	if _u.mutation.LabelsJSONCleared() {
		_spec.ClearField(workitem.FieldLabelsJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.AssigneesJSON(); ok {
		_spec.SetField(workitem.FieldAssigneesJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAssigneesJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workitem.FieldAssigneesJSON, value)
		})
	}
	if _u.mutation.AssigneesJSONCleared() {
		_spec.ClearField(workitem.FieldAssigneesJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.Milestone(); ok {
		_spec.SetField(workitem.FieldMilestone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Draft(); ok {
		_spec.SetField(workitem.FieldDraft, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Merged(); ok {
		_spec.SetField(workitem.FieldMerged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HTMLURL(); ok {
		_spec.SetField(workitem.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceUpdatedAt(); ok {
		_spec.SetField(workitem.FieldSourceUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StateHash(); ok {
		_spec.SetField(workitem.FieldStateHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewState(); ok {
		_spec.SetField(workitem.FieldReviewState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewDecision(); ok {
		_spec.SetField(workitem.FieldReviewDecision, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reviewers(); ok {
		_spec.SetField(workitem.FieldReviewers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReviewers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workitem.FieldReviewers, value)
		})
	}
	if _u.mutation.ReviewersCleared() {
		_spec.ClearField(workitem.FieldReviewers, field.TypeJSON)
	}
	if value, ok := _u.mutation.CheckStatus(); ok {
		_spec.SetField(workitem.FieldCheckStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CheckConclusion(); ok {
		_spec.SetField(workitem.FieldCheckConclusion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChecksTotal(); ok {
		_spec.SetField(workitem.FieldChecksTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChecksTotal(); ok {
		_spec.AddField(workitem.FieldChecksTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChecksPassed(); ok {
		_spec.SetField(workitem.FieldChecksPassed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChecksPassed(); ok {
		_spec.AddField(workitem.FieldChecksPassed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Ignored(); ok {
		_spec.SetField(workitem.FieldIgnored, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkItemUpdateOne is the builder for updating a single WorkItem entity.
type WorkItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkItemMutation
}

// SetRepositoryID sets the "repository_id" field.
func (_u *WorkItemUpdateOne) SetRepositoryID(v string) *WorkItemUpdateOne {
	_u.mutation.SetRepositoryID(v)
	return _u
}

// SetNillableRepositoryID sets the "repository_id" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableRepositoryID(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetRepositoryID(*v)
	}
	return _u
}

// SetNumber sets the "number" field.
func (_u *WorkItemUpdateOne) SetNumber(v int) *WorkItemUpdateOne {
	_u.mutation.ResetNumber()
	_u.mutation.SetNumber(v)
	return _u
}

// SetNillableNumber sets the "number" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableNumber(v *int) *WorkItemUpdateOne {
	if v != nil {
		_u.SetNumber(*v)
	}
	return _u
}

// AddNumber adds value to the "number" field.
func (_u *WorkItemUpdateOne) AddNumber(v int) *WorkItemUpdateOne {
	_u.mutation.AddNumber(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *WorkItemUpdateOne) SetKind(v string) *WorkItemUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableKind(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *WorkItemUpdateOne) SetState(v string) *WorkItemUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableState(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *WorkItemUpdateOne) SetTitle(v string) *WorkItemUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableTitle(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *WorkItemUpdateOne) SetAuthor(v string) *WorkItemUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableAuthor(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetLabelsJSON sets the "labels_json" field.
func (_u *WorkItemUpdateOne) SetLabelsJSON(v []interface{}) *WorkItemUpdateOne {
	_u.mutation.SetLabelsJSON(v)
	return _u
}

// AppendLabelsJSON appends value to the "labels_json" field.
func (_u *WorkItemUpdateOne) AppendLabelsJSON(v []interface{}) *WorkItemUpdateOne {
	_u.mutation.AppendLabelsJSON(v)
	return _u
}

// ClearLabelsJSON clears the value of the "labels_json" field.
func (_u *WorkItemUpdateOne) ClearLabelsJSON() *WorkItemUpdateOne {
	_u.mutation.ClearLabelsJSON()
	return _u
}

// SetAssigneesJSON sets the "assignees_json" field.
func (_u *WorkItemUpdateOne) SetAssigneesJSON(v []interface{}) *WorkItemUpdateOne {
	_u.mutation.SetAssigneesJSON(v)
	return _u
}

// AppendAssigneesJSON appends value to the "assignees_json" field.
func (_u *WorkItemUpdateOne) AppendAssigneesJSON(v []interface{}) *WorkItemUpdateOne {
	_u.mutation.AppendAssigneesJSON(v)
	return _u
}

// ClearAssigneesJSON clears the value of the "assignees_json" field.
func (_u *WorkItemUpdateOne) ClearAssigneesJSON() *WorkItemUpdateOne {
	_u.mutation.ClearAssigneesJSON()
	return _u
}

// SetMilestone sets the "milestone" field.
func (_u *WorkItemUpdateOne) SetMilestone(v string) *WorkItemUpdateOne {
	_u.mutation.SetMilestone(v)
	return _u
}

// SetNillableMilestone sets the "milestone" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableMilestone(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetMilestone(*v)
	}
	return _u
}

// SetDraft sets the "draft" field.
func (_u *WorkItemUpdateOne) SetDraft(v bool) *WorkItemUpdateOne {
	_u.mutation.SetDraft(v)
	return _u
}

// SetNillableDraft sets the "draft" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableDraft(v *bool) *WorkItemUpdateOne {
	if v != nil {
		_u.SetDraft(*v)
	}
	return _u
}

// SetMerged sets the "merged" field.
func (_u *WorkItemUpdateOne) SetMerged(v bool) *WorkItemUpdateOne {
	_u.mutation.SetMerged(v)
	return _u
}

// SetNillableMerged sets the "merged" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableMerged(v *bool) *WorkItemUpdateOne {
	if v != nil {
		_u.SetMerged(*v)
	}
	return _u
}

// SetHTMLURL sets the "html_url" field.
func (_u *WorkItemUpdateOne) SetHTMLURL(v string) *WorkItemUpdateOne {
	_u.mutation.SetHTMLURL(v)
	return _u
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableHTMLURL(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetHTMLURL(*v)
	}
	return _u
}

// SetSourceUpdatedAt sets the "source_updated_at" field.
func (_u *WorkItemUpdateOne) SetSourceUpdatedAt(v time.Time) *WorkItemUpdateOne {
	_u.mutation.SetSourceUpdatedAt(v)
	return _u
}

// SetNillableSourceUpdatedAt sets the "source_updated_at" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableSourceUpdatedAt(v *time.Time) *WorkItemUpdateOne {
	if v != nil {
		_u.SetSourceUpdatedAt(*v)
	}
	return _u
}

// SetStateHash sets the "state_hash" field.
func (_u *WorkItemUpdateOne) SetStateHash(v string) *WorkItemUpdateOne {
	_u.mutation.SetStateHash(v)
	return _u
}

// SetNillableStateHash sets the "state_hash" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableStateHash(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetStateHash(*v)
	}
	return _u
}

// SetReviewState sets the "review_state" field.
func (_u *WorkItemUpdateOne) SetReviewState(v string) *WorkItemUpdateOne {
	_u.mutation.SetReviewState(v)
	return _u
}

// SetNillableReviewState sets the "review_state" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableReviewState(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetReviewState(*v)
	}
	return _u
}

// SetReviewDecision sets the "review_decision" field.
func (_u *WorkItemUpdateOne) SetReviewDecision(v string) *WorkItemUpdateOne {
	_u.mutation.SetReviewDecision(v)
	return _u
}

// SetNillableReviewDecision sets the "review_decision" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableReviewDecision(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetReviewDecision(*v)
	}
	return _u
}

// SetReviewers sets the "reviewers" field.
func (_u *WorkItemUpdateOne) SetReviewers(v []string) *WorkItemUpdateOne {
	_u.mutation.SetReviewers(v)
	return _u
}

// AppendReviewers appends value to the "reviewers" field.
func (_u *WorkItemUpdateOne) AppendReviewers(v []string) *WorkItemUpdateOne {
	_u.mutation.AppendReviewers(v)
	return _u
}

// ClearReviewers clears the value of the "reviewers" field.
func (_u *WorkItemUpdateOne) ClearReviewers() *WorkItemUpdateOne {
	_u.mutation.ClearReviewers()
	return _u
}

// SetCheckStatus sets the "check_status" field.
func (_u *WorkItemUpdateOne) SetCheckStatus(v string) *WorkItemUpdateOne {
	_u.mutation.SetCheckStatus(v)
	return _u
}

// SetNillableCheckStatus sets the "check_status" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableCheckStatus(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetCheckStatus(*v)
	}
	return _u
}

// SetCheckConclusion sets the "check_conclusion" field.
func (_u *WorkItemUpdateOne) SetCheckConclusion(v string) *WorkItemUpdateOne {
	_u.mutation.SetCheckConclusion(v)
	return _u
}

// SetNillableCheckConclusion sets the "check_conclusion" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableCheckConclusion(v *string) *WorkItemUpdateOne {
	if v != nil {
		_u.SetCheckConclusion(*v)
	}
	return _u
}

// SetChecksTotal sets the "checks_total" field.
func (_u *WorkItemUpdateOne) SetChecksTotal(v int) *WorkItemUpdateOne {
	_u.mutation.ResetChecksTotal()
	_u.mutation.SetChecksTotal(v)
	return _u
}

// SetNillableChecksTotal sets the "checks_total" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableChecksTotal(v *int) *WorkItemUpdateOne {
	if v != nil {
		_u.SetChecksTotal(*v)
	}
	return _u
}

// AddChecksTotal adds value to the "checks_total" field.
func (_u *WorkItemUpdateOne) AddChecksTotal(v int) *WorkItemUpdateOne {
	_u.mutation.AddChecksTotal(v)
	return _u
}

// SetChecksPassed sets the "checks_passed" field.
func (_u *WorkItemUpdateOne) SetChecksPassed(v int) *WorkItemUpdateOne {
	_u.mutation.ResetChecksPassed()
	_u.mutation.SetChecksPassed(v)
	return _u
}

// SetNillableChecksPassed sets the "checks_passed" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableChecksPassed(v *int) *WorkItemUpdateOne {
	if v != nil {
		_u.SetChecksPassed(*v)
	}
	return _u
}

// AddChecksPassed adds value to the "checks_passed" field.
func (_u *WorkItemUpdateOne) AddChecksPassed(v int) *WorkItemUpdateOne {
	_u.mutation.AddChecksPassed(v)
	return _u
}

// SetIgnored sets the "ignored" field.
func (_u *WorkItemUpdateOne) SetIgnored(v bool) *WorkItemUpdateOne {
	_u.mutation.SetIgnored(v)
	return _u
}

// SetNillableIgnored sets the "ignored" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableIgnored(v *bool) *WorkItemUpdateOne {
	if v != nil {
		_u.SetIgnored(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkItemUpdateOne) SetUpdatedAt(v time.Time) *WorkItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WorkItemUpdateOne) SetNillableUpdatedAt(v *time.Time) *WorkItemUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the WorkItemMutation object of the builder.
func (_u *WorkItemUpdateOne) Mutation() *WorkItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkItemUpdate builder.
func (_u *WorkItemUpdateOne) Where(ps ...predicate.WorkItem) *WorkItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkItemUpdateOne) Select(field string, fields ...string) *WorkItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkItem entity.
func (_u *WorkItemUpdateOne) Save(ctx context.Context) (*WorkItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkItemUpdateOne) SaveX(ctx context.Context) *WorkItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkItemUpdateOne) sqlSave(ctx context.Context) (_node *WorkItem, err error) {
	_spec := sqlgraph.NewUpdateSpec(workitem.Table, workitem.Columns, sqlgraph.NewFieldSpec(workitem.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workitem.FieldID)
		for _, f := range fields {
			if !workitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RepositoryID(); ok {
		_spec.SetField(workitem.FieldRepositoryID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Number(); ok {
		_spec.SetField(workitem.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumber(); ok {
		_spec.AddField(workitem.FieldNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(workitem.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(workitem.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(workitem.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(workitem.FieldAuthor, field.TypeString, value)
	}
	if value, ok := _u.mutation.LabelsJSON(); ok {
		_spec.SetField(workitem.FieldLabelsJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLabelsJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workitem.FieldLabelsJSON, value)
		})
	}
	if _u.mutation.LabelsJSONCleared() {
		_spec.ClearField(workitem.FieldLabelsJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.AssigneesJSON(); ok {
		_spec.SetField(workitem.FieldAssigneesJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAssigneesJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workitem.FieldAssigneesJSON, value)
		})
	}
	if _u.mutation.AssigneesJSONCleared() {
		_spec.ClearField(workitem.FieldAssigneesJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.Milestone(); ok {
		_spec.SetField(workitem.FieldMilestone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Draft(); ok {
		_spec.SetField(workitem.FieldDraft, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Merged(); ok {
		_spec.SetField(workitem.FieldMerged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HTMLURL(); ok {
		_spec.SetField(workitem.FieldHTMLURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceUpdatedAt(); ok {
		_spec.SetField(workitem.FieldSourceUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StateHash(); ok {
		_spec.SetField(workitem.FieldStateHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewState(); ok {
		_spec.SetField(workitem.FieldReviewState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewDecision(); ok {
		_spec.SetField(workitem.FieldReviewDecision, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reviewers(); ok {
		_spec.SetField(workitem.FieldReviewers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReviewers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workitem.FieldReviewers, value)
		})
	}
	if _u.mutation.ReviewersCleared() {
		_spec.ClearField(workitem.FieldReviewers, field.TypeJSON)
	}
	if value, ok := _u.mutation.CheckStatus(); ok {
		_spec.SetField(workitem.FieldCheckStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CheckConclusion(); ok {
		_spec.SetField(workitem.FieldCheckConclusion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChecksTotal(); ok {
		_spec.SetField(workitem.FieldChecksTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChecksTotal(); ok {
		_spec.AddField(workitem.FieldChecksTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChecksPassed(); ok {
		_spec.SetField(workitem.FieldChecksPassed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChecksPassed(); ok {
		_spec.AddField(workitem.FieldChecksPassed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Ignored(); ok {
		_spec.SetField(workitem.FieldIgnored, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workitem.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &WorkItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
