// Code generated by ent, DO NOT EDIT.

package githubinstallation

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the githubinstallation type in the database.
	Label = "git_hub_installation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInstallationID holds the string denoting the installation_id field in the database.
	FieldInstallationID = "installation_id"
	// FieldAccountLogin holds the string denoting the account_login field in the database.
	FieldAccountLogin = "account_login"
	// FieldAccountType holds the string denoting the account_type field in the database.
	FieldAccountType = "account_type"
	// FieldTargetType holds the string denoting the target_type field in the database.
	FieldTargetType = "target_type"
	// FieldPermissionsJSON holds the string denoting the permissions_json field in the database.
	FieldPermissionsJSON = "permissions_json"
	// FieldSuspended holds the string denoting the suspended field in the database.
	FieldSuspended = "suspended"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the githubinstallation in the database.
	Table = "git_hub_installations"
)

// Columns holds all SQL columns for githubinstallation fields.
var Columns = []string{
	FieldID,
	FieldInstallationID,
	FieldAccountLogin,
	FieldAccountType,
	FieldTargetType,
	FieldPermissionsJSON,
	FieldSuspended,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTargetType holds the default value on creation for the "target_type" field.
	DefaultTargetType string
	// DefaultSuspended holds the default value on creation for the "suspended" field.
	DefaultSuspended string
)

// OrderOption defines the ordering options for the GitHubInstallation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInstallationID orders the results by the installation_id field.
func ByInstallationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallationID, opts...).ToFunc()
}

// ByAccountLogin orders the results by the account_login field.
func ByAccountLogin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountLogin, opts...).ToFunc()
}

// ByAccountType orders the results by the account_type field.
func ByAccountType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountType, opts...).ToFunc()
}

// ByTargetType orders the results by the target_type field.
func ByTargetType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetType, opts...).ToFunc()
}

// BySuspended orders the results by the suspended field.
func BySuspended(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuspended, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
