// Code generated by ent, DO NOT EDIT.

package workitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldID, id))
}

// RepositoryID applies equality check predicate on the "repository_id" field. It's identical to RepositoryIDEQ.
func RepositoryID(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldRepositoryID, v))
}

// Number applies equality check predicate on the "number" field. It's identical to NumberEQ.
func Number(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldNumber, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldKind, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldState, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldTitle, v))
}

// Author applies equality check predicate on the "author" field. It's identical to AuthorEQ.
func Author(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldAuthor, v))
}

// Milestone applies equality check predicate on the "milestone" field. It's identical to MilestoneEQ.
func Milestone(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldMilestone, v))
}

// Draft applies equality check predicate on the "draft" field. It's identical to DraftEQ.
func Draft(v bool) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldDraft, v))
}

// Merged applies equality check predicate on the "merged" field. It's identical to MergedEQ.
func Merged(v bool) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldMerged, v))
}

// HTMLURL applies equality check predicate on the "html_url" field. It's identical to HTMLURLEQ.
func HTMLURL(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldHTMLURL, v))
}

// SourceUpdatedAt applies equality check predicate on the "source_updated_at" field. It's identical to SourceUpdatedAtEQ.
func SourceUpdatedAt(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldSourceUpdatedAt, v))
}

// StateHash applies equality check predicate on the "state_hash" field. It's identical to StateHashEQ.
func StateHash(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldStateHash, v))
}

// ReviewState applies equality check predicate on the "review_state" field. It's identical to ReviewStateEQ.
func ReviewState(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldReviewState, v))
}

// ReviewDecision applies equality check predicate on the "review_decision" field. It's identical to ReviewDecisionEQ.
func ReviewDecision(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldReviewDecision, v))
}

// CheckStatus applies equality check predicate on the "check_status" field. It's identical to CheckStatusEQ.
func CheckStatus(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldCheckStatus, v))
}

// CheckConclusion applies equality check predicate on the "check_conclusion" field. It's identical to CheckConclusionEQ.
func CheckConclusion(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldCheckConclusion, v))
}

// ChecksTotal applies equality check predicate on the "checks_total" field. It's identical to ChecksTotalEQ.
func ChecksTotal(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldChecksTotal, v))
}

// ChecksPassed applies equality check predicate on the "checks_passed" field. It's identical to ChecksPassedEQ.
func ChecksPassed(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldChecksPassed, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// RepositoryIDEQ applies the EQ predicate on the "repository_id" field.
func RepositoryIDEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldRepositoryID, v))
}

// RepositoryIDNEQ applies the NEQ predicate on the "repository_id" field.
func RepositoryIDNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldRepositoryID, v))
}

// RepositoryIDIn applies the In predicate on the "repository_id" field.
func RepositoryIDIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldRepositoryID, vs...))
}

// RepositoryIDNotIn applies the NotIn predicate on the "repository_id" field.
func RepositoryIDNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldRepositoryID, vs...))
}

// RepositoryIDGT applies the GT predicate on the "repository_id" field.
func RepositoryIDGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldRepositoryID, v))
}

// RepositoryIDGTE applies the GTE predicate on the "repository_id" field.
func RepositoryIDGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldRepositoryID, v))
}

// RepositoryIDLT applies the LT predicate on the "repository_id" field.
func RepositoryIDLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldRepositoryID, v))
}

// RepositoryIDLTE applies the LTE predicate on the "repository_id" field.
func RepositoryIDLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldRepositoryID, v))
}

// RepositoryIDContains applies the Contains predicate on the "repository_id" field.
func RepositoryIDContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldRepositoryID, v))
}

// RepositoryIDHasPrefix applies the HasPrefix predicate on the "repository_id" field.
func RepositoryIDHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldRepositoryID, v))
}

// RepositoryIDHasSuffix applies the HasSuffix predicate on the "repository_id" field.
func RepositoryIDHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldRepositoryID, v))
}

// RepositoryIDEqualFold applies the EqualFold predicate on the "repository_id" field.
func RepositoryIDEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldRepositoryID, v))
}

// RepositoryIDContainsFold applies the ContainsFold predicate on the "repository_id" field.
func RepositoryIDContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldRepositoryID, v))
}

// NumberEQ applies the EQ predicate on the "number" field.
func NumberEQ(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "number" field.
func NumberNEQ(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "number" field.
func NumberIn(vs ...int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "number" field.
func NumberNotIn(vs ...int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "number" field.
func NumberGT(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "number" field.
func NumberGTE(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "number" field.
func NumberLT(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "number" field.
func NumberLTE(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldNumber, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldKind, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldState, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldTitle, v))
}

// AuthorEQ applies the EQ predicate on the "author" field.
func AuthorEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldAuthor, v))
}

// AuthorNEQ applies the NEQ predicate on the "author" field.
func AuthorNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldAuthor, v))
}

// AuthorIn applies the In predicate on the "author" field.
func AuthorIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldAuthor, vs...))
}

// AuthorNotIn applies the NotIn predicate on the "author" field.
func AuthorNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldAuthor, vs...))
}

// AuthorGT applies the GT predicate on the "author" field.
func AuthorGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldAuthor, v))
}

// AuthorGTE applies the GTE predicate on the "author" field.
func AuthorGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldAuthor, v))
}

// AuthorLT applies the LT predicate on the "author" field.
func AuthorLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldAuthor, v))
}

// AuthorLTE applies the LTE predicate on the "author" field.
func AuthorLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldAuthor, v))
}

// AuthorContains applies the Contains predicate on the "author" field.
func AuthorContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldAuthor, v))
}

// AuthorHasPrefix applies the HasPrefix predicate on the "author" field.
func AuthorHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldAuthor, v))
}

// AuthorHasSuffix applies the HasSuffix predicate on the "author" field.
func AuthorHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldAuthor, v))
}

// AuthorEqualFold applies the EqualFold predicate on the "author" field.
func AuthorEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldAuthor, v))
}

// AuthorContainsFold applies the ContainsFold predicate on the "author" field.
func AuthorContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldAuthor, v))
}

// LabelsJSONIsNil applies the IsNil predicate on the "labels_json" field.
func LabelsJSONIsNil() predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIsNull(FieldLabelsJSON))
}

// LabelsJSONNotNil applies the NotNil predicate on the "labels_json" field.
func LabelsJSONNotNil() predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotNull(FieldLabelsJSON))
}

// AssigneesJSONIsNil applies the IsNil predicate on the "assignees_json" field.
func AssigneesJSONIsNil() predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIsNull(FieldAssigneesJSON))
}

// AssigneesJSONNotNil applies the NotNil predicate on the "assignees_json" field.
func AssigneesJSONNotNil() predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotNull(FieldAssigneesJSON))
}

// MilestoneEQ applies the EQ predicate on the "milestone" field.
func MilestoneEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldMilestone, v))
}

// MilestoneNEQ applies the NEQ predicate on the "milestone" field.
func MilestoneNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldMilestone, v))
}

// MilestoneIn applies the In predicate on the "milestone" field.
func MilestoneIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldMilestone, vs...))
}

// MilestoneNotIn applies the NotIn predicate on the "milestone" field.
func MilestoneNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldMilestone, vs...))
}

// MilestoneGT applies the GT predicate on the "milestone" field.
func MilestoneGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldMilestone, v))
}

// MilestoneGTE applies the GTE predicate on the "milestone" field.
func MilestoneGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldMilestone, v))
}

// MilestoneLT applies the LT predicate on the "milestone" field.
func MilestoneLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldMilestone, v))
}

// MilestoneLTE applies the LTE predicate on the "milestone" field.
func MilestoneLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldMilestone, v))
}

// MilestoneContains applies the Contains predicate on the "milestone" field.
func MilestoneContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldMilestone, v))
}

// MilestoneHasPrefix applies the HasPrefix predicate on the "milestone" field.
func MilestoneHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldMilestone, v))
}

// MilestoneHasSuffix applies the HasSuffix predicate on the "milestone" field.
func MilestoneHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldMilestone, v))
}

// MilestoneEqualFold applies the EqualFold predicate on the "milestone" field.
func MilestoneEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldMilestone, v))
}

// MilestoneContainsFold applies the ContainsFold predicate on the "milestone" field.
func MilestoneContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldMilestone, v))
}

// DraftEQ applies the EQ predicate on the "draft" field.
func DraftEQ(v bool) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldDraft, v))
}

// DraftNEQ applies the NEQ predicate on the "draft" field.
func DraftNEQ(v bool) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldDraft, v))
}

// MergedEQ applies the EQ predicate on the "merged" field.
func MergedEQ(v bool) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldMerged, v))
}

// MergedNEQ applies the NEQ predicate on the "merged" field.
func MergedNEQ(v bool) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldMerged, v))
}

// HTMLURLEQ applies the EQ predicate on the "html_url" field.
func HTMLURLEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldHTMLURL, v))
}

// HTMLURLNEQ applies the NEQ predicate on the "html_url" field.
func HTMLURLNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldHTMLURL, v))
}

// HTMLURLIn applies the In predicate on the "html_url" field.
func HTMLURLIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldHTMLURL, vs...))
}

// HTMLURLNotIn applies the NotIn predicate on the "html_url" field.
func HTMLURLNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldHTMLURL, vs...))
}

// HTMLURLGT applies the GT predicate on the "html_url" field.
func HTMLURLGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldHTMLURL, v))
}

// HTMLURLGTE applies the GTE predicate on the "html_url" field.
func HTMLURLGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldHTMLURL, v))
}

// HTMLURLLT applies the LT predicate on the "html_url" field.
func HTMLURLLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldHTMLURL, v))
}

// HTMLURLLTE applies the LTE predicate on the "html_url" field.
func HTMLURLLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldHTMLURL, v))
}

// HTMLURLContains applies the Contains predicate on the "html_url" field.
func HTMLURLContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldHTMLURL, v))
}

// HTMLURLHasPrefix applies the HasPrefix predicate on the "html_url" field.
func HTMLURLHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldHTMLURL, v))
}

// HTMLURLHasSuffix applies the HasSuffix predicate on the "html_url" field.
func HTMLURLHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldHTMLURL, v))
}

// HTMLURLEqualFold applies the EqualFold predicate on the "html_url" field.
func HTMLURLEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldHTMLURL, v))
}

// HTMLURLContainsFold applies the ContainsFold predicate on the "html_url" field.
func HTMLURLContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldHTMLURL, v))
}

// SourceUpdatedAtEQ applies the EQ predicate on the "source_updated_at" field.
func SourceUpdatedAtEQ(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtNEQ applies the NEQ predicate on the "source_updated_at" field.
func SourceUpdatedAtNEQ(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtIn applies the In predicate on the "source_updated_at" field.
func SourceUpdatedAtIn(vs ...time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldSourceUpdatedAt, vs...))
}

// SourceUpdatedAtNotIn applies the NotIn predicate on the "source_updated_at" field.
func SourceUpdatedAtNotIn(vs ...time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldSourceUpdatedAt, vs...))
}

// SourceUpdatedAtGT applies the GT predicate on the "source_updated_at" field.
func SourceUpdatedAtGT(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtGTE applies the GTE predicate on the "source_updated_at" field.
func SourceUpdatedAtGTE(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtLT applies the LT predicate on the "source_updated_at" field.
func SourceUpdatedAtLT(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtLTE applies the LTE predicate on the "source_updated_at" field.
func SourceUpdatedAtLTE(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldSourceUpdatedAt, v))
}

// StateHashEQ applies the EQ predicate on the "state_hash" field.
func StateHashEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldStateHash, v))
}

// StateHashNEQ applies the NEQ predicate on the "state_hash" field.
func StateHashNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldStateHash, v))
}

// StateHashIn applies the In predicate on the "state_hash" field.
func StateHashIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldStateHash, vs...))
}

// StateHashNotIn applies the NotIn predicate on the "state_hash" field.
func StateHashNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldStateHash, vs...))
}

// StateHashGT applies the GT predicate on the "state_hash" field.
func StateHashGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldStateHash, v))
}

// StateHashGTE applies the GTE predicate on the "state_hash" field.
func StateHashGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldStateHash, v))
}

// StateHashLT applies the LT predicate on the "state_hash" field.
func StateHashLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldStateHash, v))
}

// StateHashLTE applies the LTE predicate on the "state_hash" field.
func StateHashLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldStateHash, v))
}

// StateHashContains applies the Contains predicate on the "state_hash" field.
func StateHashContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldStateHash, v))
}

// StateHashHasPrefix applies the HasPrefix predicate on the "state_hash" field.
func StateHashHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldStateHash, v))
}

// StateHashHasSuffix applies the HasSuffix predicate on the "state_hash" field.
func StateHashHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldStateHash, v))
}

// StateHashEqualFold applies the EqualFold predicate on the "state_hash" field.
func StateHashEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldStateHash, v))
}

// StateHashContainsFold applies the ContainsFold predicate on the "state_hash" field.
func StateHashContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldStateHash, v))
}

// ReviewStateEQ applies the EQ predicate on the "review_state" field.
func ReviewStateEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldReviewState, v))
}

// ReviewStateNEQ applies the NEQ predicate on the "review_state" field.
func ReviewStateNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldReviewState, v))
}

// ReviewStateIn applies the In predicate on the "review_state" field.
func ReviewStateIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldReviewState, vs...))
}

// ReviewStateNotIn applies the NotIn predicate on the "review_state" field.
func ReviewStateNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldReviewState, vs...))
}

// ReviewStateGT applies the GT predicate on the "review_state" field.
func ReviewStateGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldReviewState, v))
}

// ReviewStateGTE applies the GTE predicate on the "review_state" field.
func ReviewStateGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldReviewState, v))
}

// ReviewStateLT applies the LT predicate on the "review_state" field.
func ReviewStateLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldReviewState, v))
}

// ReviewStateLTE applies the LTE predicate on the "review_state" field.
func ReviewStateLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldReviewState, v))
}

// ReviewStateContains applies the Contains predicate on the "review_state" field.
func ReviewStateContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldReviewState, v))
}

// ReviewStateHasPrefix applies the HasPrefix predicate on the "review_state" field.
func ReviewStateHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldReviewState, v))
}

// ReviewStateHasSuffix applies the HasSuffix predicate on the "review_state" field.
func ReviewStateHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldReviewState, v))
}

// ReviewStateEqualFold applies the EqualFold predicate on the "review_state" field.
func ReviewStateEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldReviewState, v))
}

// ReviewStateContainsFold applies the ContainsFold predicate on the "review_state" field.
func ReviewStateContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldReviewState, v))
}

// ReviewDecisionEQ applies the EQ predicate on the "review_decision" field.
func ReviewDecisionEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldReviewDecision, v))
}

// ReviewDecisionNEQ applies the NEQ predicate on the "review_decision" field.
func ReviewDecisionNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldReviewDecision, v))
}

// ReviewDecisionIn applies the In predicate on the "review_decision" field.
func ReviewDecisionIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldReviewDecision, vs...))
}

// ReviewDecisionNotIn applies the NotIn predicate on the "review_decision" field.
func ReviewDecisionNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldReviewDecision, vs...))
}

// ReviewDecisionGT applies the GT predicate on the "review_decision" field.
func ReviewDecisionGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldReviewDecision, v))
}

// ReviewDecisionGTE applies the GTE predicate on the "review_decision" field.
func ReviewDecisionGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldReviewDecision, v))
}

// ReviewDecisionLT applies the LT predicate on the "review_decision" field.
func ReviewDecisionLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldReviewDecision, v))
}

// ReviewDecisionLTE applies the LTE predicate on the "review_decision" field.
func ReviewDecisionLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldReviewDecision, v))
}

// ReviewDecisionContains applies the Contains predicate on the "review_decision" field.
func ReviewDecisionContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldReviewDecision, v))
}

// ReviewDecisionHasPrefix applies the HasPrefix predicate on the "review_decision" field.
func ReviewDecisionHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldReviewDecision, v))
}

// ReviewDecisionHasSuffix applies the HasSuffix predicate on the "review_decision" field.
func ReviewDecisionHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldReviewDecision, v))
}

// ReviewDecisionEqualFold applies the EqualFold predicate on the "review_decision" field.
func ReviewDecisionEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldReviewDecision, v))
}

// ReviewDecisionContainsFold applies the ContainsFold predicate on the "review_decision" field.
func ReviewDecisionContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldReviewDecision, v))
}

// ReviewersIsNil applies the IsNil predicate on the "reviewers" field.
func ReviewersIsNil() predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIsNull(FieldReviewers))
}

// ReviewersNotNil applies the NotNil predicate on the "reviewers" field.
func ReviewersNotNil() predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotNull(FieldReviewers))
}

// CheckStatusEQ applies the EQ predicate on the "check_status" field.
func CheckStatusEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldCheckStatus, v))
}

// CheckStatusNEQ applies the NEQ predicate on the "check_status" field.
func CheckStatusNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldCheckStatus, v))
}

// CheckStatusIn applies the In predicate on the "check_status" field.
func CheckStatusIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldCheckStatus, vs...))
}

// CheckStatusNotIn applies the NotIn predicate on the "check_status" field.
func CheckStatusNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldCheckStatus, vs...))
}

// CheckStatusGT applies the GT predicate on the "check_status" field.
func CheckStatusGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldCheckStatus, v))
}

// CheckStatusGTE applies the GTE predicate on the "check_status" field.
func CheckStatusGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldCheckStatus, v))
}

// CheckStatusLT applies the LT predicate on the "check_status" field.
func CheckStatusLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldCheckStatus, v))
}

// CheckStatusLTE applies the LTE predicate on the "check_status" field.
func CheckStatusLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldCheckStatus, v))
}

// CheckStatusContains applies the Contains predicate on the "check_status" field.
func CheckStatusContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldCheckStatus, v))
}

// CheckStatusHasPrefix applies the HasPrefix predicate on the "check_status" field.
func CheckStatusHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldCheckStatus, v))
}

// CheckStatusHasSuffix applies the HasSuffix predicate on the "check_status" field.
func CheckStatusHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldCheckStatus, v))
}

// CheckStatusEqualFold applies the EqualFold predicate on the "check_status" field.
func CheckStatusEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldCheckStatus, v))
}

// CheckStatusContainsFold applies the ContainsFold predicate on the "check_status" field.
func CheckStatusContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldCheckStatus, v))
}

// CheckConclusionEQ applies the EQ predicate on the "check_conclusion" field.
func CheckConclusionEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldCheckConclusion, v))
}

// CheckConclusionNEQ applies the NEQ predicate on the "check_conclusion" field.
func CheckConclusionNEQ(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldCheckConclusion, v))
}

// CheckConclusionIn applies the In predicate on the "check_conclusion" field.
func CheckConclusionIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldCheckConclusion, vs...))
}

// CheckConclusionNotIn applies the NotIn predicate on the "check_conclusion" field.
func CheckConclusionNotIn(vs ...string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldCheckConclusion, vs...))
}

// CheckConclusionGT applies the GT predicate on the "check_conclusion" field.
func CheckConclusionGT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldCheckConclusion, v))
}

// CheckConclusionGTE applies the GTE predicate on the "check_conclusion" field.
func CheckConclusionGTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldCheckConclusion, v))
}

// CheckConclusionLT applies the LT predicate on the "check_conclusion" field.
func CheckConclusionLT(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldCheckConclusion, v))
}

// CheckConclusionLTE applies the LTE predicate on the "check_conclusion" field.
func CheckConclusionLTE(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldCheckConclusion, v))
}

// CheckConclusionContains applies the Contains predicate on the "check_conclusion" field.
func CheckConclusionContains(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContains(FieldCheckConclusion, v))
}

// CheckConclusionHasPrefix applies the HasPrefix predicate on the "check_conclusion" field.
func CheckConclusionHasPrefix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasPrefix(FieldCheckConclusion, v))
}

// CheckConclusionHasSuffix applies the HasSuffix predicate on the "check_conclusion" field.
func CheckConclusionHasSuffix(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldHasSuffix(FieldCheckConclusion, v))
}

// CheckConclusionEqualFold applies the EqualFold predicate on the "check_conclusion" field.
func CheckConclusionEqualFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEqualFold(FieldCheckConclusion, v))
}

// CheckConclusionContainsFold applies the ContainsFold predicate on the "check_conclusion" field.
func CheckConclusionContainsFold(v string) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldContainsFold(FieldCheckConclusion, v))
}

// ChecksTotalEQ applies the EQ predicate on the "checks_total" field.
func ChecksTotalEQ(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldChecksTotal, v))
}

// ChecksTotalNEQ applies the NEQ predicate on the "checks_total" field.
func ChecksTotalNEQ(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldChecksTotal, v))
}

// ChecksTotalIn applies the In predicate on the "checks_total" field.
func ChecksTotalIn(vs ...int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldChecksTotal, vs...))
}

// ChecksTotalNotIn applies the NotIn predicate on the "checks_total" field.
func ChecksTotalNotIn(vs ...int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldChecksTotal, vs...))
}

// ChecksTotalGT applies the GT predicate on the "checks_total" field.
func ChecksTotalGT(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldChecksTotal, v))
}

// ChecksTotalGTE applies the GTE predicate on the "checks_total" field.
func ChecksTotalGTE(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldChecksTotal, v))
}

// ChecksTotalLT applies the LT predicate on the "checks_total" field.
func ChecksTotalLT(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldChecksTotal, v))
}

// ChecksTotalLTE applies the LTE predicate on the "checks_total" field.
func ChecksTotalLTE(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldChecksTotal, v))
}

// ChecksPassedEQ applies the EQ predicate on the "checks_passed" field.
func ChecksPassedEQ(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldChecksPassed, v))
}

// ChecksPassedNEQ applies the NEQ predicate on the "checks_passed" field.
func ChecksPassedNEQ(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldChecksPassed, v))
}

// ChecksPassedIn applies the In predicate on the "checks_passed" field.
func ChecksPassedIn(vs ...int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldChecksPassed, vs...))
}

// ChecksPassedNotIn applies the NotIn predicate on the "checks_passed" field.
func ChecksPassedNotIn(vs ...int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldChecksPassed, vs...))
}

// ChecksPassedGT applies the GT predicate on the "checks_passed" field.
func ChecksPassedGT(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldChecksPassed, v))
}

// ChecksPassedGTE applies the GTE predicate on the "checks_passed" field.
func ChecksPassedGTE(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldChecksPassed, v))
}

// ChecksPassedLT applies the LT predicate on the "checks_passed" field.
func ChecksPassedLT(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldChecksPassed, v))
}

// ChecksPassedLTE applies the LTE predicate on the "checks_passed" field.
func ChecksPassedLTE(v int) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldChecksPassed, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkItem {
	return predicate.WorkItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkItem) predicate.WorkItem {
	return predicate.WorkItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkItem) predicate.WorkItem {
	return predicate.WorkItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkItem) predicate.WorkItem {
	return predicate.WorkItem(sql.NotPredicates(p))
}
