// Code generated by ent, DO NOT EDIT.

package workitem

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the workitem type in the database.
	Label = "work_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepositoryID holds the string denoting the repository_id field in the database.
	FieldRepositoryID = "repository_id"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldLabelsJSON holds the string denoting the labels_json field in the database.
	FieldLabelsJSON = "labels_json"
	// FieldAssigneesJSON holds the string denoting the assignees_json field in the database.
	FieldAssigneesJSON = "assignees_json"
	// FieldMilestone holds the string denoting the milestone field in the database.
	FieldMilestone = "milestone"
	// FieldDraft holds the string denoting the draft field in the database.
	FieldDraft = "draft"
	// FieldMerged holds the string denoting the merged field in the database.
	FieldMerged = "merged"
	// FieldHTMLURL holds the string denoting the html_url field in the database.
	FieldHTMLURL = "html_url"
	// FieldSourceUpdatedAt holds the string denoting the source_updated_at field in the database.
	FieldSourceUpdatedAt = "source_updated_at"
	// FieldStateHash holds the string denoting the state_hash field in the database.
	FieldStateHash = "state_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the workitem in the database.
	Table = "work_items"
)

// Columns holds all SQL columns for workitem fields.
var Columns = []string{
	FieldID,
	FieldRepositoryID,
	FieldNumber,
	FieldKind,
	FieldState,
	FieldTitle,
	FieldAuthor,
	FieldLabelsJSON,
	FieldAssigneesJSON,
	FieldMilestone,
	FieldDraft,
	FieldMerged,
	FieldHTMLURL,
	FieldSourceUpdatedAt,
	FieldStateHash,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAuthor holds the default value on creation for the "author" field.
	DefaultAuthor string
	// DefaultMilestone holds the default value on creation for the "milestone" field.
	DefaultMilestone string
	// DefaultDraft holds the default value on creation for the "draft" field.
	DefaultDraft bool
	// DefaultMerged holds the default value on creation for the "merged" field.
	DefaultMerged bool
	// DefaultHTMLURL holds the default value on creation for the "html_url" field.
	DefaultHTMLURL string
)

// OrderOption defines the ordering options for the WorkItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepositoryID orders the results by the repository_id field.
func ByRepositoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryID, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByAuthor orders the results by the author field.
func ByAuthor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthor, opts...).ToFunc()
}

// ByMilestone orders the results by the milestone field.
func ByMilestone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMilestone, opts...).ToFunc()
}

// ByDraft orders the results by the draft field.
func ByDraft(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDraft, opts...).ToFunc()
}

// ByMerged orders the results by the merged field.
func ByMerged(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMerged, opts...).ToFunc()
}

// ByHTMLURL orders the results by the html_url field.
func ByHTMLURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTMLURL, opts...).ToFunc()
}

// BySourceUpdatedAt orders the results by the source_updated_at field.
func BySourceUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceUpdatedAt, opts...).ToFunc()
}

// ByStateHash orders the results by the state_hash field.
func ByStateHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStateHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
