// Code generated by ent, DO NOT EDIT.

package securityalert

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the securityalert type in the database.
	Label = "security_alert"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepositoryID holds the string denoting the repository_id field in the database.
	FieldRepositoryID = "repository_id"
	// FieldAlertKind holds the string denoting the alert_kind field in the database.
	FieldAlertKind = "alert_kind"
	// FieldAlertNumber holds the string denoting the alert_number field in the database.
	FieldAlertNumber = "alert_number"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldRuleOrDependency holds the string denoting the rule_or_dependency field in the database.
	FieldRuleOrDependency = "rule_or_dependency"
	// FieldDismissedReason holds the string denoting the dismissed_reason field in the database.
	FieldDismissedReason = "dismissed_reason"
	// FieldHTMLURL holds the string denoting the html_url field in the database.
	FieldHTMLURL = "html_url"
	// FieldSourceUpdatedAt holds the string denoting the source_updated_at field in the database.
	FieldSourceUpdatedAt = "source_updated_at"
	// FieldStateHash holds the string denoting the state_hash field in the database.
	FieldStateHash = "state_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the securityalert in the database.
	Table = "security_alerts"
)

// Columns holds all SQL columns for securityalert fields.
var Columns = []string{
	FieldID,
	FieldRepositoryID,
	FieldAlertKind,
	FieldAlertNumber,
	FieldState,
	FieldSeverity,
	FieldRuleOrDependency,
	FieldDismissedReason,
	FieldHTMLURL,
	FieldSourceUpdatedAt,
	FieldStateHash,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSeverity holds the default value on creation for the "severity" field.
	DefaultSeverity string
	// DefaultRuleOrDependency holds the default value on creation for the "rule_or_dependency" field.
	DefaultRuleOrDependency string
	// DefaultDismissedReason holds the default value on creation for the "dismissed_reason" field.
	DefaultDismissedReason string
	// DefaultHTMLURL holds the default value on creation for the "html_url" field.
	DefaultHTMLURL string
)

// OrderOption defines the ordering options for the SecurityAlert queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepositoryID orders the results by the repository_id field.
func ByRepositoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryID, opts...).ToFunc()
}

// ByAlertKind orders the results by the alert_kind field.
func ByAlertKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertKind, opts...).ToFunc()
}

// ByAlertNumber orders the results by the alert_number field.
func ByAlertNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertNumber, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// ByRuleOrDependency orders the results by the rule_or_dependency field.
func ByRuleOrDependency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleOrDependency, opts...).ToFunc()
}

// ByDismissedReason orders the results by the dismissed_reason field.
func ByDismissedReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDismissedReason, opts...).ToFunc()
}

// ByHTMLURL orders the results by the html_url field.
func ByHTMLURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTMLURL, opts...).ToFunc()
}

// BySourceUpdatedAt orders the results by the source_updated_at field.
func BySourceUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceUpdatedAt, opts...).ToFunc()
}

// ByStateHash orders the results by the state_hash field.
func ByStateHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStateHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
