// Code generated by ent, DO NOT EDIT.

package securityalert

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContainsFold(FieldID, id))
}

// RepositoryID applies equality check predicate on the "repository_id" field. It's identical to RepositoryIDEQ.
func RepositoryID(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldRepositoryID, v))
}

// AlertKind applies equality check predicate on the "alert_kind" field. It's identical to AlertKindEQ.
func AlertKind(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldAlertKind, v))
}

// AlertNumber applies equality check predicate on the "alert_number" field. It's identical to AlertNumberEQ.
func AlertNumber(v int) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldAlertNumber, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldState, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldSeverity, v))
}

// RuleOrDependency applies equality check predicate on the "rule_or_dependency" field. It's identical to RuleOrDependencyEQ.
func RuleOrDependency(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldRuleOrDependency, v))
}

// DismissedReason applies equality check predicate on the "dismissed_reason" field. It's identical to DismissedReasonEQ.
func DismissedReason(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldDismissedReason, v))
}

// HTMLURL applies equality check predicate on the "html_url" field. It's identical to HTMLURLEQ.
func HTMLURL(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldHTMLURL, v))
}

// SourceUpdatedAt applies equality check predicate on the "source_updated_at" field. It's identical to SourceUpdatedAtEQ.
func SourceUpdatedAt(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldSourceUpdatedAt, v))
}

// StateHash applies equality check predicate on the "state_hash" field. It's identical to StateHashEQ.
func StateHash(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldStateHash, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldUpdatedAt, v))
}

// RepositoryIDEQ applies the EQ predicate on the "repository_id" field.
func RepositoryIDEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldRepositoryID, v))
}

// RepositoryIDNEQ applies the NEQ predicate on the "repository_id" field.
func RepositoryIDNEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldRepositoryID, v))
}

// RepositoryIDIn applies the In predicate on the "repository_id" field.
func RepositoryIDIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldRepositoryID, vs...))
}

// RepositoryIDNotIn applies the NotIn predicate on the "repository_id" field.
func RepositoryIDNotIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldRepositoryID, vs...))
}

// RepositoryIDGT applies the GT predicate on the "repository_id" field.
func RepositoryIDGT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldRepositoryID, v))
}

// RepositoryIDGTE applies the GTE predicate on the "repository_id" field.
func RepositoryIDGTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldRepositoryID, v))
}

// RepositoryIDLT applies the LT predicate on the "repository_id" field.
func RepositoryIDLT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldRepositoryID, v))
}

// RepositoryIDLTE applies the LTE predicate on the "repository_id" field.
func RepositoryIDLTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldRepositoryID, v))
}

// RepositoryIDContains applies the Contains predicate on the "repository_id" field.
func RepositoryIDContains(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContains(FieldRepositoryID, v))
}

// RepositoryIDHasPrefix applies the HasPrefix predicate on the "repository_id" field.
func RepositoryIDHasPrefix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasPrefix(FieldRepositoryID, v))
}

// RepositoryIDHasSuffix applies the HasSuffix predicate on the "repository_id" field.
func RepositoryIDHasSuffix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasSuffix(FieldRepositoryID, v))
}

// RepositoryIDEqualFold applies the EqualFold predicate on the "repository_id" field.
func RepositoryIDEqualFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEqualFold(FieldRepositoryID, v))
}

// RepositoryIDContainsFold applies the ContainsFold predicate on the "repository_id" field.
func RepositoryIDContainsFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContainsFold(FieldRepositoryID, v))
}

// AlertKindEQ applies the EQ predicate on the "alert_kind" field.
func AlertKindEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldAlertKind, v))
}

// AlertKindNEQ applies the NEQ predicate on the "alert_kind" field.
func AlertKindNEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldAlertKind, v))
}

// AlertKindIn applies the In predicate on the "alert_kind" field.
func AlertKindIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldAlertKind, vs...))
}

// AlertKindNotIn applies the NotIn predicate on the "alert_kind" field.
func AlertKindNotIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldAlertKind, vs...))
}

// AlertKindGT applies the GT predicate on the "alert_kind" field.
func AlertKindGT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldAlertKind, v))
}

// AlertKindGTE applies the GTE predicate on the "alert_kind" field.
func AlertKindGTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldAlertKind, v))
}

// AlertKindLT applies the LT predicate on the "alert_kind" field.
func AlertKindLT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldAlertKind, v))
}

// AlertKindLTE applies the LTE predicate on the "alert_kind" field.
func AlertKindLTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldAlertKind, v))
}

// AlertKindContains applies the Contains predicate on the "alert_kind" field.
func AlertKindContains(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContains(FieldAlertKind, v))
}

// AlertKindHasPrefix applies the HasPrefix predicate on the "alert_kind" field.
func AlertKindHasPrefix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasPrefix(FieldAlertKind, v))
}

// AlertKindHasSuffix applies the HasSuffix predicate on the "alert_kind" field.
func AlertKindHasSuffix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasSuffix(FieldAlertKind, v))
}

// AlertKindEqualFold applies the EqualFold predicate on the "alert_kind" field.
func AlertKindEqualFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEqualFold(FieldAlertKind, v))
}

// AlertKindContainsFold applies the ContainsFold predicate on the "alert_kind" field.
func AlertKindContainsFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContainsFold(FieldAlertKind, v))
}

// AlertNumberEQ applies the EQ predicate on the "alert_number" field.
func AlertNumberEQ(v int) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldAlertNumber, v))
}

// AlertNumberNEQ applies the NEQ predicate on the "alert_number" field.
func AlertNumberNEQ(v int) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldAlertNumber, v))
}

// AlertNumberIn applies the In predicate on the "alert_number" field.
func AlertNumberIn(vs ...int) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldAlertNumber, vs...))
}

// AlertNumberNotIn applies the NotIn predicate on the "alert_number" field.
func AlertNumberNotIn(vs ...int) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldAlertNumber, vs...))
}

// AlertNumberGT applies the GT predicate on the "alert_number" field.
func AlertNumberGT(v int) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldAlertNumber, v))
}

// AlertNumberGTE applies the GTE predicate on the "alert_number" field.
func AlertNumberGTE(v int) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldAlertNumber, v))
}

// AlertNumberLT applies the LT predicate on the "alert_number" field.
func AlertNumberLT(v int) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldAlertNumber, v))
}

// AlertNumberLTE applies the LTE predicate on the "alert_number" field.
func AlertNumberLTE(v int) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldAlertNumber, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContainsFold(FieldState, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContainsFold(FieldSeverity, v))
}

// RuleOrDependencyEQ applies the EQ predicate on the "rule_or_dependency" field.
func RuleOrDependencyEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldRuleOrDependency, v))
}

// RuleOrDependencyNEQ applies the NEQ predicate on the "rule_or_dependency" field.
func RuleOrDependencyNEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldRuleOrDependency, v))
}

// RuleOrDependencyIn applies the In predicate on the "rule_or_dependency" field.
func RuleOrDependencyIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldRuleOrDependency, vs...))
}

// RuleOrDependencyNotIn applies the NotIn predicate on the "rule_or_dependency" field.
func RuleOrDependencyNotIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldRuleOrDependency, vs...))
}

// RuleOrDependencyGT applies the GT predicate on the "rule_or_dependency" field.
func RuleOrDependencyGT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldRuleOrDependency, v))
}

// RuleOrDependencyGTE applies the GTE predicate on the "rule_or_dependency" field.
func RuleOrDependencyGTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldRuleOrDependency, v))
}

// RuleOrDependencyLT applies the LT predicate on the "rule_or_dependency" field.
func RuleOrDependencyLT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldRuleOrDependency, v))
}

// RuleOrDependencyLTE applies the LTE predicate on the "rule_or_dependency" field.
func RuleOrDependencyLTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldRuleOrDependency, v))
}

// RuleOrDependencyContains applies the Contains predicate on the "rule_or_dependency" field.
func RuleOrDependencyContains(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContains(FieldRuleOrDependency, v))
}

// RuleOrDependencyHasPrefix applies the HasPrefix predicate on the "rule_or_dependency" field.
func RuleOrDependencyHasPrefix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasPrefix(FieldRuleOrDependency, v))
}

// RuleOrDependencyHasSuffix applies the HasSuffix predicate on the "rule_or_dependency" field.
func RuleOrDependencyHasSuffix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasSuffix(FieldRuleOrDependency, v))
}

// RuleOrDependencyEqualFold applies the EqualFold predicate on the "rule_or_dependency" field.
func RuleOrDependencyEqualFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEqualFold(FieldRuleOrDependency, v))
}

// RuleOrDependencyContainsFold applies the ContainsFold predicate on the "rule_or_dependency" field.
func RuleOrDependencyContainsFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContainsFold(FieldRuleOrDependency, v))
}

// DismissedReasonEQ applies the EQ predicate on the "dismissed_reason" field.
func DismissedReasonEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldDismissedReason, v))
}

// DismissedReasonNEQ applies the NEQ predicate on the "dismissed_reason" field.
func DismissedReasonNEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldDismissedReason, v))
}

// DismissedReasonIn applies the In predicate on the "dismissed_reason" field.
func DismissedReasonIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldDismissedReason, vs...))
}

// DismissedReasonNotIn applies the NotIn predicate on the "dismissed_reason" field.
func DismissedReasonNotIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldDismissedReason, vs...))
}

// DismissedReasonGT applies the GT predicate on the "dismissed_reason" field.
func DismissedReasonGT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldDismissedReason, v))
}

// DismissedReasonGTE applies the GTE predicate on the "dismissed_reason" field.
func DismissedReasonGTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldDismissedReason, v))
}

// DismissedReasonLT applies the LT predicate on the "dismissed_reason" field.
func DismissedReasonLT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldDismissedReason, v))
}

// DismissedReasonLTE applies the LTE predicate on the "dismissed_reason" field.
func DismissedReasonLTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldDismissedReason, v))
}

// DismissedReasonContains applies the Contains predicate on the "dismissed_reason" field.
func DismissedReasonContains(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContains(FieldDismissedReason, v))
}

// DismissedReasonHasPrefix applies the HasPrefix predicate on the "dismissed_reason" field.
func DismissedReasonHasPrefix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasPrefix(FieldDismissedReason, v))
}

// DismissedReasonHasSuffix applies the HasSuffix predicate on the "dismissed_reason" field.
func DismissedReasonHasSuffix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasSuffix(FieldDismissedReason, v))
}

// DismissedReasonEqualFold applies the EqualFold predicate on the "dismissed_reason" field.
func DismissedReasonEqualFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEqualFold(FieldDismissedReason, v))
}

// DismissedReasonContainsFold applies the ContainsFold predicate on the "dismissed_reason" field.
func DismissedReasonContainsFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContainsFold(FieldDismissedReason, v))
}

// HTMLURLEQ applies the EQ predicate on the "html_url" field.
func HTMLURLEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldHTMLURL, v))
}

// HTMLURLNEQ applies the NEQ predicate on the "html_url" field.
func HTMLURLNEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldHTMLURL, v))
}

// HTMLURLIn applies the In predicate on the "html_url" field.
func HTMLURLIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldHTMLURL, vs...))
}

// HTMLURLNotIn applies the NotIn predicate on the "html_url" field.
func HTMLURLNotIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldHTMLURL, vs...))
}

// HTMLURLGT applies the GT predicate on the "html_url" field.
func HTMLURLGT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldHTMLURL, v))
}

// HTMLURLGTE applies the GTE predicate on the "html_url" field.
func HTMLURLGTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldHTMLURL, v))
}

// HTMLURLLT applies the LT predicate on the "html_url" field.
func HTMLURLLT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldHTMLURL, v))
}

// HTMLURLLTE applies the LTE predicate on the "html_url" field.
func HTMLURLLTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldHTMLURL, v))
}

// HTMLURLContains applies the Contains predicate on the "html_url" field.
func HTMLURLContains(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContains(FieldHTMLURL, v))
}

// HTMLURLHasPrefix applies the HasPrefix predicate on the "html_url" field.
func HTMLURLHasPrefix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasPrefix(FieldHTMLURL, v))
}

// HTMLURLHasSuffix applies the HasSuffix predicate on the "html_url" field.
func HTMLURLHasSuffix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasSuffix(FieldHTMLURL, v))
}

// HTMLURLEqualFold applies the EqualFold predicate on the "html_url" field.
func HTMLURLEqualFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEqualFold(FieldHTMLURL, v))
}

// HTMLURLContainsFold applies the ContainsFold predicate on the "html_url" field.
func HTMLURLContainsFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContainsFold(FieldHTMLURL, v))
}

// SourceUpdatedAtEQ applies the EQ predicate on the "source_updated_at" field.
func SourceUpdatedAtEQ(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtNEQ applies the NEQ predicate on the "source_updated_at" field.
func SourceUpdatedAtNEQ(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtIn applies the In predicate on the "source_updated_at" field.
func SourceUpdatedAtIn(vs ...time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldSourceUpdatedAt, vs...))
}

// SourceUpdatedAtNotIn applies the NotIn predicate on the "source_updated_at" field.
func SourceUpdatedAtNotIn(vs ...time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldSourceUpdatedAt, vs...))
}

// SourceUpdatedAtGT applies the GT predicate on the "source_updated_at" field.
func SourceUpdatedAtGT(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtGTE applies the GTE predicate on the "source_updated_at" field.
func SourceUpdatedAtGTE(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtLT applies the LT predicate on the "source_updated_at" field.
func SourceUpdatedAtLT(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldSourceUpdatedAt, v))
}

// SourceUpdatedAtLTE applies the LTE predicate on the "source_updated_at" field.
func SourceUpdatedAtLTE(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldSourceUpdatedAt, v))
}

// StateHashEQ applies the EQ predicate on the "state_hash" field.
func StateHashEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldStateHash, v))
}

// StateHashNEQ applies the NEQ predicate on the "state_hash" field.
func StateHashNEQ(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldStateHash, v))
}

// StateHashIn applies the In predicate on the "state_hash" field.
func StateHashIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldStateHash, vs...))
}

// StateHashNotIn applies the NotIn predicate on the "state_hash" field.
func StateHashNotIn(vs ...string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldStateHash, vs...))
}

// StateHashGT applies the GT predicate on the "state_hash" field.
func StateHashGT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldStateHash, v))
}

// StateHashGTE applies the GTE predicate on the "state_hash" field.
func StateHashGTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldStateHash, v))
}

// StateHashLT applies the LT predicate on the "state_hash" field.
func StateHashLT(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldStateHash, v))
}

// StateHashLTE applies the LTE predicate on the "state_hash" field.
func StateHashLTE(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldStateHash, v))
}

// StateHashContains applies the Contains predicate on the "state_hash" field.
func StateHashContains(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContains(FieldStateHash, v))
}

// StateHashHasPrefix applies the HasPrefix predicate on the "state_hash" field.
func StateHashHasPrefix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasPrefix(FieldStateHash, v))
}

// StateHashHasSuffix applies the HasSuffix predicate on the "state_hash" field.
func StateHashHasSuffix(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldHasSuffix(FieldStateHash, v))
}

// StateHashEqualFold applies the EqualFold predicate on the "state_hash" field.
func StateHashEqualFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEqualFold(FieldStateHash, v))
}

// StateHashContainsFold applies the ContainsFold predicate on the "state_hash" field.
func StateHashContainsFold(v string) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldContainsFold(FieldStateHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SecurityAlert) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SecurityAlert) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SecurityAlert) predicate.SecurityAlert {
	return predicate.SecurityAlert(sql.NotPredicates(p))
}
