// Code generated by ent, DO NOT EDIT.

package notificationoutbox

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the notificationoutbox type in the database.
	Label = "notification_outbox"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldAggregateKey holds the string denoting the aggregate_key field in the database.
	FieldAggregateKey = "aggregate_key"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "next_attempt_at"
	// FieldLockedUntil holds the string denoting the locked_until field in the database.
	FieldLockedUntil = "locked_until"
	// FieldLastErrorCode holds the string denoting the last_error_code field in the database.
	FieldLastErrorCode = "last_error_code"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldBodyText holds the string denoting the body_text field in the database.
	FieldBodyText = "body_text"
	// FieldBodyJSON holds the string denoting the body_json field in the database.
	FieldBodyJSON = "body_json"
	// FieldParseMode holds the string denoting the parse_mode field in the database.
	FieldParseMode = "parse_mode"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the notificationoutbox in the database.
	Table = "notification_outbox"
)

// Columns holds all SQL columns for notificationoutbox fields.
var Columns = []string{
	FieldID,
	FieldChannelID,
	FieldEventID,
	FieldAggregateKey,
	FieldIdempotencyKey,
	FieldStatus,
	FieldAttemptCount,
	FieldNextAttemptAt,
	FieldLockedUntil,
	FieldLastErrorCode,
	FieldTitle,
	FieldBodyText,
	FieldBodyJSON,
	FieldParseMode,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAggregateKey holds the default value on creation for the "aggregate_key" field.
	DefaultAggregateKey string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// DefaultLastErrorCode holds the default value on creation for the "last_error_code" field.
	DefaultLastErrorCode string
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// DefaultParseMode holds the default value on creation for the "parse_mode" field.
	DefaultParseMode string
)

// OrderOption defines the ordering options for the NotificationOutbox queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// ByAggregateKey orders the results by the aggregate_key field.
func ByAggregateKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAggregateKey, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// ByLockedUntil orders the results by the locked_until field.
func ByLockedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedUntil, opts...).ToFunc()
}

// ByLastErrorCode orders the results by the last_error_code field.
func ByLastErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorCode, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByBodyText orders the results by the body_text field.
func ByBodyText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBodyText, opts...).ToFunc()
}

// ByParseMode orders the results by the parse_mode field.
func ByParseMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParseMode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
