// Code generated by ent, DO NOT EDIT.

package adminaccount

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the adminaccount type in the database.
	Label = "admin_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldUsernameNormalized holds the string denoting the username_normalized field in the database.
	FieldUsernameNormalized = "username_normalized"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPasswordChangedAt holds the string denoting the password_changed_at field in the database.
	FieldPasswordChangedAt = "password_changed_at"
	// FieldSingletonSlot holds the string denoting the singleton_slot field in the database.
	FieldSingletonSlot = "singleton_slot"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// Table holds the table name of the adminaccount in the database.
	Table = "admin_accounts"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "admin_sessions"
	// SessionsInverseTable is the table name for the AdminSession entity.
	// It exists in this package in order to avoid circular dependency with the "adminsession" package.
	SessionsInverseTable = "admin_sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "admin_id"
)

// Columns holds all SQL columns for adminaccount fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldUsernameNormalized,
	FieldPasswordHash,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPasswordChangedAt,
	FieldSingletonSlot,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSingletonSlot holds the default value on creation for the "singleton_slot" field.
	DefaultSingletonSlot int
)

// OrderOption defines the ordering options for the AdminAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByUsernameNormalized orders the results by the username_normalized field.
func ByUsernameNormalized(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsernameNormalized, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPasswordChangedAt orders the results by the password_changed_at field.
func ByPasswordChangedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordChangedAt, opts...).ToFunc()
}

// BySingletonSlot orders the results by the singleton_slot field.
func BySingletonSlot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSingletonSlot, opts...).ToFunc()
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
