// Code generated by ent, DO NOT EDIT.

package adminaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Silentely/Repo-Sentinel/internal/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldContainsFold(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldUsername, v))
}

// UsernameNormalized applies equality check predicate on the "username_normalized" field. It's identical to UsernameNormalizedEQ.
func UsernameNormalized(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldUsernameNormalized, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldPasswordHash, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// PasswordChangedAt applies equality check predicate on the "password_changed_at" field. It's identical to PasswordChangedAtEQ.
func PasswordChangedAt(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldPasswordChangedAt, v))
}

// SingletonSlot applies equality check predicate on the "singleton_slot" field. It's identical to SingletonSlotEQ.
func SingletonSlot(v int) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldSingletonSlot, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldContainsFold(FieldUsername, v))
}

// UsernameNormalizedEQ applies the EQ predicate on the "username_normalized" field.
func UsernameNormalizedEQ(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldUsernameNormalized, v))
}

// UsernameNormalizedNEQ applies the NEQ predicate on the "username_normalized" field.
func UsernameNormalizedNEQ(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNEQ(FieldUsernameNormalized, v))
}

// UsernameNormalizedIn applies the In predicate on the "username_normalized" field.
func UsernameNormalizedIn(vs ...string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldIn(FieldUsernameNormalized, vs...))
}

// UsernameNormalizedNotIn applies the NotIn predicate on the "username_normalized" field.
func UsernameNormalizedNotIn(vs ...string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNotIn(FieldUsernameNormalized, vs...))
}

// UsernameNormalizedGT applies the GT predicate on the "username_normalized" field.
func UsernameNormalizedGT(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGT(FieldUsernameNormalized, v))
}

// UsernameNormalizedGTE applies the GTE predicate on the "username_normalized" field.
func UsernameNormalizedGTE(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGTE(FieldUsernameNormalized, v))
}

// UsernameNormalizedLT applies the LT predicate on the "username_normalized" field.
func UsernameNormalizedLT(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLT(FieldUsernameNormalized, v))
}

// UsernameNormalizedLTE applies the LTE predicate on the "username_normalized" field.
func UsernameNormalizedLTE(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLTE(FieldUsernameNormalized, v))
}

// UsernameNormalizedContains applies the Contains predicate on the "username_normalized" field.
func UsernameNormalizedContains(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldContains(FieldUsernameNormalized, v))
}

// UsernameNormalizedHasPrefix applies the HasPrefix predicate on the "username_normalized" field.
func UsernameNormalizedHasPrefix(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldHasPrefix(FieldUsernameNormalized, v))
}

// UsernameNormalizedHasSuffix applies the HasSuffix predicate on the "username_normalized" field.
func UsernameNormalizedHasSuffix(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldHasSuffix(FieldUsernameNormalized, v))
}

// UsernameNormalizedEqualFold applies the EqualFold predicate on the "username_normalized" field.
func UsernameNormalizedEqualFold(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEqualFold(FieldUsernameNormalized, v))
}

// UsernameNormalizedContainsFold applies the ContainsFold predicate on the "username_normalized" field.
func UsernameNormalizedContainsFold(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldContainsFold(FieldUsernameNormalized, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldContainsFold(FieldPasswordHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// PasswordChangedAtEQ applies the EQ predicate on the "password_changed_at" field.
func PasswordChangedAtEQ(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldPasswordChangedAt, v))
}

// PasswordChangedAtNEQ applies the NEQ predicate on the "password_changed_at" field.
func PasswordChangedAtNEQ(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNEQ(FieldPasswordChangedAt, v))
}

// PasswordChangedAtIn applies the In predicate on the "password_changed_at" field.
func PasswordChangedAtIn(vs ...time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldIn(FieldPasswordChangedAt, vs...))
}

// PasswordChangedAtNotIn applies the NotIn predicate on the "password_changed_at" field.
func PasswordChangedAtNotIn(vs ...time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNotIn(FieldPasswordChangedAt, vs...))
}

// PasswordChangedAtGT applies the GT predicate on the "password_changed_at" field.
func PasswordChangedAtGT(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGT(FieldPasswordChangedAt, v))
}

// PasswordChangedAtGTE applies the GTE predicate on the "password_changed_at" field.
func PasswordChangedAtGTE(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGTE(FieldPasswordChangedAt, v))
}

// PasswordChangedAtLT applies the LT predicate on the "password_changed_at" field.
func PasswordChangedAtLT(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLT(FieldPasswordChangedAt, v))
}

// PasswordChangedAtLTE applies the LTE predicate on the "password_changed_at" field.
func PasswordChangedAtLTE(v time.Time) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLTE(FieldPasswordChangedAt, v))
}

// SingletonSlotEQ applies the EQ predicate on the "singleton_slot" field.
func SingletonSlotEQ(v int) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldEQ(FieldSingletonSlot, v))
}

// SingletonSlotNEQ applies the NEQ predicate on the "singleton_slot" field.
func SingletonSlotNEQ(v int) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNEQ(FieldSingletonSlot, v))
}

// SingletonSlotIn applies the In predicate on the "singleton_slot" field.
func SingletonSlotIn(vs ...int) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldIn(FieldSingletonSlot, vs...))
}

// SingletonSlotNotIn applies the NotIn predicate on the "singleton_slot" field.
func SingletonSlotNotIn(vs ...int) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldNotIn(FieldSingletonSlot, vs...))
}

// SingletonSlotGT applies the GT predicate on the "singleton_slot" field.
func SingletonSlotGT(v int) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGT(FieldSingletonSlot, v))
}

// SingletonSlotGTE applies the GTE predicate on the "singleton_slot" field.
func SingletonSlotGTE(v int) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldGTE(FieldSingletonSlot, v))
}

// SingletonSlotLT applies the LT predicate on the "singleton_slot" field.
func SingletonSlotLT(v int) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLT(FieldSingletonSlot, v))
}

// SingletonSlotLTE applies the LTE predicate on the "singleton_slot" field.
func SingletonSlotLTE(v int) predicate.AdminAccount {
	return predicate.AdminAccount(sql.FieldLTE(FieldSingletonSlot, v))
}

// HasSessions applies the HasEdge predicate on the "sessions" edge.
func HasSessions() predicate.AdminAccount {
	return predicate.AdminAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionsWith applies the HasEdge predicate on the "sessions" edge with a given conditions (other predicates).
func HasSessionsWith(preds ...predicate.AdminSession) predicate.AdminAccount {
	return predicate.AdminAccount(func(s *sql.Selector) {
		step := newSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminAccount) predicate.AdminAccount {
	return predicate.AdminAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminAccount) predicate.AdminAccount {
	return predicate.AdminAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminAccount) predicate.AdminAccount {
	return predicate.AdminAccount(sql.NotPredicates(p))
}
