// Code generated by ent, DO NOT EDIT.

package webhookdelivery

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the webhookdelivery type in the database.
	Label = "webhook_delivery"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeliveryID holds the string denoting the delivery_id field in the database.
	FieldDeliveryID = "delivery_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldRepositoryFullName holds the string denoting the repository_full_name field in the database.
	FieldRepositoryFullName = "repository_full_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldReceivedAt holds the string denoting the received_at field in the database.
	FieldReceivedAt = "received_at"
	// FieldProcessedAt holds the string denoting the processed_at field in the database.
	FieldProcessedAt = "processed_at"
	// FieldClaimToken holds the string denoting the claim_token field in the database.
	FieldClaimToken = "claim_token"
	// FieldClaimVersion holds the string denoting the claim_version field in the database.
	FieldClaimVersion = "claim_version"
	// FieldClaimedBy holds the string denoting the claimed_by field in the database.
	FieldClaimedBy = "claimed_by"
	// FieldClaimedUntil holds the string denoting the claimed_until field in the database.
	FieldClaimedUntil = "claimed_until"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldLastErrorCode holds the string denoting the last_error_code field in the database.
	FieldLastErrorCode = "last_error_code"
	// Table holds the table name of the webhookdelivery in the database.
	Table = "webhook_deliveries"
)

// Columns holds all SQL columns for webhookdelivery fields.
var Columns = []string{
	FieldID,
	FieldDeliveryID,
	FieldEventType,
	FieldAction,
	FieldRepositoryFullName,
	FieldStatus,
	FieldErrorCode,
	FieldPayload,
	FieldReceivedAt,
	FieldProcessedAt,
	FieldClaimToken,
	FieldClaimVersion,
	FieldClaimedBy,
	FieldClaimedUntil,
	FieldAttemptCount,
	FieldLastErrorCode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAction holds the default value on creation for the "action" field.
	DefaultAction string
	// DefaultRepositoryFullName holds the default value on creation for the "repository_full_name" field.
	DefaultRepositoryFullName string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultErrorCode holds the default value on creation for the "error_code" field.
	DefaultErrorCode string
	// DefaultClaimToken holds the default value on creation for the "claim_token" field.
	DefaultClaimToken string
	// DefaultClaimVersion holds the default value on creation for the "claim_version" field.
	DefaultClaimVersion int64
	// DefaultClaimedBy holds the default value on creation for the "claimed_by" field.
	DefaultClaimedBy string
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// DefaultLastErrorCode holds the default value on creation for the "last_error_code" field.
	DefaultLastErrorCode string
)

// OrderOption defines the ordering options for the WebhookDelivery queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeliveryID orders the results by the delivery_id field.
func ByDeliveryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByRepositoryFullName orders the results by the repository_full_name field.
func ByRepositoryFullName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryFullName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByReceivedAt orders the results by the received_at field.
func ByReceivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedAt, opts...).ToFunc()
}

// ByProcessedAt orders the results by the processed_at field.
func ByProcessedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedAt, opts...).ToFunc()
}

// ByClaimToken orders the results by the claim_token field.
func ByClaimToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimToken, opts...).ToFunc()
}

// ByClaimVersion orders the results by the claim_version field.
func ByClaimVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimVersion, opts...).ToFunc()
}

// ByClaimedBy orders the results by the claimed_by field.
func ByClaimedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimedBy, opts...).ToFunc()
}

// ByClaimedUntil orders the results by the claimed_until field.
func ByClaimedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimedUntil, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByLastErrorCode orders the results by the last_error_code field.
func ByLastErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorCode, opts...).ToFunc()
}
