// Code generated by ent, DO NOT EDIT.

package workflowrun

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the workflowrun type in the database.
	Label = "workflow_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepositoryID holds the string denoting the repository_id field in the database.
	FieldRepositoryID = "repository_id"
	// FieldGithubRunID holds the string denoting the github_run_id field in the database.
	FieldGithubRunID = "github_run_id"
	// FieldGithubWorkflowID holds the string denoting the github_workflow_id field in the database.
	FieldGithubWorkflowID = "github_workflow_id"
	// FieldWorkflowName holds the string denoting the workflow_name field in the database.
	FieldWorkflowName = "workflow_name"
	// FieldRunNumber holds the string denoting the run_number field in the database.
	FieldRunNumber = "run_number"
	// FieldEvent holds the string denoting the event field in the database.
	FieldEvent = "event"
	// FieldHeadBranch holds the string denoting the head_branch field in the database.
	FieldHeadBranch = "head_branch"
	// FieldHeadSha holds the string denoting the head_sha field in the database.
	FieldHeadSha = "head_sha"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldConclusion holds the string denoting the conclusion field in the database.
	FieldConclusion = "conclusion"
	// FieldPreviousConclusion holds the string denoting the previous_conclusion field in the database.
	FieldPreviousConclusion = "previous_conclusion"
	// FieldActor holds the string denoting the actor field in the database.
	FieldActor = "actor"
	// FieldRunAttempt holds the string denoting the run_attempt field in the database.
	FieldRunAttempt = "run_attempt"
	// FieldHTMLURL holds the string denoting the html_url field in the database.
	FieldHTMLURL = "html_url"
	// FieldRunStartedAt holds the string denoting the run_started_at field in the database.
	FieldRunStartedAt = "run_started_at"
	// FieldRunUpdatedAt holds the string denoting the run_updated_at field in the database.
	FieldRunUpdatedAt = "run_updated_at"
	// FieldRunCompletedAt holds the string denoting the run_completed_at field in the database.
	FieldRunCompletedAt = "run_completed_at"
	// FieldStateHash holds the string denoting the state_hash field in the database.
	FieldStateHash = "state_hash"
	// FieldIgnored holds the string denoting the ignored field in the database.
	FieldIgnored = "ignored"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the workflowrun in the database.
	Table = "workflow_runs"
)

// Columns holds all SQL columns for workflowrun fields.
var Columns = []string{
	FieldID,
	FieldRepositoryID,
	FieldGithubRunID,
	FieldGithubWorkflowID,
	FieldWorkflowName,
	FieldRunNumber,
	FieldEvent,
	FieldHeadBranch,
	FieldHeadSha,
	FieldStatus,
	FieldConclusion,
	FieldPreviousConclusion,
	FieldActor,
	FieldRunAttempt,
	FieldHTMLURL,
	FieldRunStartedAt,
	FieldRunUpdatedAt,
	FieldRunCompletedAt,
	FieldStateHash,
	FieldIgnored,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultWorkflowName holds the default value on creation for the "workflow_name" field.
	DefaultWorkflowName string
	// DefaultRunNumber holds the default value on creation for the "run_number" field.
	DefaultRunNumber int
	// DefaultEvent holds the default value on creation for the "event" field.
	DefaultEvent string
	// DefaultHeadBranch holds the default value on creation for the "head_branch" field.
	DefaultHeadBranch string
	// DefaultHeadSha holds the default value on creation for the "head_sha" field.
	DefaultHeadSha string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultActor holds the default value on creation for the "actor" field.
	DefaultActor string
	// DefaultRunAttempt holds the default value on creation for the "run_attempt" field.
	DefaultRunAttempt int
	// DefaultHTMLURL holds the default value on creation for the "html_url" field.
	DefaultHTMLURL string
	// DefaultIgnored holds the default value on creation for the "ignored" field.
	DefaultIgnored bool
)

// OrderOption defines the ordering options for the WorkflowRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepositoryID orders the results by the repository_id field.
func ByRepositoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepositoryID, opts...).ToFunc()
}

// ByGithubRunID orders the results by the github_run_id field.
func ByGithubRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubRunID, opts...).ToFunc()
}

// ByGithubWorkflowID orders the results by the github_workflow_id field.
func ByGithubWorkflowID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubWorkflowID, opts...).ToFunc()
}

// ByWorkflowName orders the results by the workflow_name field.
func ByWorkflowName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowName, opts...).ToFunc()
}

// ByRunNumber orders the results by the run_number field.
func ByRunNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunNumber, opts...).ToFunc()
}

// ByEvent orders the results by the event field.
func ByEvent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEvent, opts...).ToFunc()
}

// ByHeadBranch orders the results by the head_branch field.
func ByHeadBranch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeadBranch, opts...).ToFunc()
}

// ByHeadSha orders the results by the head_sha field.
func ByHeadSha(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeadSha, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByConclusion orders the results by the conclusion field.
func ByConclusion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConclusion, opts...).ToFunc()
}

// ByPreviousConclusion orders the results by the previous_conclusion field.
func ByPreviousConclusion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousConclusion, opts...).ToFunc()
}

// ByActor orders the results by the actor field.
func ByActor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActor, opts...).ToFunc()
}

// ByRunAttempt orders the results by the run_attempt field.
func ByRunAttempt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunAttempt, opts...).ToFunc()
}

// ByHTMLURL orders the results by the html_url field.
func ByHTMLURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTMLURL, opts...).ToFunc()
}

// ByRunStartedAt orders the results by the run_started_at field.
func ByRunStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunStartedAt, opts...).ToFunc()
}

// ByRunUpdatedAt orders the results by the run_updated_at field.
func ByRunUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunUpdatedAt, opts...).ToFunc()
}

// ByRunCompletedAt orders the results by the run_completed_at field.
func ByRunCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunCompletedAt, opts...).ToFunc()
}

// ByStateHash orders the results by the state_hash field.
func ByStateHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStateHash, opts...).ToFunc()
}

// ByIgnored orders the results by the ignored field.
func ByIgnored(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIgnored, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
